import Foundation

// Unofficial translation generated for this app — NOT the official Positive Health wording.
enum Danish {
    static let table: [String: String] = [
        "done": "Færdig",
        "cancel": "Annullér",
        "back": "Tilbage",
        "next": "Næste",
        "app_title": "Min Positive Health",
        "fill_menu": "Udfyld spindelvævet",
        "empty_title": "Udfyld dit spindelvæv",
        "empty_desc": "Positive Health ser på det, der betyder noget for dig, på tværs af seks dimensioner af sundhed. Udfyld spindelvævet for at få dit personlige overblik — et udgangspunkt for en anden slags samtale.",
        "version.adult.title": "Voksne",
        "version.adolescent.title": "Unge / unge voksne",
        "version.child.title": "Børn",
        "version.adult.age": "18+ år",
        "version.adolescent.age": "16–25 år",
        "version.child.age": "8–16 år",
        "reflect.adult": "Der mangler noget, som er vigtigt for mig:",
        "reflect.adolescent": "Følgende er særligt vigtigt for mig",
        "reflect.child": "Følgende er særligt vigtigt for mig",
        "q.how_feel": "Hvordan har du det med dette? Der er ingen rigtige eller forkerte svar.",
        "q.include12": "Medtag spørgsmål for 12 år og opefter",
        "q.almost_done": "Næsten færdig",
        "q.write_here": "Skriv det ned her…",
        "q.save_footer": "Når du gemmer, vises dit personlige overblik i spindelvævet. Husk: dette er ikke en test, og der findes ingen norm — det er dit eget billede af dette øjeblik og et udgangspunkt for en samtale.",
        "q.show_web": "Vis mit spindelvæv",
        "r.compare": "Sammenlign med tidligere",
        "r.no_norm_footer": "Der findes ingen norm og ingen score, du skal nå. Dette er dit eget billede af dette øjeblik.",
        "r.my_dimensions": "Mine dimensioner",
        "r.other_conversation": "Den anden samtale",
        "r.other_footer": "Det er ligegyldigt, hvor du begynder — det vigtige er, at du begynder, og at du tager små skridt. Når ét punkt flytter sig, flytter andre punkter sig også.",
        "r.your_answer": "Dit svar…",
        "conv.attention": "Er der noget, du gerne vil give mere opmærksomhed, eller som du gerne vil ændre?",
        "conv.step": "Hvilket lille skridt kunne du selv tage?",
        "conv.support": "Hvem eller hvad kunne støtte dig med dette?",
        "settings.title": "Indstillinger",
        "settings.language": "Sprog",
        "settings.language_footer": "Engelsk bruger den officielle formulering fra Positive Health-værktøjerne. De øvrige sprog er uofficielle oversættelser lavet til denne app.",
        "about.title": "Om Positive Health",
        "about.s.whatisit": "Hvad er Positive Health?",
        "about.s.origin": "Hvor kommer det fra?",
        "about.s.dimensions": "De seks dimensioner",
        "about.s.spiderweb": "Spindelvævet",
        "about.s.conversation": "Den anden samtale",
        "about.s.steps": "Sådan virker det — tre trin",
        "about.s.who": "Hvem er det til?",
        "about.s.movement": "En bevægelse, ikke bare et værktøj",
        "about.s.value": "Værdien, det stræber efter",
        "about.s.resources": "Flere ressourcer",
        "about.s.versions": "Versioner i denne app",
        "about.s.learnmore": "Læs mere",
        "about.whatisit": "Positive Health er et bredt syn på sundhed, som blev udviklet i Holland. I stedet for at definere sundhed som fravær af sygdom ser det på mennesker som hele personer: på deres modstandskraft — evnen til at håndtere livets fysiske, følelsesmæssige og sociale udfordringer — og på det, der gør deres liv meningsfuldt. Det centrale spørgsmål skifter fra “Hvad er der galt med dig?” til “Hvad betyder noget for dig?”\n\nDet er ikke en behandling eller en test. Det er en måde at se på, et refleksionsværktøj og en samtalestarter, der hjælper dig med at forblive herre over dit eget liv, hvor det er muligt.",
        "about.quote": "Jeg er overbevist om, at af alle de kræfter, der fremmer sundhed, er meningsfuldhed den stærkeste.",
        "about.quote_author": "Machteld Huber, grundlægger af Positive Health",
        "about.origin": "Positive Health blev sat i gang af Machteld Huber, en tidligere hollandsk praktiserende læge og forsker. Efter selv at være blevet alvorligt syg lagde hun mærke til, hvor meget hendes egen indstilling og retningsfornemmelse påvirkede hendes bedring — noget, som det gældende syn på sundhed ikke havde plads til.\n\nVerdenssundhedsorganisationens definition fra 1948 beskriver sundhed som en tilstand af fuldstændigt fysisk, mentalt og socialt velbefindende. Huber og hendes kolleger argumenterede i British Medical Journal (2011) for, at dette ideal om “fuldstændigt velbefindende” er statisk og uopnåeligt — efter den målestok er næsten ingen sund, mindst af alt mennesker, der lever med en kronisk lidelse. De foreslog et dynamisk alternativ: sundhed som evnen til at tilpasse sig og til selv at klare livets udfordringer.\n\nFor at finde ud af, hvad sundhed betyder for folk selv, interviewede Hubers team derefter patienter, sundhedsprofessionelle og forskere. De hundredvis af sundhedsindikatorer, der kom ud af denne undersøgelse, blev grupperet i seks hoveddimensioner — spindelvævets seks akser. Forskningen bygger også på ældre indsigter: Aaron Antonovskys salutogenese (studiet af, hvad der skaber sundhed, snarere end hvad der forårsager sygdom) og Blue Zones, områder hvor mennesker bliver gamle med bemærkelsesværdigt godt helbred.",
        "about.spiderweb": "Du udfylder selv spørgeskemaet og giver hvert aspekt en score fra 0 til 10. Dine svar tegnes som din personlige sundhedsflade i spindelvævet. Der findes ingen norm og intet at bestå eller dumpe: vævet viser, hvordan du oplever dit helbred i dette øjeblik, i alle seks dimensioner — et billede, der er langt rigere end et enkelt tal.\n\nAt udfylde det er ofte en øjenåbner i sig selv: sundhed viser sig at være ikke kun din krop og dit humør, men også mening, deltagelse, livskvalitet og måden, du klarer dine dage på.",
        "about.conversation": "Spindelvævet er udgangspunktet for det, Positive Health kalder “den anden samtale” — med en læge, sygeplejerske, coach, socialrådgiver eller en, du stoler på. Samtalen udvider sig først (ser på hele vævet, ikke kun én klage) og indsnævrer sig så til det, der virkelig betyder noget for dig. Det handler ikke om de laveste scorer; du vælger, hvad du vil give opmærksomhed.\n\nSådanne samtaler tager jævnligt overraskende vendinger: det, man først kom med, viser sig ikke at være det, man mest ønsker at arbejde med. Folk ved som regel allerede, hvad der er brug for — vævet hjælper med at sige det højt.\n\nHerfra er tilgangen bevidst lille: vælg ét lille skridt, du selv kan tage, og tænk over, hvem eller hvad der kunne støtte dig. Når ét punkt i vævet flytter sig, har andre punkter en tendens til også at flytte sig.",
        "about.step1.title": "Udfyld spindelvævet",
        "about.step1.text": "Giv en score for, hvordan du har det med hvert aspekt, fra 0 til 10. Det tager kun et par minutter. Der findes ingen norm — det er en personlig vurdering af dette øjeblik.",
        "about.step2.title": "Hav den anden samtale",
        "about.step2.text": "Brug dit spindelvæv som en samtalestarter — med en læge, sygeplejerske, socialrådgiver, coach eller en ven. Ikke om, hvor scorerne er lave, men om hvor du gerne vil hen, og hvad der er vigtigt for dig.",
        "about.step3.title": "Tag et lille skridt",
        "about.step3.text": "Vælg ét lille skridt, du selv kan tage, og tænk over, hvem eller hvad der kunne støtte dig. Når ét punkt i vævet flytter sig, flytter andre punkter sig også.",
        "about.who": "Dialogværktøjerne findes i tre versioner — til voksne, til unge og unge voksne, og til børn — så alle fra omkring 8 år kan udfylde deres eget væv. De officielle værktøjer er udgivet på mere end ti sprog, og en onlineversion er tilgængelig på mypositivehealth.com.\n\nPositive Health begyndte i Holland og bruges nu internationalt, fra almen praksis og hospitaler til skoler, arbejdspladser og hele regioner. Det anvendes på fire niveauer: af enkeltpersoner for dem selv, af fagfolk i deres daglige arbejde, af fællesskaber og i sundhedssystemet som helhed — som en drivkraft for forandring fra sygdomsorienteret til sundhedsorienteret omsorg.",
        "about.movement": "Positive Health er ikke kun et værktøj, men en bevægelse — en anden måde at tænke, handle, organisere og finansiere omsorg på. Det starter som regel med nogle få engagerede mennesker og lokale partnere, der deler en vision, og vokser til bredere koalitioner. Måden, det føres ud i livet på, er forskellig fra land til land og fra kultur til kultur, men kernevisionen forbliver den samme. Det har slået rod på tværs af mange områder i Holland i løbet af det seneste årti og spreder sig nu internationalt.\n\nI kernen ligger et skift væk fra “reparationsrefleksen” — den automatiske trang til at fikse en klage — hen imod at give mennesker mulighed for at erkende, hvad de selv kan gøre for at leve et formålsfyldt og meningsfuldt liv.",
        "about.value": "Inden for omsorg sigter Positive Health mod det, der er kendt som “Quadruple Aim”:\n\n• At forbedre befolkningens sundhed\n• At forbedre folks oplevelse af omsorg\n• At reducere omkostninger\n• At forbedre trivslen hos omsorgsteams og fagfolk\n\nTilsammen beskriver de en bevægelse fra sygdomsorienteret omsorg til sundhedsorienteret omsorg — omsorg, der tager udgangspunkt i, hvad der betyder noget for en person, ikke kun i hvad der er galt.",
        "about.resources": "Ud over spindelvævet tilbyder Positive Health International og instituttet for Positive Health (iPH) flere måder at gå i dybden på:\n\n• Det online spindelvæv på mypositivehealth.com, til at udfylde det digitalt.\n• Et e-læringsmodul, “The Essence of Positive Health”, som en introduktion.\n• En håndbog med omfattende vejledning.\n• Gratis downloads og materialer til borgere og fagfolk.\n\nDenne app er en uafhængig personlig ledsager, der lader dig udfylde spindelvævet på din enhed; ressourcerne ovenfor er kilden og stedet, hvor du kan lære mere.",
        "about.link.phi": "Positive Health International — dialogværktøjer",
        "about.link.iph": "Institute for Positive Health (iPH)",
        "about.link.online": "My Positive Health — officielt online spindelvæv",
        "about.source": "Indholdet i dialogværktøjet i denne app (dimensioner, aspekter og samtalespørgsmål) er © iPH/PHi. Den engelske formulering er gengivet fra de officielle engelske værktøjer fra Positive Health International i samarbejde med instituttet for Positive Health (iPH). Oversættelser til andre sprog er uofficielle og er lavet til denne app. De forklarende tekster sammenfatter de to organisationers offentlige information.\n\nDenne app er en ledsager til personlig brug. Den er ikke en medicinsk enhed og giver ikke diagnoser eller lægelige råd. Dine svar gemmes kun på denne enhed.",
        "dimexpl.body": "Hvordan din krop føles og fungerer — at føle dig sund og i form, sove, spise, bevæge dig og være fri for gener eller smerter.",
        "dimexpl.mind": "Dit indre liv — at huske og koncentrere dig, håndtere dine følelser, acceptere dig selv og føle dig i kontrol.",
        "dimexpl.meaning": "Mening og retning — et meningsfuldt liv, livsglæde, idealer og drømme, tillid, accept og taknemmelighed.",
        "dimexpl.quality": "Hvordan du oplever dit liv — glæde, lykke, balance, tryghed og forhold som bolig og penge.",
        "dimexpl.participation": "Din forbindelse med andre — sociale kontakter, at blive taget alvorligt, tilhørsforhold, støtte og at gøre meningsfulde ting sammen.",
        "dimexpl.daily": "At klare hverdagen — at tage vare på dig selv, arbejde eller studier, kende dine grænser og kunne bede om hjælp.",
        "adult.body": "Kropslige funktioner",
        "adult.mind": "Mental trivsel",
        "adult.meaning": "Meningsfuldhed",
        "adult.quality": "Livskvalitet",
        "adult.participation": "Deltagelse",
        "adult.daily": "Daglig funktion",
        "adolescent.body": "Min krop",
        "adolescent.mind": "Mine følelser og tanker",
        "adolescent.meaning": "Meningsfuldhed",
        "adolescent.quality": "Livskvalitet",
        "adolescent.participation": "Deltagelse",
        "adolescent.daily": "Hverdagsliv",
        "child.body": "Min krop",
        "child.mind": "Mine følelser og tanker",
        "child.meaning": "Nu og i fremtiden",
        "child.quality": "At have det godt med dig selv",
        "child.participation": "Deltagelse",
        "child.daily": "Hverdagsliv",
        "adult.body.1": "At føle dig sund",
        "adult.body.2": "At føle dig i form",
        "adult.body.3": "Ingen fysiske gener eller smerter",
        "adult.body.4": "At sove",
        "adult.body.5": "At spise",
        "adult.body.6": "Seksualitet",
        "adult.body.7": "Fysisk form",
        "adult.body.8": "Fysisk aktivitet",
        "adult.mind.1": "At kunne huske ting",
        "adult.mind.2": "At kunne koncentrere dig",
        "adult.mind.3": "At kunne kommunikere",
        "adult.mind.4": "At være i godt humør",
        "adult.mind.5": "At acceptere dig selv",
        "adult.mind.6": "At kunne håndtere forandring",
        "adult.mind.7": "At føle dig i kontrol",
        "adult.meaning.1": "At have et meningsfuldt liv",
        "adult.meaning.2": "At have livsglæde",
        "adult.meaning.3": "At forfølge idealer",
        "adult.meaning.4": "At føle dig tryg og selvsikker",
        "adult.meaning.5": "At acceptere livet",
        "adult.meaning.6": "At være taknemmelig",
        "adult.meaning.7": "Livslang læring",
        "adult.quality.1": "Nydelse",
        "adult.quality.2": "At være lykkelig",
        "adult.quality.3": "At have det godt",
        "adult.quality.4": "At føle dig i balance",
        "adult.quality.5": "At føle dig tryg",
        "adult.quality.6": "Intimitet",
        "adult.quality.7": "Boligforhold",
        "adult.quality.8": "At have penge nok",
        "adult.participation.1": "Sociale kontakter",
        "adult.participation.2": "At blive taget alvorligt",
        "adult.participation.3": "At lave sjove ting sammen",
        "adult.participation.4": "At have støtte fra andre",
        "adult.participation.5": "Følelse af tilhørsforhold",
        "adult.participation.6": "At gøre meningsfulde ting",
        "adult.participation.7": "At være interesseret i samfundet",
        "adult.daily.1": "At tage vare på dig selv",
        "adult.daily.2": "At kende dine begrænsninger",
        "adult.daily.3": "Viden om sundhed",
        "adult.daily.4": "At håndtere tid",
        "adult.daily.5": "At håndtere penge",
        "adult.daily.6": "At kunne arbejde",
        "adult.daily.7": "At kunne bede om hjælp",
        "adolescent.body.1": "At føle dig sund",
        "adolescent.body.2": "At have energi",
        "adolescent.body.3": "Ingen fysiske gener eller smerter",
        "adolescent.body.4": "At spise sundt",
        "adolescent.body.5": "At sove",
        "adolescent.body.6": "Kondition",
        "adolescent.body.7": "Sport og motion",
        "adolescent.body.8": "Fysisk udseende",
        "adolescent.mind.1": "Koncentration",
        "adolescent.mind.2": "At håndtere dine følelser",
        "adolescent.mind.3": "At have et positivt syn på livet",
        "adolescent.mind.4": "At acceptere dig selv",
        "adolescent.mind.5": "Tro på dig selv",
        "adolescent.mind.6": "At håndtere forandring",
        "adolescent.mind.7": "At være i kontrol",
        "adolescent.meaning.1": "At leve et meningsfuldt liv",
        "adolescent.meaning.2": "At have tro på fremtiden",
        "adolescent.meaning.3": "At have livsglæde",
        "adolescent.meaning.4": "At have mål og drømme",
        "adolescent.meaning.5": "At træffe valg",
        "adolescent.meaning.6": "At acceptere situationer",
        "adolescent.meaning.7": "Taknemmelighed",
        "adolescent.quality.1": "Lykke",
        "adolescent.quality.2": "Nydelse",
        "adolescent.quality.3": "At opleve balance",
        "adolescent.quality.4": "At føle dig tryg",
        "adolescent.quality.5": "Et rart miljø",
        "adolescent.quality.6": "Bolig og nærmiljø",
        "adolescent.quality.7": "At få pengene til at slå til",
        "adolescent.participation.1": "Sociale kontakter",
        "adolescent.participation.2": "At blive taget alvorligt",
        "adolescent.participation.3": "At lave sjove ting med andre",
        "adolescent.participation.4": "Tilhørsforhold",
        "adolescent.participation.5": "Selvudfoldelse",
        "adolescent.participation.6": "Meningsfulde relationer",
        "adolescent.participation.7": "At få støtte og forståelse fra andre",
        "adolescent.daily.1": "At tage vare på dig selv",
        "adolescent.daily.2": "At kunne arbejde eller studere",
        "adolescent.daily.3": "At kende dine begrænsninger",
        "adolescent.daily.4": "Viden om sundhed",
        "adolescent.daily.5": "At kunne planlægge",
        "adolescent.daily.6": "At kunne bede om hjælp",
        "adolescent.daily.7": "Ingen rygning, alkohol eller stoffer",
        "child.body.1": "At have det godt",
        "child.body.2": "At have energi",
        "child.body.3": "At spise sundt",
        "child.body.4": "At sove godt",
        "child.body.5": "Sport og motion",
        "child.body.6": "Ingen fysiske gener",
        "child.body.7": "Ingen smerter",
        "child.body.8": "Fysisk udseende",
        "child.mind.1": "At håndtere dine følelser",
        "child.mind.2": "At acceptere dig selv",
        "child.mind.3": "At passe ind",
        "child.mind.4": "At have et positivt syn på livet",
        "child.mind.5": "At kende dine begrænsninger",
        "child.mind.6": "At klare modgang",
        "child.meaning.1": "At se på fremtiden",
        "child.meaning.2": "Kultur og religion",
        "child.meaning.3": "At have mål og drømme",
        "child.meaning.4": "At træffe valg",
        "child.meaning.5": "Selvindsigt",
        "child.meaning.6": "Forbilleder",
        "child.quality.1": "Nydelse",
        "child.quality.2": "Lykke",
        "child.quality.3": "Glæde",
        "child.quality.4": "Et rart miljø",
        "child.quality.5": "At have det sjovt med at lave ting",
        "child.quality.6": "At få støtte og forståelse fra andre",
        "child.participation.1": "Venner",
        "child.participation.2": "Tilhørsforhold",
        "child.participation.3": "Mobning",
        "child.participation.4": "Selvbestemmelse",
        "child.participation.5": "At følge med de andre",
        "child.participation.6": "Personligt bidrag",
        "child.daily.1": "At gå i skole",
        "child.daily.2": "At være dig selv",
        "child.daily.3": "Fritid",
        "child.daily.4": "At tage vare på dig selv",
        "child.daily.5": "At føle dig normal",
        "child.daily.6": "Begrænsninger",
        "child.daily.7": "Ingen brug af rygning, alkohol eller stoffer",
    ]
}
