import Foundation

// Unofficial translation generated for this app — NOT the official Positive Health wording.
enum Dutch {
    static let table: [String: String] = [
        "done": "Klaar",
        "cancel": "Annuleren",
        "back": "Terug",
        "next": "Volgende",
        "app_title": "Mijn Positieve Gezondheid",
        "fill_menu": "Vul het spinnenweb in",
        "empty_title": "Vul je spinnenweb in",
        "empty_desc": "Positieve Gezondheid kijkt naar wat voor jou belangrijk is, verdeeld over zes dimensies van gezondheid. Vul het spinnenweb in om je persoonlijke overzicht te krijgen — een startpunt voor een ander gesprek.",
        "version.adult.title": "Volwassenen",
        "version.adolescent.title": "Jongeren / jongvolwassenen",
        "version.child.title": "Kinderen",
        "version.adult.age": "18+ jaar",
        "version.adolescent.age": "16–25 jaar",
        "version.child.age": "8–16 jaar",
        "reflect.adult": "Er ontbreekt iets dat voor mij belangrijk is:",
        "reflect.adolescent": "Het volgende is voor mij extra belangrijk",
        "reflect.child": "Het volgende is voor mij extra belangrijk",
        "q.how_feel": "Hoe voel je je hierover? Er zijn geen goede of foute antwoorden.",
        "q.include12": "Vragen voor 12 jaar en ouder meenemen",
        "q.almost_done": "Bijna klaar",
        "q.write_here": "Schrijf het hier op…",
        "q.save_footer": "Als je opslaat, verschijnt je persoonlijke overzicht in het spinnenweb. Onthoud: dit is geen test en er is geen norm — het is jouw eigen beeld van dit moment, en een startpunt voor een gesprek.",
        "q.show_web": "Toon mijn spinnenweb",
        "r.compare": "Vergelijk met eerder",
        "r.no_norm_footer": "Er is geen norm en geen score die je moet halen. Dit is jouw eigen beeld van dit moment.",
        "r.my_dimensions": "Mijn dimensies",
        "r.other_conversation": "Het andere gesprek",
        "r.other_footer": "Het maakt niet uit waar je begint — wat telt is dat je begint, en dat je kleine stappen zet. Als één punt beweegt, bewegen andere punten mee.",
        "r.your_answer": "Jouw antwoord…",
        "conv.attention": "Is er iets waar je meer aandacht aan zou willen geven, of dat je zou willen veranderen?",
        "conv.step": "Welke kleine stap zou je zelf kunnen zetten?",
        "conv.support": "Wie of wat zou je hierbij kunnen steunen?",
        "settings.title": "Instellingen",
        "settings.language": "Taal",
        "settings.language_footer": "Het Engels gebruikt de officiële formuleringen van de Positieve Gezondheid-instrumenten. De andere talen zijn onofficiële vertalingen die voor deze app zijn gemaakt.",
        "about.title": "Over Positieve Gezondheid",
        "about.s.whatisit": "Wat is Positieve Gezondheid?",
        "about.s.origin": "Waar komt het vandaan?",
        "about.s.dimensions": "De zes dimensies",
        "about.s.spiderweb": "Het spinnenweb",
        "about.s.conversation": "Het andere gesprek",
        "about.s.steps": "Hoe het werkt — drie stappen",
        "about.s.who": "Voor wie is het?",
        "about.s.movement": "Een beweging, niet alleen een instrument",
        "about.s.value": "De waarde die het nastreeft",
        "about.s.resources": "Meer bronnen",
        "about.s.versions": "Versies in deze app",
        "about.s.learnmore": "Meer weten",
        "about.whatisit": "Positieve Gezondheid is een brede kijk op gezondheid die in Nederland is ontwikkeld. In plaats van gezondheid te zien als de afwezigheid van ziekte, kijkt het naar mensen als geheel: naar hun veerkracht — het vermogen om met de fysieke, emotionele en sociale uitdagingen van het leven om te gaan — en naar wat hun leven betekenisvol maakt. De centrale vraag verschuift van “Wat heb je?” naar “Wat is voor jou belangrijk?”\n\nHet is geen behandeling of test. Het is een manier van kijken, een reflectie-instrument en een gespreksopener die je helpt om waar mogelijk zelf de regie over je leven te houden.",
        "about.quote": "Ik ben ervan overtuigd dat van alle krachten die de gezondheid versterken, betekenisgeving de sterkste is.",
        "about.quote_author": "Machteld Huber, grondlegger van Positieve Gezondheid",
        "about.origin": "Positieve Gezondheid is geïnitieerd door Machteld Huber, een voormalig Nederlands huisarts en onderzoeker. Nadat ze zelf ernstig ziek was geworden, merkte ze hoezeer haar eigen houding en gevoel van richting haar herstel beïnvloedden — iets waar de heersende kijk op gezondheid geen ruimte voor had.\n\nDe definitie van de Wereldgezondheidsorganisatie uit 1948 beschrijft gezondheid als een toestand van volledig fysiek, mentaal en sociaal welbevinden. Huber en haar collega's betoogden in het British Medical Journal (2011) dat dit ideaal van “volledig welbevinden” statisch en onhaalbaar is — volgens die maatstaf is bijna niemand gezond, en mensen met een chronische aandoening al helemaal niet. Ze stelden een dynamisch alternatief voor: gezondheid als het vermogen om je aan te passen en eigen regie te voeren bij de uitdagingen van het leven.\n\nOm te ontdekken wat gezondheid voor mensen zelf betekent, interviewde Hubers team vervolgens patiënten, zorgprofessionals en onderzoekers. De honderden gezondheidsindicatoren die uit dit onderzoek naar voren kwamen, werden gegroepeerd in zes hoofddimensies — de zes assen van het spinnenweb. Het onderzoek bouwt ook voort op oudere inzichten: de salutogenese van Aaron Antonovsky (het bestuderen van wat gezondheid schept in plaats van wat ziekte veroorzaakt) en de Blue Zones, gebieden waar mensen opvallend gezond oud worden.",
        "about.spiderweb": "Je vult de vragenlijst zelf in en geeft elk aspect een score van 0 tot 10. Je antwoorden worden getekend als jouw persoonlijke gezondheidsoppervlak in het spinnenweb. Er is geen norm en niets om te halen of te falen: het web laat zien hoe je je gezondheid op dit moment ervaart, in alle zes dimensies — een beeld dat veel rijker is dan één enkel cijfer.\n\nHet invullen is vaak op zichzelf al een eyeopener: gezondheid blijkt niet alleen je lichaam en je stemming te zijn, maar ook betekenis, meedoen, kwaliteit van leven en hoe je je dagen indeelt.",
        "about.conversation": "Het spinnenweb is het startpunt voor wat Positieve Gezondheid “het andere gesprek” noemt — met een arts, verpleegkundige, coach, maatschappelijk werker of iemand die je vertrouwt. Het gesprek verbreedt eerst (kijken naar het hele web, niet alleen naar één klacht) en versmalt daarna naar wat er voor jou echt toe doet. Het gaat niet om de laagste scores; jij kiest waar je aandacht aan wilt geven.\n\nZulke gesprekken nemen regelmatig verrassende wendingen: waar iemand in eerste instantie mee binnenkwam, blijkt niet het onderwerp te zijn waar diegene het liefst aan wil werken. Mensen weten meestal al wat er nodig is — het web helpt om het hardop te zeggen.\n\nVan daaruit is de aanpak bewust klein: kies één kleine stap die je zelf kunt zetten, en denk na over wie of wat je daarbij kan steunen. Als één punt van het web beweegt, bewegen andere punten meestal mee.",
        "about.step1.title": "Vul het spinnenweb in",
        "about.step1.text": "Geef aan hoe je je bij elk aspect voelt, van 0 tot 10. Het kost maar een paar minuten. Er is geen norm — het is een persoonlijke beoordeling van dit moment.",
        "about.step2.title": "Voer het andere gesprek",
        "about.step2.text": "Gebruik je spinnenweb als gespreksopener — met een arts, verpleegkundige, maatschappelijk werker, coach of een vriend. Niet over waar de scores laag zijn, maar over waar je heen wilt en wat voor jou belangrijk is.",
        "about.step3.title": "Zet een kleine stap",
        "about.step3.text": "Kies één kleine stap die je zelf kunt zetten, en denk na over wie of wat je daarbij kan steunen. Als één punt van het web beweegt, bewegen andere punten mee.",
        "about.who": "De gespreksinstrumenten bestaan in drie versies — voor volwassenen, voor jongeren en jongvolwassenen, en voor kinderen — zodat iedereen vanaf ongeveer 8 jaar zijn eigen web kan invullen. De officiële instrumenten zijn in meer dan tien talen gepubliceerd, en een onlineversie is beschikbaar op mypositivehealth.com.\n\nPositieve Gezondheid begon in Nederland en wordt inmiddels internationaal gebruikt, van huisartsenpraktijken en ziekenhuizen tot scholen, werkplekken en hele regio's. Het wordt op vier niveaus toegepast: door mensen voor zichzelf, door professionals in hun dagelijks werk, door gemeenschappen, en in het zorgstelsel als geheel — als aanjager van de omslag van ziektegerichte naar gezondheidsgerichte zorg.",
        "about.movement": "Positieve Gezondheid is niet alleen een instrument maar een beweging — een andere manier van denken, doen, organiseren en financieren van zorg. Het begint meestal met een paar betrokken mensen en lokale partners die een visie delen, en groeit uit tot bredere coalities. De manier waarop het wordt ingevoerd verschilt per land en cultuur, maar de kernvisie blijft hetzelfde. Het heeft de afgelopen tien jaar in Nederland in veel domeinen wortel geschoten en verspreidt zich nu internationaal.\n\nDe kern is een verschuiving weg van “de reparatiereflex” — de automatische drang om een klacht op te lossen — naar het versterken van mensen om te herkennen wat ze zelf kunnen doen om een zinvol, betekenisvol leven te leiden.",
        "about.value": "In de zorg richt Positieve Gezondheid zich op wat bekendstaat als de “Quadruple Aim”:\n\n• De gezondheid van de bevolking verbeteren\n• De ervaring van mensen met zorg verbeteren\n• De kosten verlagen\n• Het welzijn van zorgteams en professionals verbeteren\n\nSamen beschrijven ze een beweging van ziektegerichte zorg naar gezondheidsgerichte zorg — zorg die uitgaat van wat voor iemand belangrijk is, en niet alleen van wat er mis is.",
        "about.resources": "Naast het spinnenweb bieden Positive Health International en het instituut voor Positieve Gezondheid (iPH) meer manieren om de verdieping in te gaan:\n\n• Het online spinnenweb op mypositivehealth.com, om het digitaal in te vullen.\n• Een e-learningmodule, “The Essence of Positive Health”, als introductie.\n• Een handboek met uitgebreide handreikingen.\n• Gratis downloads en materialen voor mensen en professionals.\n\nDeze app is een onafhankelijke persoonlijke metgezel waarmee je het spinnenweb op je apparaat kunt invullen; de bovenstaande bronnen zijn de oorsprong en de plek om meer te leren.",
        "about.link.phi": "Positive Health International — gespreksinstrumenten",
        "about.link.iph": "Instituut voor Positieve Gezondheid (iPH)",
        "about.link.online": "Mijn Positieve Gezondheid — officieel online spinnenweb",
        "about.source": "De inhoud van het gespreksinstrument in deze app (dimensies, aspecten en gespreksvragen) is © iPH/PHi. De Engelse tekst is overgenomen uit de officiële Engelse instrumenten van Positive Health International in samenwerking met het instituut voor Positieve Gezondheid (iPH). Vertalingen in andere talen zijn onofficieel en zijn voor deze app gemaakt. De uitlegteksten vatten de openbare informatie van beide organisaties samen.\n\nDeze app is een metgezel voor persoonlijk gebruik. Het is geen medisch hulpmiddel en geeft geen diagnoses of medisch advies. Je antwoorden worden alleen op dit apparaat opgeslagen.",
        "dimexpl.body": "Hoe je lichaam aanvoelt en functioneert — je gezond en fit voelen, slapen, eten, bewegen, en vrij zijn van klachten of pijn.",
        "dimexpl.mind": "Je innerlijke leven — onthouden en concentreren, omgaan met je gevoelens, jezelf accepteren en je in controle voelen.",
        "dimexpl.meaning": "Zin en richting — een betekenisvol leven, levenslust, idealen en dromen, vertrouwen, acceptatie en dankbaarheid.",
        "dimexpl.quality": "Hoe je je leven ervaart — plezier, geluk, balans, veiligheid, en omstandigheden zoals wonen en geld.",
        "dimexpl.participation": "Je verbondenheid met anderen — sociale contacten, serieus genomen worden, erbij horen, steun, en samen betekenisvolle dingen doen.",
        "dimexpl.daily": "Het dagelijks leven aankunnen — voor jezelf zorgen, werk of studie, je grenzen kennen, en om hulp kunnen vragen.",
        "adult.body": "Lichaamsfuncties",
        "adult.mind": "Mentaal welbevinden",
        "adult.meaning": "Zingeving",
        "adult.quality": "Kwaliteit van leven",
        "adult.participation": "Meedoen",
        "adult.daily": "Dagelijks functioneren",
        "adolescent.body": "Mijn lichaam",
        "adolescent.mind": "Mijn gevoelens en gedachten",
        "adolescent.meaning": "Zingeving",
        "adolescent.quality": "Kwaliteit van leven",
        "adolescent.participation": "Meedoen",
        "adolescent.daily": "Dagelijks leven",
        "child.body": "Mijn lichaam",
        "child.mind": "Mijn gevoelens en gedachten",
        "child.meaning": "Nu en later",
        "child.quality": "Je goed voelen over jezelf",
        "child.participation": "Meedoen",
        "child.daily": "Dagelijks leven",
        "adult.body.1": "Je gezond voelen",
        "adult.body.2": "Je fit voelen",
        "adult.body.3": "Geen lichamelijke klachten of pijn",
        "adult.body.4": "Slapen",
        "adult.body.5": "Eten",
        "adult.body.6": "Seksualiteit",
        "adult.body.7": "Conditie",
        "adult.body.8": "Bewegen",
        "adult.mind.1": "Dingen kunnen onthouden",
        "adult.mind.2": "Je kunnen concentreren",
        "adult.mind.3": "Kunnen communiceren",
        "adult.mind.4": "Vrolijk zijn",
        "adult.mind.5": "Jezelf accepteren",
        "adult.mind.6": "Met verandering kunnen omgaan",
        "adult.mind.7": "Je in controle voelen",
        "adult.meaning.1": "Een betekenisvol leven hebben",
        "adult.meaning.2": "Levenslust hebben",
        "adult.meaning.3": "Idealen nastreven",
        "adult.meaning.4": "Je zeker voelen",
        "adult.meaning.5": "Het leven accepteren",
        "adult.meaning.6": "Dankbaar zijn",
        "adult.meaning.7": "Een leven lang leren",
        "adult.quality.1": "Plezier",
        "adult.quality.2": "Gelukkig zijn",
        "adult.quality.3": "Je goed voelen",
        "adult.quality.4": "Je in balans voelen",
        "adult.quality.5": "Je veilig voelen",
        "adult.quality.6": "Intimiteit",
        "adult.quality.7": "Woonomstandigheden",
        "adult.quality.8": "Genoeg geld hebben",
        "adult.participation.1": "Sociale contacten",
        "adult.participation.2": "Serieus genomen worden",
        "adult.participation.3": "Samen leuke dingen doen",
        "adult.participation.4": "Steun van anderen hebben",
        "adult.participation.5": "Erbij horen",
        "adult.participation.6": "Betekenisvolle dingen doen",
        "adult.participation.7": "Betrokken zijn bij de samenleving",
        "adult.daily.1": "Voor jezelf zorgen",
        "adult.daily.2": "Je grenzen kennen",
        "adult.daily.3": "Kennis over gezondheid",
        "adult.daily.4": "Je tijd indelen",
        "adult.daily.5": "Met geld omgaan",
        "adult.daily.6": "Kunnen werken",
        "adult.daily.7": "Om hulp kunnen vragen",
        "adolescent.body.1": "Je gezond voelen",
        "adolescent.body.2": "Energie hebben",
        "adolescent.body.3": "Geen lichamelijke klachten of pijn",
        "adolescent.body.4": "Gezond eten",
        "adolescent.body.5": "Slapen",
        "adolescent.body.6": "Fitheid",
        "adolescent.body.7": "Sport & beweging",
        "adolescent.body.8": "Je uiterlijk",
        "adolescent.mind.1": "Concentratie",
        "adolescent.mind.2": "Omgaan met je gevoelens",
        "adolescent.mind.3": "Positief in het leven staan",
        "adolescent.mind.4": "Jezelf accepteren",
        "adolescent.mind.5": "Vertrouwen in jezelf",
        "adolescent.mind.6": "Omgaan met verandering",
        "adolescent.mind.7": "De regie hebben",
        "adolescent.meaning.1": "Een betekenisvol leven leiden",
        "adolescent.meaning.2": "Vertrouwen in de toekomst hebben",
        "adolescent.meaning.3": "Levenslust hebben",
        "adolescent.meaning.4": "Doelen en dromen hebben",
        "adolescent.meaning.5": "Keuzes maken",
        "adolescent.meaning.6": "Situaties accepteren",
        "adolescent.meaning.7": "Dankbaarheid",
        "adolescent.quality.1": "Geluk",
        "adolescent.quality.2": "Plezier",
        "adolescent.quality.3": "Balans ervaren",
        "adolescent.quality.4": "Je veilig voelen",
        "adolescent.quality.5": "Een prettige omgeving",
        "adolescent.quality.6": "Woon- en leefomgeving",
        "adolescent.quality.7": "Rondkomen",
        "adolescent.participation.1": "Sociale contacten",
        "adolescent.participation.2": "Serieus genomen worden",
        "adolescent.participation.3": "Leuke dingen doen met anderen",
        "adolescent.participation.4": "Erbij horen",
        "adolescent.participation.5": "Jezelf uiten",
        "adolescent.participation.6": "Betekenisvolle relaties",
        "adolescent.participation.7": "Steun en begrip van anderen krijgen",
        "adolescent.daily.1": "Voor jezelf zorgen",
        "adolescent.daily.2": "Kunnen werken of leren",
        "adolescent.daily.3": "Je grenzen kennen",
        "adolescent.daily.4": "Kennis over gezondheid",
        "adolescent.daily.5": "Kunnen plannen",
        "adolescent.daily.6": "Om hulp kunnen vragen",
        "adolescent.daily.7": "Geen roken, alcohol of drugs",
        "child.body.1": "Je goed voelen",
        "child.body.2": "Energie hebben",
        "child.body.3": "Gezond eten",
        "child.body.4": "Goed slapen",
        "child.body.5": "Sport & beweging",
        "child.body.6": "Geen lichamelijke klachten",
        "child.body.7": "Geen pijn",
        "child.body.8": "Je uiterlijk",
        "child.mind.1": "Omgaan met je gevoelens",
        "child.mind.2": "Jezelf accepteren",
        "child.mind.3": "Erbij horen",
        "child.mind.4": "Positief in het leven staan",
        "child.mind.5": "Je grenzen kennen",
        "child.mind.6": "Omgaan met tegenslag",
        "child.meaning.1": "Naar de toekomst kijken",
        "child.meaning.2": "Cultuur en geloof",
        "child.meaning.3": "Doelen en dromen hebben",
        "child.meaning.4": "Keuzes maken",
        "child.meaning.5": "Jezelf kennen",
        "child.meaning.6": "Voorbeelden om naar op te kijken",
        "child.quality.1": "Plezier",
        "child.quality.2": "Geluk",
        "child.quality.3": "Vrolijkheid",
        "child.quality.4": "Een prettige omgeving",
        "child.quality.5": "Plezier hebben in dingen doen",
        "child.quality.6": "Steun en begrip van anderen krijgen",
        "child.participation.1": "Vrienden",
        "child.participation.2": "Erbij horen",
        "child.participation.3": "Pesten",
        "child.participation.4": "Zelf beslissen",
        "child.participation.5": "Meekomen met anderen",
        "child.participation.6": "Je eigen bijdrage",
        "child.daily.1": "Naar school gaan",
        "child.daily.2": "Jezelf zijn",
        "child.daily.3": "Vrije tijd",
        "child.daily.4": "Voor jezelf zorgen",
        "child.daily.5": "Je normaal voelen",
        "child.daily.6": "Grenzen",
        "child.daily.7": "Geen roken, alcohol of drugsgebruik",
    ]
}
