import Foundation

// Unofficial translation generated for this app — NOT the official Positive Health wording.
enum French {
    static let table: [String: String] = [
        "done": "Terminé",
        "cancel": "Annuler",
        "back": "Retour",
        "next": "Suivant",
        "app_title": "Ma Santé Positive",
        "fill_menu": "Remplir la toile d'araignée",
        "empty_title": "Remplissez votre toile d'araignée",
        "empty_desc": "Positive Health s'intéresse à ce qui compte pour vous, à travers six dimensions de la santé. Remplissez la toile d'araignée pour obtenir votre aperçu personnel — un point de départ pour une autre conversation.",
        "version.adult.title": "Adultes",
        "version.adolescent.title": "Adolescents / jeunes adultes",
        "version.child.title": "Enfants",
        "version.adult.age": "18 ans et plus",
        "version.adolescent.age": "16–25 ans",
        "version.child.age": "8–16 ans",
        "reflect.adult": "Quelque chose qui est important pour moi manque :",
        "reflect.adolescent": "Ce qui suit est particulièrement important pour moi",
        "reflect.child": "Ce qui suit est particulièrement important pour moi",
        "q.how_feel": "Comment vous sentez-vous à ce sujet ? Il n'y a pas de bonnes ou de mauvaises réponses.",
        "q.include12": "Inclure les questions pour les 12 ans et plus",
        "q.almost_done": "Presque terminé",
        "q.write_here": "Notez-le ici…",
        "q.save_footer": "Lorsque vous enregistrez, votre aperçu personnel apparaît dans la toile d'araignée. N'oubliez pas : ceci n'est pas un test et il n'y a pas de norme — c'est votre propre image de cet instant, et un point de départ pour une conversation.",
        "q.show_web": "Afficher ma toile d'araignée",
        "r.compare": "Comparer avec la précédente",
        "r.no_norm_footer": "Il n'y a pas de norme ni de score à atteindre. C'est votre propre image de cet instant.",
        "r.my_dimensions": "Mes dimensions",
        "r.other_conversation": "L'autre conversation",
        "r.other_footer": "Peu importe par où vous commencez — ce qui compte, c'est que vous commenciez et que vous fassiez de petits pas. Quand un point bouge, d'autres points bougent aussi.",
        "r.your_answer": "Votre réponse…",
        "conv.attention": "Y a-t-il quelque chose auquel vous aimeriez accorder plus d'attention, ou que vous aimeriez changer ?",
        "conv.step": "Quel petit pas pourriez-vous faire vous-même ?",
        "conv.support": "Qui ou quoi pourrait vous soutenir dans cette démarche ?",
        "settings.title": "Réglages",
        "settings.language": "Langue",
        "settings.language_footer": "L'anglais utilise la formulation officielle des outils Positive Health. Les autres langues sont des traductions non officielles réalisées pour cette application.",
        "about.title": "À propos de Positive Health",
        "about.s.whatisit": "Qu'est-ce que Positive Health ?",
        "about.s.origin": "D'où cela vient-il ?",
        "about.s.dimensions": "Les six dimensions",
        "about.s.spiderweb": "La toile d'araignée",
        "about.s.conversation": "L'autre conversation",
        "about.s.steps": "Comment ça marche — trois étapes",
        "about.s.who": "À qui cela s'adresse-t-il ?",
        "about.s.movement": "Un mouvement, pas seulement un outil",
        "about.s.value": "La valeur qu'il vise",
        "about.s.resources": "Plus de ressources",
        "about.s.versions": "Versions dans cette application",
        "about.s.learnmore": "En savoir plus",
        "about.whatisit": "Positive Health est une vision large de la santé qui a été développée aux Pays-Bas. Au lieu de définir la santé comme l'absence de maladie, elle considère les personnes dans leur globalité : leur résilience — la capacité à faire face aux défis physiques, émotionnels et sociaux de la vie — et ce qui donne un sens à leur vie. La question centrale passe de « Qu'est-ce qui ne va pas chez vous ? » à « Qu'est-ce qui compte pour vous ? »\n\nCe n'est ni un traitement ni un test. C'est une manière de regarder, un outil de réflexion et un point de départ pour la conversation qui vous aide à rester maître de votre propre vie chaque fois que possible.",
        "about.quote": "Je suis convaincue que, de toutes les forces qui renforcent la santé, le sens de la vie est la plus puissante.",
        "about.quote_author": "Machteld Huber, fondatrice de Positive Health",
        "about.origin": "Positive Health a été initié par Machteld Huber, ancienne médecin généraliste et chercheuse néerlandaise. Après être tombée gravement malade elle-même, elle a remarqué à quel point sa propre attitude et son sens de la direction influençaient sa guérison — quelque chose auquel la vision dominante de la santé ne laissait aucune place.\n\nLa définition de la santé donnée par l'Organisation mondiale de la santé en 1948 la décrit comme un état de complet bien-être physique, mental et social. Huber et ses collègues ont soutenu dans le British Medical Journal (2011) que cet idéal de « complet bien-être » est statique et inatteignable — selon ce critère, presque personne n'est en bonne santé, et surtout pas les personnes vivant avec une maladie chronique. Ils ont proposé une alternative dynamique : la santé comme la capacité de s'adapter et de se prendre en charge face aux défis de la vie.\n\nPour découvrir ce que la santé signifie pour les gens eux-mêmes, l'équipe de Huber a ensuite interrogé des patients, des professionnels du soin et des chercheurs. Les centaines d'indicateurs de santé issus de cette étude ont été regroupés en six dimensions principales — les six axes de la toile d'araignée. La recherche s'appuie aussi sur des connaissances plus anciennes : la salutogenèse d'Aaron Antonovsky (l'étude de ce qui crée la santé plutôt que de ce qui cause la maladie) et les Blue Zones, ces régions où les gens vieillissent en restant remarquablement en bonne santé.",
        "about.spiderweb": "Vous remplissez vous-même le questionnaire, en attribuant à chaque aspect une note de 0 à 10. Vos réponses sont dessinées comme votre surface de santé personnelle dans la toile d'araignée. Il n'y a pas de norme et rien à réussir ou à échouer : la toile montre comment vous vivez votre santé en ce moment, dans les six dimensions — une image bien plus riche qu'un simple chiffre.\n\nLa remplir est souvent une révélation en soi : la santé ne se résume pas au corps et à l'humeur, mais englobe aussi le sens, la participation, la qualité de vie et la manière dont vous gérez vos journées.",
        "about.conversation": "La toile d'araignée est le point de départ de ce que Positive Health appelle « l'autre conversation » — avec un médecin, un infirmier, un coach, un travailleur social ou une personne de confiance. La conversation s'élargit d'abord (en regardant toute la toile, et non une seule plainte), puis se resserre vers ce qui compte vraiment pour vous. Il ne s'agit pas des scores les plus bas ; c'est vous qui choisissez ce à quoi vous voulez accorder de l'attention.\n\nDe telles conversations prennent régulièrement des tournures surprenantes : ce avec quoi quelqu'un est venu au départ n'est finalement pas ce sur quoi il souhaite le plus travailler. Les gens savent généralement déjà ce dont ils ont besoin — la toile aide à le dire à voix haute.\n\nÀ partir de là, l'approche est délibérément modeste : choisissez un petit pas que vous pouvez faire vous-même, et réfléchissez à qui ou à quoi pourrait vous soutenir. Quand un point de la toile bouge, les autres points ont tendance à bouger aussi.",
        "about.step1.title": "Remplir la toile d'araignée",
        "about.step1.text": "Évaluez comment vous vous sentez pour chaque aspect, de 0 à 10. Cela ne prend que quelques minutes. Il n'y a pas de norme — c'est une évaluation personnelle de cet instant.",
        "about.step2.title": "Avoir l'autre conversation",
        "about.step2.text": "Utilisez votre toile d'araignée comme point de départ à une conversation — avec un médecin, un infirmier, un travailleur social, un coach ou un ami. Non pas sur les endroits où les scores sont bas, mais sur là où vous voulez aller et ce qui est important pour vous.",
        "about.step3.title": "Faire un petit pas",
        "about.step3.text": "Choisissez un petit pas que vous pouvez faire vous-même, et réfléchissez à qui ou à quoi pourrait vous soutenir. Quand un point de la toile bouge, d'autres points bougent aussi.",
        "about.who": "Les outils de dialogue existent en trois versions — pour les adultes, pour les adolescents et jeunes adultes, et pour les enfants — afin que chacun, dès l'âge de 8 ans environ, puisse remplir sa propre toile. Les outils officiels sont publiés dans plus de dix langues, et une version en ligne est disponible sur mypositivehealth.com.\n\nPositive Health a commencé aux Pays-Bas et est aujourd'hui utilisé à l'international, des cabinets de médecins généralistes et des hôpitaux jusqu'aux écoles, aux lieux de travail et à des régions entières. Il s'applique à quatre niveaux : par les individus pour eux-mêmes, par les professionnels dans leur travail quotidien, par les communautés, et dans le système de santé dans son ensemble — comme moteur d'un changement d'une santé orientée vers la maladie vers une santé orientée vers le bien-être.",
        "about.movement": "Positive Health n'est pas seulement un outil, mais un mouvement — une autre manière de penser, d'agir, d'organiser et de financer les soins. Cela commence généralement par quelques personnes engagées et des partenaires locaux qui partagent une vision, puis se développe en coalitions plus larges. La manière dont il est mis en œuvre diffère selon les pays et les cultures, mais la vision de fond reste la même. Il a pris racine dans de nombreux domaines aux Pays-Bas au cours de la dernière décennie et se répand désormais à l'international.\n\nEn son cœur se trouve un éloignement du « réflexe de réparation » — l'envie automatique de régler une plainte — au profit de la capacité donnée aux gens de reconnaître ce qu'ils peuvent eux-mêmes faire pour mener une vie qui a du sens et de la valeur.",
        "about.value": "Dans les soins, Positive Health vise ce que l'on appelle le « Quadruple Aim » :\n\n• Améliorer la santé de la population\n• Améliorer l'expérience de soin des personnes\n• Réduire les coûts\n• Améliorer le bien-être des équipes et des professionnels de soin\n\nEnsemble, ces objectifs décrivent un passage de soins orientés vers la maladie à des soins orientés vers la santé — des soins qui partent de ce qui compte pour une personne, et non seulement de ce qui ne va pas.",
        "about.resources": "Au-delà de la toile d'araignée, Positive Health International et l'institut pour Positive Health (iPH) proposent d'autres moyens d'aller plus loin :\n\n• La toile d'araignée en ligne sur mypositivehealth.com, pour la remplir de manière numérique.\n• Un module d'e-learning, « The Essence of Positive Health », en guise d'introduction.\n• Un manuel offrant un accompagnement complet.\n• Des téléchargements et des ressources gratuits pour les particuliers et les professionnels.\n\nCette application est un compagnon personnel indépendant qui vous permet de remplir la toile d'araignée sur votre appareil ; les ressources ci-dessus en sont la source et l'endroit pour en apprendre davantage.",
        "about.link.phi": "Positive Health International — outils de dialogue",
        "about.link.iph": "Institute for Positive Health (iPH)",
        "about.link.online": "My Positive Health — toile d'araignée officielle en ligne",
        "about.source": "Le contenu de l'outil de dialogue de cette application (dimensions, aspects et questions de conversation) est © iPH/PHi. La formulation anglaise est reproduite d'après les outils officiels en anglais de Positive Health International, en collaboration avec l'institut pour Positive Health (iPH). Les traductions dans d'autres langues sont non officielles et ont été réalisées pour cette application. Les textes explicatifs résument l'information publique des deux organisations.\n\nCette application est un compagnon à usage personnel. Ce n'est pas un dispositif médical et elle ne fournit ni diagnostic ni conseil médical. Vos réponses sont stockées uniquement sur cet appareil.",
        "dimexpl.body": "Comment votre corps se sent et fonctionne — se sentir en bonne santé et en forme, dormir, manger, bouger, et être libre de plaintes ou de douleurs.",
        "dimexpl.mind": "Votre vie intérieure — se souvenir et se concentrer, gérer vos émotions, vous accepter et vous sentir maître de la situation.",
        "dimexpl.meaning": "Le sens et la direction — une vie qui a du sens, la joie de vivre, les idéaux et les rêves, la confiance, l'acceptation et la gratitude.",
        "dimexpl.quality": "Comment vous vivez votre vie — le plaisir, le bonheur, l'équilibre, la sécurité, et des circonstances telles que le logement et l'argent.",
        "dimexpl.participation": "Votre lien avec les autres — les contacts sociaux, être pris au sérieux, l'appartenance, le soutien, et faire des choses qui ont du sens ensemble.",
        "dimexpl.daily": "Gérer la vie quotidienne — prendre soin de vous, travailler ou étudier, connaître vos limites, et être capable de demander de l'aide.",
        "adult.body": "Fonctions corporelles",
        "adult.mind": "Bien-être mental",
        "adult.meaning": "Sens de la vie",
        "adult.quality": "Qualité de vie",
        "adult.participation": "Participation",
        "adult.daily": "Fonctionnement quotidien",
        "adolescent.body": "Mon corps",
        "adolescent.mind": "Mes émotions et mes pensées",
        "adolescent.meaning": "Sens de la vie",
        "adolescent.quality": "Qualité de vie",
        "adolescent.participation": "Participation",
        "adolescent.daily": "Vie quotidienne",
        "child.body": "Mon corps",
        "child.mind": "Mes émotions et mes pensées",
        "child.meaning": "Maintenant et à l'avenir",
        "child.quality": "Se sentir bien dans sa peau",
        "child.participation": "Participation",
        "child.daily": "Vie quotidienne",
        "adult.body.1": "Se sentir en bonne santé",
        "adult.body.2": "Se sentir en forme",
        "adult.body.3": "Pas de plaintes physiques ni de douleurs",
        "adult.body.4": "Dormir",
        "adult.body.5": "Manger",
        "adult.body.6": "Sexualité",
        "adult.body.7": "Condition physique",
        "adult.body.8": "Activité physique",
        "adult.mind.1": "Être capable de se souvenir des choses",
        "adult.mind.2": "Être capable de se concentrer",
        "adult.mind.3": "Être capable de communiquer",
        "adult.mind.4": "Être de bonne humeur",
        "adult.mind.5": "S'accepter",
        "adult.mind.6": "Être capable de gérer le changement",
        "adult.mind.7": "Se sentir maître de la situation",
        "adult.meaning.1": "Avoir une vie qui a du sens",
        "adult.meaning.2": "Avoir la joie de vivre",
        "adult.meaning.3": "Poursuivre ses idéaux",
        "adult.meaning.4": "Avoir confiance",
        "adult.meaning.5": "Accepter la vie",
        "adult.meaning.6": "Être reconnaissant",
        "adult.meaning.7": "Apprendre tout au long de la vie",
        "adult.quality.1": "Le plaisir",
        "adult.quality.2": "Être heureux",
        "adult.quality.3": "Se sentir bien",
        "adult.quality.4": "Se sentir équilibré",
        "adult.quality.5": "Se sentir en sécurité",
        "adult.quality.6": "Intimité",
        "adult.quality.7": "Conditions de logement",
        "adult.quality.8": "Avoir assez d'argent",
        "adult.participation.1": "Contacts sociaux",
        "adult.participation.2": "Être pris au sérieux",
        "adult.participation.3": "Faire des choses agréables ensemble",
        "adult.participation.4": "Avoir le soutien des autres",
        "adult.participation.5": "Sentiment d'appartenance",
        "adult.participation.6": "Faire des choses qui ont du sens",
        "adult.participation.7": "S'intéresser à la société",
        "adult.daily.1": "Prendre soin de vous",
        "adult.daily.2": "Connaître vos limites",
        "adult.daily.3": "Connaissances en matière de santé",
        "adult.daily.4": "Gérer son temps",
        "adult.daily.5": "Gérer son argent",
        "adult.daily.6": "Être capable de travailler",
        "adult.daily.7": "Être capable de demander de l'aide",
        "adolescent.body.1": "Se sentir en bonne santé",
        "adolescent.body.2": "Avoir de l'énergie",
        "adolescent.body.3": "Pas de plaintes physiques ni de douleurs",
        "adolescent.body.4": "Manger sainement",
        "adolescent.body.5": "Dormir",
        "adolescent.body.6": "Forme physique",
        "adolescent.body.7": "Sport et exercice",
        "adolescent.body.8": "Apparence physique",
        "adolescent.mind.1": "Concentration",
        "adolescent.mind.2": "Gérer ses émotions",
        "adolescent.mind.3": "Voir la vie de façon positive",
        "adolescent.mind.4": "S'accepter",
        "adolescent.mind.5": "Avoir confiance en soi",
        "adolescent.mind.6": "Faire face au changement",
        "adolescent.mind.7": "Être maître de la situation",
        "adolescent.meaning.1": "Mener une vie qui a du sens",
        "adolescent.meaning.2": "Avoir confiance en l'avenir",
        "adolescent.meaning.3": "Avoir la joie de vivre",
        "adolescent.meaning.4": "Avoir des objectifs et des rêves",
        "adolescent.meaning.5": "Faire des choix",
        "adolescent.meaning.6": "Accepter les situations",
        "adolescent.meaning.7": "Gratitude",
        "adolescent.quality.1": "Bonheur",
        "adolescent.quality.2": "Le plaisir",
        "adolescent.quality.3": "Ressentir un équilibre",
        "adolescent.quality.4": "Se sentir en sécurité",
        "adolescent.quality.5": "Un environnement agréable",
        "adolescent.quality.6": "Logement et cadre de vie",
        "adolescent.quality.7": "Joindre les deux bouts",
        "adolescent.participation.1": "Contacts sociaux",
        "adolescent.participation.2": "Être pris au sérieux",
        "adolescent.participation.3": "Faire des choses agréables avec d'autres personnes",
        "adolescent.participation.4": "Appartenir",
        "adolescent.participation.5": "S'exprimer",
        "adolescent.participation.6": "Relations qui ont du sens",
        "adolescent.participation.7": "Recevoir du soutien et de la compréhension de la part des autres",
        "adolescent.daily.1": "Prendre soin de vous",
        "adolescent.daily.2": "Être capable de travailler ou d'étudier",
        "adolescent.daily.3": "Connaître vos limites",
        "adolescent.daily.4": "Connaissances sur la santé",
        "adolescent.daily.5": "Capacité à planifier",
        "adolescent.daily.6": "Être capable de demander de l'aide",
        "adolescent.daily.7": "Pas de tabac, d'alcool ni de drogues",
        "child.body.1": "Se sentir bien",
        "child.body.2": "Avoir de l'énergie",
        "child.body.3": "Manger sainement",
        "child.body.4": "Bien dormir",
        "child.body.5": "Sport et exercice",
        "child.body.6": "Pas de plaintes physiques",
        "child.body.7": "Pas de douleur",
        "child.body.8": "Apparence physique",
        "child.mind.1": "Gérer ses émotions",
        "child.mind.2": "S'accepter",
        "child.mind.3": "Se sentir à sa place",
        "child.mind.4": "Voir la vie de façon positive",
        "child.mind.5": "Connaître ses limites",
        "child.mind.6": "Faire face à l'adversité",
        "child.meaning.1": "Regarder vers l'avenir",
        "child.meaning.2": "Culture et religion",
        "child.meaning.3": "Avoir des objectifs et des rêves",
        "child.meaning.4": "Faire des choix",
        "child.meaning.5": "Se connaître soi-même",
        "child.meaning.6": "Modèles à suivre",
        "child.quality.1": "Le plaisir",
        "child.quality.2": "Bonheur",
        "child.quality.3": "Bonne humeur",
        "child.quality.4": "Un environnement agréable",
        "child.quality.5": "Prendre du plaisir à faire des choses",
        "child.quality.6": "Recevoir du soutien et de la compréhension de la part des autres",
        "child.participation.1": "Amis",
        "child.participation.2": "Appartenir",
        "child.participation.3": "Le harcèlement",
        "child.participation.4": "L'autodétermination",
        "child.participation.5": "Suivre le rythme des autres",
        "child.participation.6": "Contribution personnelle",
        "child.daily.1": "Aller à l'école",
        "child.daily.2": "Être soi-même",
        "child.daily.3": "Temps libre",
        "child.daily.4": "Prendre soin de soi",
        "child.daily.5": "Se sentir normal",
        "child.daily.6": "Limites",
        "child.daily.7": "Pas de tabac, d'alcool ni de drogue",
    ]
}
