import Foundation

// Unofficial translation generated for this app — NOT the official Positive Health wording.
enum German {
    static let table: [String: String] = [
        "done": "Fertig",
        "cancel": "Abbrechen",
        "back": "Zurück",
        "next": "Weiter",
        "app_title": "Meine Positive Health",
        "fill_menu": "Spinnennetz ausfüllen",
        "empty_title": "Fülle dein Spinnennetz aus",
        "empty_desc": "Positive Health schaut darauf, was dir wichtig ist – über sechs Dimensionen der Gesundheit hinweg. Fülle das Spinnennetz aus, um deinen persönlichen Überblick zu bekommen – ein Ausgangspunkt für ein anderes Gespräch.",
        "version.adult.title": "Erwachsene",
        "version.adolescent.title": "Jugendliche / junge Erwachsene",
        "version.child.title": "Kinder",
        "version.adult.age": "18+ Jahre",
        "version.adolescent.age": "16–25 Jahre",
        "version.child.age": "8–16 Jahre",
        "reflect.adult": "Etwas, das mir wichtig ist, fehlt:",
        "reflect.adolescent": "Das Folgende ist mir besonders wichtig",
        "reflect.child": "Das Folgende ist mir besonders wichtig",
        "q.how_feel": "Wie fühlst du dich damit? Es gibt keine richtigen oder falschen Antworten.",
        "q.include12": "Fragen für Personen ab 12 Jahren einbeziehen",
        "q.almost_done": "Fast geschafft",
        "q.write_here": "Schreib es hier auf…",
        "q.save_footer": "Wenn du speicherst, erscheint dein persönlicher Überblick im Spinnennetz. Denk daran: Das ist kein Test und es gibt keine Norm – es ist dein eigenes Bild dieses Moments und ein Ausgangspunkt für ein Gespräch.",
        "q.show_web": "Mein Spinnennetz zeigen",
        "r.compare": "Mit früherem vergleichen",
        "r.no_norm_footer": "Es gibt keine Norm und keine Punktzahl, die du erreichen musst. Das ist dein eigenes Bild dieses Moments.",
        "r.my_dimensions": "Meine Dimensionen",
        "r.other_conversation": "Das andere Gespräch",
        "r.other_footer": "Es spielt keine Rolle, wo du anfängst – wichtig ist, dass du anfängst und kleine Schritte machst. Wenn sich ein Punkt bewegt, bewegen sich auch andere Punkte.",
        "r.your_answer": "Deine Antwort…",
        "conv.attention": "Gibt es etwas, dem du mehr Aufmerksamkeit schenken oder das du verändern möchtest?",
        "conv.step": "Welchen kleinen Schritt könntest du selbst gehen?",
        "conv.support": "Wer oder was könnte dich dabei unterstützen?",
        "settings.title": "Einstellungen",
        "settings.language": "Sprache",
        "settings.language_footer": "Englisch verwendet den offiziellen Wortlaut der Positive-Health-Werkzeuge. Die anderen Sprachen sind inoffizielle Übersetzungen, die für diese App erstellt wurden.",
        "about.title": "Über Positive Health",
        "about.s.whatisit": "Was ist Positive Health?",
        "about.s.origin": "Woher kommt es?",
        "about.s.dimensions": "Die sechs Dimensionen",
        "about.s.spiderweb": "Das Spinnennetz",
        "about.s.conversation": "Das andere Gespräch",
        "about.s.steps": "Wie es funktioniert – drei Schritte",
        "about.s.who": "Für wen ist es?",
        "about.s.movement": "Eine Bewegung, nicht nur ein Werkzeug",
        "about.s.value": "Der Wert, den es anstrebt",
        "about.s.resources": "Weitere Ressourcen",
        "about.s.versions": "Versionen in dieser App",
        "about.s.learnmore": "Mehr erfahren",
        "about.whatisit": "Positive Health ist ein breiter Blick auf Gesundheit, der in den Niederlanden entwickelt wurde. Statt Gesundheit als das Fehlen von Krankheit zu definieren, sieht sie den Menschen als ganze Person: seine Widerstandskraft – die Fähigkeit, mit den körperlichen, emotionalen und sozialen Herausforderungen des Lebens umzugehen – und das, was sein Leben sinnvoll macht. Die zentrale Frage verschiebt sich von „Was fehlt Ihnen?“ zu „Was ist Ihnen wichtig?“\n\nEs ist keine Behandlung und kein Test. Es ist eine Art zu schauen, ein Reflexionswerkzeug und ein Gesprächsanstoß, der dir hilft, so weit wie möglich selbst über dein Leben zu bestimmen.",
        "about.quote": "Ich bin überzeugt, dass von allen Kräften, die Gesundheit stärken, die Sinnhaftigkeit die stärkste ist.",
        "about.quote_author": "Machteld Huber, Begründerin von Positive Health",
        "about.origin": "Positive Health wurde von Machteld Huber angestoßen, einer ehemaligen niederländischen Hausärztin und Forscherin. Nachdem sie selbst schwer erkrankt war, bemerkte sie, wie sehr ihre eigene Haltung und ihr Gefühl von Richtung ihre Genesung beeinflussten – etwas, wofür das vorherrschende Gesundheitsverständnis keinen Platz hatte.\n\nDie Definition der Weltgesundheitsorganisation von 1948 beschreibt Gesundheit als einen Zustand vollständigen körperlichen, geistigen und sozialen Wohlbefindens. Huber und ihre Kolleginnen und Kollegen argumentierten im British Medical Journal (2011), dass dieses Ideal des „vollständigen Wohlbefindens“ statisch und unerreichbar ist – nach diesem Maßstab ist fast niemand gesund, am wenigsten Menschen, die mit einer chronischen Erkrankung leben. Sie schlugen eine dynamische Alternative vor: Gesundheit als die Fähigkeit, sich anzupassen und sich angesichts der Herausforderungen des Lebens selbst zu steuern.\n\nUm herauszufinden, was Gesundheit für die Menschen selbst bedeutet, befragte Hubers Team anschließend Patientinnen und Patienten, Pflegefachkräfte und Forschende. Die Hunderte von Gesundheitsindikatoren, die aus dieser Studie hervorgingen, wurden zu sechs Hauptdimensionen gruppiert – den sechs Achsen des Spinnennetzes. Die Forschung baut auch auf älteren Erkenntnissen auf: Aaron Antonovskys Salutogenese (die Frage, was Gesundheit schafft, statt was Krankheit verursacht) und den Blue Zones, Regionen, in denen Menschen bei bemerkenswert guter Gesundheit alt werden.",
        "about.spiderweb": "Du füllst den Fragebogen selbst aus und bewertest jeden Aspekt von 0 bis 10. Deine Antworten werden als deine persönliche Gesundheitsfläche im Spinnennetz dargestellt. Es gibt keine Norm und nichts zu bestehen oder zu versäumen: Das Netz zeigt, wie du deine Gesundheit in diesem Moment erlebst, in allen sechs Dimensionen – ein Bild, das viel reicher ist als eine einzelne Zahl.\n\nSchon das Ausfüllen ist oft ein Aha-Erlebnis: Gesundheit ist nicht nur dein Körper und deine Stimmung, sondern auch Sinn, Teilhabe, Lebensqualität und wie du deinen Alltag bewältigst.",
        "about.conversation": "Das Spinnennetz ist der Ausgangspunkt für das, was Positive Health „das andere Gespräch“ nennt – mit einer Ärztin oder einem Arzt, einer Pflegekraft, einem Coach, einer Sozialarbeiterin oder jemandem, dem du vertraust. Das Gespräch weitet sich zunächst (der Blick auf das ganze Netz, nicht nur auf eine Beschwerde) und richtet sich dann auf das, was dir wirklich wichtig ist. Es geht nicht um die niedrigsten Werte; du wählst selbst, wem du Aufmerksamkeit schenken möchtest.\n\nSolche Gespräche nehmen regelmäßig überraschende Wendungen: Das, womit jemand zuerst kam, stellt sich oft nicht als das heraus, woran er am meisten arbeiten möchte. Meistens wissen die Menschen schon, was nötig ist – das Netz hilft, es auszusprechen.\n\nVon dort aus ist der Ansatz bewusst klein: Wähle einen kleinen Schritt, den du selbst gehen kannst, und überlege, wer oder was dich unterstützen könnte. Wenn sich ein Punkt des Netzes bewegt, bewegen sich meist auch andere Punkte.",
        "about.step1.title": "Fülle das Spinnennetz aus",
        "about.step1.text": "Bewerte, wie du dich mit jedem Aspekt fühlst, von 0 bis 10. Es dauert nur ein paar Minuten. Es gibt keine Norm – es ist eine persönliche Einschätzung dieses Moments.",
        "about.step2.title": "Führe das andere Gespräch",
        "about.step2.text": "Nutze dein Spinnennetz als Gesprächsanstoß – mit einer Ärztin oder einem Arzt, einer Pflegekraft, einer Sozialarbeiterin, einem Coach oder einer Freundin bzw. einem Freund. Nicht darüber, wo die Werte niedrig sind, sondern darüber, wohin du willst und was dir wichtig ist.",
        "about.step3.title": "Mach einen kleinen Schritt",
        "about.step3.text": "Wähle einen kleinen Schritt, den du selbst gehen kannst, und überlege, wer oder was dich unterstützen könnte. Wenn sich ein Punkt des Netzes bewegt, bewegen sich auch andere Punkte.",
        "about.who": "Die Dialogwerkzeuge gibt es in drei Versionen – für Erwachsene, für Jugendliche und junge Erwachsene sowie für Kinder – sodass alle ab etwa 8 Jahren ihr eigenes Netz ausfüllen können. Die offiziellen Werkzeuge sind in mehr als zehn Sprachen veröffentlicht, und eine Online-Version ist unter mypositivehealth.com verfügbar.\n\nPositive Health begann in den Niederlanden und wird heute international genutzt, von Hausarztpraxen und Krankenhäusern bis hin zu Schulen, Arbeitsplätzen und ganzen Regionen. Es wird auf vier Ebenen angewendet: von Einzelnen für sich selbst, von Fachkräften in ihrer täglichen Arbeit, von Gemeinschaften und im Gesundheitssystem als Ganzem – als Antrieb für den Wandel von einer krankheitsorientierten zu einer gesundheitsorientierten Versorgung.",
        "about.movement": "Positive Health ist nicht nur ein Werkzeug, sondern eine Bewegung – eine andere Art zu denken, zu handeln, zu organisieren und Versorgung zu finanzieren. Es beginnt meist mit einigen engagierten Menschen und lokalen Partnern, die eine gemeinsame Vision teilen, und wächst zu breiteren Bündnissen heran. Die Art der Umsetzung unterscheidet sich je nach Land und Kultur, doch die Kernvision bleibt dieselbe. In den Niederlanden hat es sich im vergangenen Jahrzehnt in vielen Bereichen verankert und breitet sich nun international aus.\n\nIm Kern steht eine Abkehr vom „Reparaturreflex“ – dem automatischen Drang, eine Beschwerde zu beheben – hin dazu, Menschen zu befähigen, zu erkennen, was sie selbst tun können, um ein zielgerichtetes, sinnvolles Leben zu führen.",
        "about.value": "In der Versorgung strebt Positive Health das an, was als „Quadruple Aim“ bekannt ist:\n\n• Die Gesundheit der Bevölkerung verbessern\n• Das Erleben der Versorgung für die Menschen verbessern\n• Kosten senken\n• Das Wohlbefinden von Versorgungsteams und Fachkräften verbessern\n\nZusammen beschreiben sie einen Wandel von krankheitsorientierter zu gesundheitsorientierter Versorgung – einer Versorgung, die davon ausgeht, was einem Menschen wichtig ist, und nicht nur davon, was ihm fehlt.",
        "about.resources": "Über das Spinnennetz hinaus bieten Positive Health International und das institute for Positive Health (iPH) weitere Möglichkeiten, tiefer einzusteigen:\n\n• Das Online-Spinnennetz unter mypositivehealth.com, um es digital auszufüllen.\n• Ein E-Learning-Modul, „The Essence of Positive Health“, als Einführung.\n• Ein Handbuch mit umfassender Anleitung.\n• Kostenlose Downloads und Materialien für Menschen und Fachkräfte.\n\nDiese App ist ein unabhängiger persönlicher Begleiter, mit dem du das Spinnennetz auf deinem Gerät ausfüllen kannst; die oben genannten Ressourcen sind die Quelle und der Ort, um mehr zu erfahren.",
        "about.link.phi": "Positive Health International – Dialogwerkzeuge",
        "about.link.iph": "Institute for Positive Health (iPH)",
        "about.link.online": "My Positive Health – offizielles Online-Spinnennetz",
        "about.source": "Die Inhalte der Dialogwerkzeuge in dieser App (Dimensionen, Aspekte und Gesprächsfragen) sind © iPH/PHi. Der englische Wortlaut wird aus den offiziellen englischen Werkzeugen von Positive Health International in Zusammenarbeit mit dem institute for Positive Health (iPH) übernommen. Übersetzungen in andere Sprachen sind inoffiziell und wurden für diese App erstellt. Die erläuternden Texte fassen die öffentlichen Informationen beider Organisationen zusammen.\n\nDiese App ist ein Begleiter für den persönlichen Gebrauch. Sie ist kein Medizinprodukt und stellt keine Diagnosen oder medizinischen Ratschläge bereit. Deine Antworten werden nur auf diesem Gerät gespeichert.",
        "dimexpl.body": "Wie sich dein Körper anfühlt und funktioniert – sich gesund und fit fühlen, schlafen, essen, sich bewegen und frei von Beschwerden oder Schmerzen sein.",
        "dimexpl.mind": "Dein Innenleben – sich erinnern und konzentrieren, mit deinen Gefühlen umgehen, dich selbst annehmen und dich in Kontrolle fühlen.",
        "dimexpl.meaning": "Sinn und Richtung – ein sinnvolles Leben, Lebensfreude, Ideale und Träume, Zuversicht, Annahme und Dankbarkeit.",
        "dimexpl.quality": "Wie du dein Leben erlebst – Freude, Glück, Ausgeglichenheit, Sicherheit und Umstände wie Wohnen und Geld.",
        "dimexpl.participation": "Deine Verbundenheit mit anderen – soziale Kontakte, ernst genommen werden, Zugehörigkeit, Unterstützung und gemeinsam Sinnvolles tun.",
        "dimexpl.daily": "Den Alltag bewältigen – für dich selbst sorgen, arbeiten oder lernen, deine Grenzen kennen und um Hilfe bitten können.",
        "adult.body": "Körperfunktionen",
        "adult.mind": "Psychisches Wohlbefinden",
        "adult.meaning": "Sinnhaftigkeit",
        "adult.quality": "Lebensqualität",
        "adult.participation": "Teilhabe",
        "adult.daily": "Alltagsfunktionen",
        "adolescent.body": "Mein Körper",
        "adolescent.mind": "Meine Gefühle und Gedanken",
        "adolescent.meaning": "Sinnhaftigkeit",
        "adolescent.quality": "Lebensqualität",
        "adolescent.participation": "Teilhabe",
        "adolescent.daily": "Alltag",
        "child.body": "Mein Körper",
        "child.mind": "Meine Gefühle und Gedanken",
        "child.meaning": "Jetzt und in der Zukunft",
        "child.quality": "Sich gut fühlen",
        "child.participation": "Teilhabe",
        "child.daily": "Alltag",
        "adult.body.1": "Sich gesund fühlen",
        "adult.body.2": "Sich fit fühlen",
        "adult.body.3": "Keine körperlichen Beschwerden oder Schmerzen",
        "adult.body.4": "Schlafen",
        "adult.body.5": "Essen",
        "adult.body.6": "Sexualität",
        "adult.body.7": "Körperliche Verfassung",
        "adult.body.8": "Körperliche Aktivität",
        "adult.mind.1": "Sich Dinge merken können",
        "adult.mind.2": "Sich konzentrieren können",
        "adult.mind.3": "Sich mitteilen können",
        "adult.mind.4": "Fröhlich sein",
        "adult.mind.5": "Sich selbst annehmen",
        "adult.mind.6": "Mit Veränderung umgehen können",
        "adult.mind.7": "Sich in Kontrolle fühlen",
        "adult.meaning.1": "Ein sinnvolles Leben führen",
        "adult.meaning.2": "Lebensfreude haben",
        "adult.meaning.3": "Ideale verfolgen",
        "adult.meaning.4": "Sich zuversichtlich fühlen",
        "adult.meaning.5": "Das Leben annehmen",
        "adult.meaning.6": "Dankbar sein",
        "adult.meaning.7": "Lebenslang lernen",
        "adult.quality.1": "Genuss",
        "adult.quality.2": "Glücklich sein",
        "adult.quality.3": "Sich wohlfühlen",
        "adult.quality.4": "Sich ausgeglichen fühlen",
        "adult.quality.5": "Sich sicher fühlen",
        "adult.quality.6": "Nähe",
        "adult.quality.7": "Wohnsituation",
        "adult.quality.8": "Genug Geld haben",
        "adult.participation.1": "Soziale Kontakte",
        "adult.participation.2": "Ernst genommen werden",
        "adult.participation.3": "Gemeinsam schöne Dinge tun",
        "adult.participation.4": "Unterstützung von anderen haben",
        "adult.participation.5": "Zugehörigkeitsgefühl",
        "adult.participation.6": "Sinnvolle Dinge tun",
        "adult.participation.7": "Interesse an der Gesellschaft",
        "adult.daily.1": "Für sich selbst sorgen",
        "adult.daily.2": "Seine Grenzen kennen",
        "adult.daily.3": "Wissen über Gesundheit",
        "adult.daily.4": "Zeit einteilen",
        "adult.daily.5": "Mit Geld umgehen",
        "adult.daily.6": "Arbeiten können",
        "adult.daily.7": "Um Hilfe bitten können",
        "adolescent.body.1": "Sich gesund fühlen",
        "adolescent.body.2": "Energie haben",
        "adolescent.body.3": "Keine körperlichen Beschwerden oder Schmerzen",
        "adolescent.body.4": "Gesund essen",
        "adolescent.body.5": "Schlafen",
        "adolescent.body.6": "Fitness",
        "adolescent.body.7": "Sport & Bewegung",
        "adolescent.body.8": "Aussehen",
        "adolescent.mind.1": "Konzentration",
        "adolescent.mind.2": "Mit deinen Gefühlen umgehen",
        "adolescent.mind.3": "Positiv aufs Leben blicken",
        "adolescent.mind.4": "Dich selbst annehmen",
        "adolescent.mind.5": "Vertrauen in dich selbst",
        "adolescent.mind.6": "Mit Veränderung umgehen",
        "adolescent.mind.7": "In Kontrolle sein",
        "adolescent.meaning.1": "Ein sinnvolles Leben führen",
        "adolescent.meaning.2": "Vertrauen in die Zukunft haben",
        "adolescent.meaning.3": "Lebensfreude haben",
        "adolescent.meaning.4": "Ziele und Träume haben",
        "adolescent.meaning.5": "Entscheidungen treffen",
        "adolescent.meaning.6": "Situationen annehmen",
        "adolescent.meaning.7": "Dankbarkeit",
        "adolescent.quality.1": "Glück",
        "adolescent.quality.2": "Genuss",
        "adolescent.quality.3": "Ausgeglichenheit erleben",
        "adolescent.quality.4": "Sich sicher fühlen",
        "adolescent.quality.5": "Eine angenehme Umgebung",
        "adolescent.quality.6": "Wohnen und Wohnumfeld",
        "adolescent.quality.7": "Über die Runden kommen",
        "adolescent.participation.1": "Soziale Kontakte",
        "adolescent.participation.2": "Ernst genommen werden",
        "adolescent.participation.3": "Schöne Dinge mit anderen tun",
        "adolescent.participation.4": "Zugehörigkeit",
        "adolescent.participation.5": "Sich ausdrücken",
        "adolescent.participation.6": "Bedeutsame Beziehungen",
        "adolescent.participation.7": "Unterstützung und Verständnis von anderen erhalten",
        "adolescent.daily.1": "Für dich selbst sorgen",
        "adolescent.daily.2": "Arbeiten oder lernen können",
        "adolescent.daily.3": "Deine Grenzen kennen",
        "adolescent.daily.4": "Wissen über Gesundheit",
        "adolescent.daily.5": "Planen können",
        "adolescent.daily.6": "Um Hilfe bitten können",
        "adolescent.daily.7": "Kein Rauchen, Alkohol oder Drogen",
        "child.body.1": "Sich gut fühlen",
        "child.body.2": "Energie haben",
        "child.body.3": "Gesund essen",
        "child.body.4": "Gut schlafen",
        "child.body.5": "Sport & Bewegung",
        "child.body.6": "Keine körperlichen Beschwerden",
        "child.body.7": "Keine Schmerzen",
        "child.body.8": "Aussehen",
        "child.mind.1": "Mit deinen Gefühlen umgehen",
        "child.mind.2": "Dich selbst annehmen",
        "child.mind.3": "Dazugehören",
        "child.mind.4": "Positiv aufs Leben blicken",
        "child.mind.5": "Deine Grenzen kennen",
        "child.mind.6": "Mit Rückschlägen umgehen",
        "child.meaning.1": "In die Zukunft blicken",
        "child.meaning.2": "Kultur und Religion",
        "child.meaning.3": "Ziele und Träume haben",
        "child.meaning.4": "Entscheidungen treffen",
        "child.meaning.5": "Sich selbst kennen",
        "child.meaning.6": "Vorbilder",
        "child.quality.1": "Genuss",
        "child.quality.2": "Glück",
        "child.quality.3": "Fröhlichkeit",
        "child.quality.4": "Eine angenehme Umgebung",
        "child.quality.5": "Freude an dem haben, was du tust",
        "child.quality.6": "Unterstützung und Verständnis von anderen erhalten",
        "child.participation.1": "Freunde",
        "child.participation.2": "Zugehörigkeit",
        "child.participation.3": "Mobbing",
        "child.participation.4": "Selbstbestimmung",
        "child.participation.5": "Mit anderen mithalten",
        "child.participation.6": "Eigener Beitrag",
        "child.daily.1": "Zur Schule gehen",
        "child.daily.2": "Du selbst sein",
        "child.daily.3": "Freizeit",
        "child.daily.4": "Auf dich selbst achten",
        "child.daily.5": "Sich normal fühlen",
        "child.daily.6": "Grenzen",
        "child.daily.7": "Kein Rauchen, Alkohol oder Drogenkonsum",
    ]
}
