import Foundation

// Unofficial translation generated for this app — NOT the official Positive Health wording.
enum Hungarian {
    static let table: [String: String] = [
        "done": "Kész",
        "cancel": "Mégse",
        "back": "Vissza",
        "next": "Tovább",
        "app_title": "Az én Positive Health-em",
        "fill_menu": "Töltsd ki a pókhálót",
        "empty_title": "Töltsd ki a pókhálódat",
        "empty_desc": "A Positive Health azt nézi, ami számodra fontos, az egészség hat dimenziójában. Töltsd ki a pókhálót, hogy megkapd a személyes áttekintésedet – egy kiindulópontot egy másfajta beszélgetéshez.",
        "version.adult.title": "Felnőttek",
        "version.adolescent.title": "Serdülők / fiatal felnőttek",
        "version.child.title": "Gyermekek",
        "version.adult.age": "18+ év",
        "version.adolescent.age": "16–25 év",
        "version.child.age": "8–16 év",
        "reflect.adult": "Valami, ami fontos nekem, hiányzik:",
        "reflect.adolescent": "A következő különösen fontos nekem",
        "reflect.child": "A következő különösen fontos nekem",
        "q.how_feel": "Hogy érzed magad ezzel kapcsolatban? Nincsenek jó vagy rossz válaszok.",
        "q.include12": "A 12 éves és idősebb korosztálynak szóló kérdések megjelenítése",
        "q.almost_done": "Majdnem kész",
        "q.write_here": "Írd ide…",
        "q.save_footer": "Amikor mentesz, a személyes áttekintésed megjelenik a pókhálóban. Ne feledd: ez nem teszt, és nincs norma – ez a saját képed erről a pillanatról, és egy kiindulópont egy beszélgetéshez.",
        "q.show_web": "Mutasd a pókhálómat",
        "r.compare": "Összehasonlítás a korábbival",
        "r.no_norm_footer": "Nincs norma és nincs elérendő pontszám. Ez a saját képed erről a pillanatról.",
        "r.my_dimensions": "A dimenzióim",
        "r.other_conversation": "A másfajta beszélgetés",
        "r.other_footer": "Nem az számít, hol kezdesz – az számít, hogy elkezded, és hogy kis lépéseket teszel. Amikor egy pont elmozdul, más pontok is elmozdulnak.",
        "r.your_answer": "A válaszod…",
        "conv.attention": "Van valami, aminek több figyelmet szeretnél szentelni, vagy amin változtatnál?",
        "conv.step": "Milyen kis lépést tudnál te magad megtenni?",
        "conv.support": "Ki vagy mi tudna ebben támogatni?",
        "settings.title": "Beállítások",
        "settings.language": "Nyelv",
        "settings.language_footer": "Az angol a Positive Health eszközök hivatalos megfogalmazását használja. A többi nyelv nem hivatalos fordítás, amely ehhez az alkalmazáshoz készült.",
        "about.title": "A Positive Health-ről",
        "about.s.whatisit": "Mi az a Positive Health?",
        "about.s.origin": "Honnan ered?",
        "about.s.dimensions": "A hat dimenzió",
        "about.s.spiderweb": "A pókháló",
        "about.s.conversation": "A másfajta beszélgetés",
        "about.s.steps": "Hogyan működik – három lépés",
        "about.s.who": "Kinek szól?",
        "about.s.movement": "Egy mozgalom, nem csupán egy eszköz",
        "about.s.value": "Az érték, amelyre törekszik",
        "about.s.resources": "További források",
        "about.s.versions": "Verziók ebben az alkalmazásban",
        "about.s.learnmore": "Tudj meg többet",
        "about.whatisit": "A Positive Health az egészség tág szemlélete, amelyet Hollandiában dolgoztak ki. Ahelyett, hogy az egészséget a betegség hiányaként határozná meg, az embereket egész személyként nézi: az ellenálló képességüket – vagyis azt, ahogyan az élet testi, érzelmi és társas kihívásaival megbirkóznak – és azt, ami az életüket értelmessé teszi. A központi kérdés a „Mi a bajod?”-ról a „Mi számít neked?”-re helyeződik át.\n\nEz nem kezelés és nem teszt. Ez egy szemléletmód, egy önreflexiós eszköz és egy beszélgetésindító, amely segít, hogy amennyire csak lehetséges, kézben tartsd a saját életedet.",
        "about.quote": "Meggyőződésem, hogy az egészséget erősítő minden erő közül az értelmesség a legerősebb.",
        "about.quote_author": "Machteld Huber, a Positive Health megalapítója",
        "about.origin": "A Positive Health-t Machteld Huber kezdeményezte, egy egykori holland háziorvos és kutató. Miután ő maga súlyosan megbetegedett, észrevette, mennyire befolyásolta a felépülését a saját hozzáállása és irányérzéke – valami, aminek az egészség uralkodó szemléletében nem volt helye.\n\nAz Egészségügyi Világszervezet 1948-as meghatározása az egészséget a teljes testi, lelki és társadalmi jóllét állapotaként írja le. Huber és kollégái a British Medical Journalban (2011) azzal érveltek, hogy a „teljes jóllét” eszménye statikus és elérhetetlen – ezen mérce szerint szinte senki sem egészséges, legkevésbé a krónikus betegséggel élők. Egy dinamikus alternatívát javasoltak: az egészség mint az a képesség, hogy az élet kihívásaival szemben alkalmazkodni és önmagunkat irányítani tudjuk.\n\nHogy megtudják, mit is jelent az egészség maguknak az embereknek, Huber csapata ezután betegeket, egészségügyi szakembereket és kutatókat kérdezett meg. Az e vizsgálatból származó több száz egészségjelzőt hat fő dimenzióba csoportosították – ezek a pókháló hat tengelye. A kutatás régebbi felismerésekre is épít: Aaron Antonovsky szalutogenezisére (amely azt vizsgálja, mi teremt egészséget, nem pedig azt, mi okoz betegséget) és a Blue Zones-ra, azokra a régiókra, ahol az emberek feltűnően jó egészségben érnek meg idős kort.",
        "about.spiderweb": "A kérdőívet magad töltöd ki, minden szempontot 0-tól 10-ig pontozva. A válaszaid a pókhálóban a személyes egészségfelületedként jelennek meg. Nincs norma, és nincs semmi, amin átmenni vagy megbukni lehet: a pókháló azt mutatja, hogyan éled meg az egészségedet ebben a pillanatban, mind a hat dimenzióban – egy kép, amely sokkal gazdagabb egyetlen számnál.\n\nA kitöltés önmagában is gyakran szemnyitogató: kiderül, hogy az egészség nemcsak a tested és a hangulatod, hanem az értelem, a részvétel, az életminőség és az is, ahogyan a mindennapjaidat kezeled.",
        "about.conversation": "A pókháló a kiindulópontja annak, amit a Positive Health „a másfajta beszélgetésnek” nevez – egy orvossal, ápolóval, coachcsal, szociális munkással vagy valakivel, akiben megbízol. A beszélgetés először kitágul (az egész pókhálót nézi, nem csak egy panaszt), majd leszűkül arra, ami valóban számít neked. Nem a legalacsonyabb pontszámokról szól; te választod meg, minek szeretnél figyelmet szentelni.\n\nAz ilyen beszélgetések rendszeresen meglepő fordulatokat vesznek: kiderül, hogy amivel valaki először beállított, nem az, amin a leginkább dolgozni szeretne. Az emberek általában már tudják, mire van szükségük – a pókháló segít abban, hogy ki is mondják.\n\nInnen a megközelítés szándékosan apró: válassz egy kis lépést, amelyet te magad megtehetsz, és gondold végig, ki vagy mi tudna támogatni. Amikor a pókháló egyik pontja elmozdul, hajlamosak más pontok is elmozdulni.",
        "about.step1.title": "Töltsd ki a pókhálót",
        "about.step1.text": "Pontozd, hogyan érzel az egyes szempontokkal kapcsolatban, 0-tól 10-ig. Csak néhány percet vesz igénybe. Nincs norma – ez a pillanat személyes értékelése.",
        "about.step2.title": "Folytasd le a másfajta beszélgetést",
        "about.step2.text": "Használd a pókhálódat beszélgetésindítóként – egy orvossal, ápolóval, szociális munkással, coachcsal vagy egy baráttal. Nem arról, hol alacsonyak a pontszámok, hanem arról, hová szeretnél eljutni, és mi fontos neked.",
        "about.step3.title": "Tegyél egy kis lépést",
        "about.step3.text": "Válassz egy kis lépést, amelyet te magad megtehetsz, és gondold végig, ki vagy mi tudna támogatni. Amikor a pókháló egyik pontja elmozdul, más pontok is elmozdulnak.",
        "about.who": "A párbeszédeszközök három változatban léteznek – felnőtteknek, serdülőknek és fiatal felnőtteknek, valamint gyermekeknek –, így mindenki, körülbelül 8 éves kortól, kitöltheti a saját pókhálóját. A hivatalos eszközök több mint tíz nyelven jelentek meg, és egy online változat is elérhető a mypositivehealth.com oldalon.\n\nA Positive Health Hollandiában indult, és ma már nemzetközileg használják, a háziorvosi rendelőktől és kórházaktól az iskolákig, munkahelyekig és egész régiókig. Négy szinten alkalmazzák: egyének önmaguk számára, szakemberek a mindennapi munkájukban, közösségek, valamint az egészségügyi rendszer egésze – a betegségközpontú ellátástól az egészségközpontú ellátás felé történő változás motorjaként.",
        "about.movement": "A Positive Health nemcsak eszköz, hanem mozgalom is – egy másfajta gondolkodás-, cselekvés-, szervezés- és finanszírozásmód az ellátásban. Rendszerint néhány elkötelezett emberrel és helyi partnerrel kezdődik, akik közös víziót osztanak, majd szélesebb koalíciókká nő. A megvalósítás módja országonként és kultúránként eltér, de az alapvíziója változatlan marad. Az elmúlt évtizedben Hollandiában számos területen gyökeret vert, és most nemzetközileg terjed.\n\nA lényege az elfordulás a „javítási reflextől” – a panasz kijavítására irányuló automatikus késztetéstől – az emberek megerősítése felé, hogy felismerjék, mit tehetnek ők maguk azért, hogy céltudatos, értelmes életet éljenek.",
        "about.value": "Az ellátásban a Positive Health arra törekszik, amit „Quadruple Aim” néven ismernek:\n\n• A népesség egészségének javítása\n• Az emberek ellátással kapcsolatos élményének javítása\n• A költségek csökkentése\n• Az ellátó csapatok és szakemberek jóllétének javítása\n\nEzek együtt egy elmozdulást írnak le a betegségközpontú ellátástól az egészségközpontú ellátás felé – olyan ellátás felé, amely abból indul ki, ami az embernek számít, nem csupán abból, hogy mi a baj vele.",
        "about.resources": "A pókhálón túl a Positive Health International és az institute for Positive Health (iPH) további módokat kínál az elmélyülésre:\n\n• Az online pókháló a mypositivehealth.com oldalon, a digitális kitöltéshez.\n• Egy e-learning modul, „The Essence of Positive Health”, bevezetésként.\n• Egy átfogó útmutatót tartalmazó kézikönyv.\n• Ingyenes letöltések és anyagok emberek és szakemberek számára.\n\nEz az alkalmazás egy független, személyes társ, amely lehetővé teszi, hogy a pókhálót a saját eszközödön töltsd ki; a fenti források jelentik a forrást és a helyet, ahol többet tanulhatsz.",
        "about.link.phi": "Positive Health International – párbeszédeszközök",
        "about.link.iph": "Institute for Positive Health (iPH)",
        "about.link.online": "My Positive Health – hivatalos online pókháló",
        "about.source": "Az ebben az alkalmazásban szereplő párbeszédeszköz-tartalom (dimenziók, szempontok és beszélgetéskérdések) © iPH/PHi. Az angol megfogalmazás a Positive Health International hivatalos angol eszközeiből származik, az institute for Positive Health (iPH) közreműködésével. A más nyelvekre való fordítások nem hivatalosak, és ehhez az alkalmazáshoz készültek. A magyarázó szövegek mindkét szervezet nyilvános információit foglalják össze.\n\nEz az alkalmazás személyes használatra szolgáló társ. Nem orvostechnikai eszköz, és nem nyújt diagnózist vagy orvosi tanácsot. A válaszaidat kizárólag ezen az eszközön tároljuk.",
        "dimexpl.body": "Ahogyan a tested érez és működik – egészségesnek és fittnek érezni magad, aludni, enni, mozogni, valamint panaszoktól vagy fájdalomtól mentesnek lenni.",
        "dimexpl.mind": "A belső világod – emlékezni és összpontosítani, kezelni az érzéseidet, elfogadni önmagad és irányban érezni magad.",
        "dimexpl.meaning": "Cél és irány – értelmes élet, életkedv, eszmények és álmok, bizalom, elfogadás és hála.",
        "dimexpl.quality": "Ahogyan megéled az életedet – öröm, boldogság, egyensúly, biztonság, valamint körülmények, mint a lakhatás és a pénz.",
        "dimexpl.participation": "A kapcsolatod másokkal – társas kapcsolatok, komolyan vétel, valahová tartozás, támogatás és értelmes dolgok közös csinálása.",
        "dimexpl.daily": "A mindennapi élet kezelése – gondoskodni önmagadról, munka vagy tanulás, ismerni a határaidat, és segítséget tudni kérni.",
        "adult.body": "Testi működés",
        "adult.mind": "Lelki jóllét",
        "adult.meaning": "Értelmesség",
        "adult.quality": "Életminőség",
        "adult.participation": "Részvétel",
        "adult.daily": "Mindennapi működés",
        "adolescent.body": "A testem",
        "adolescent.mind": "Az érzéseim és gondolataim",
        "adolescent.meaning": "Értelmesség",
        "adolescent.quality": "Életminőség",
        "adolescent.participation": "Részvétel",
        "adolescent.daily": "Mindennapi élet",
        "child.body": "A testem",
        "child.mind": "Az érzéseim és gondolataim",
        "child.meaning": "Most és a jövőben",
        "child.quality": "Jól érzed magad a bőrödben",
        "child.participation": "Részvétel",
        "child.daily": "Mindennapi élet",
        "adult.body.1": "Egészségesnek érezni magad",
        "adult.body.2": "Fittnek érezni magad",
        "adult.body.3": "Nincs testi panasz vagy fájdalom",
        "adult.body.4": "Alvás",
        "adult.body.5": "Táplálkozás",
        "adult.body.6": "Szexualitás",
        "adult.body.7": "Fizikai állapot",
        "adult.body.8": "Testmozgás",
        "adult.mind.1": "Emlékezni tudni a dolgokra",
        "adult.mind.2": "Tudni összpontosítani",
        "adult.mind.3": "Tudni kommunikálni",
        "adult.mind.4": "Derűsnek lenni",
        "adult.mind.5": "Elfogadni önmagad",
        "adult.mind.6": "Meg tudni birkózni a változással",
        "adult.mind.7": "Irányban érezni magad",
        "adult.meaning.1": "Értelmes életet élni",
        "adult.meaning.2": "Életkedvet érezni",
        "adult.meaning.3": "Eszmények követése",
        "adult.meaning.4": "Bizakodónak lenni",
        "adult.meaning.5": "Elfogadni az életet",
        "adult.meaning.6": "Hálásnak lenni",
        "adult.meaning.7": "Egész életen át tartó tanulás",
        "adult.quality.1": "Öröm",
        "adult.quality.2": "Boldognak lenni",
        "adult.quality.3": "Jól érezni magad",
        "adult.quality.4": "Kiegyensúlyozottnak érezni magad",
        "adult.quality.5": "Biztonságban érezni magad",
        "adult.quality.6": "Bensőségesség",
        "adult.quality.7": "Lakhatási körülmények",
        "adult.quality.8": "Elegendő pénz",
        "adult.participation.1": "Társas kapcsolatok",
        "adult.participation.2": "Komolyan vétel",
        "adult.participation.3": "Jó dolgok közös csinálása",
        "adult.participation.4": "Mások támogatásának megléte",
        "adult.participation.5": "Valahová tartozás érzése",
        "adult.participation.6": "Értelmes dolgok csinálása",
        "adult.participation.7": "Érdeklődés a társadalom iránt",
        "adult.daily.1": "Gondoskodni önmagadról",
        "adult.daily.2": "Ismerni a határaidat",
        "adult.daily.3": "Egészséggel kapcsolatos ismeretek",
        "adult.daily.4": "Az idő beosztása",
        "adult.daily.5": "A pénz kezelése",
        "adult.daily.6": "Tudni dolgozni",
        "adult.daily.7": "Tudni segítséget kérni",
        "adolescent.body.1": "Egészségesnek érezni magad",
        "adolescent.body.2": "Energikusnak lenni",
        "adolescent.body.3": "Nincs testi panasz vagy fájdalom",
        "adolescent.body.4": "Egészségesen táplálkozni",
        "adolescent.body.5": "Alvás",
        "adolescent.body.6": "Erőnlét",
        "adolescent.body.7": "Sport és testmozgás",
        "adolescent.body.8": "Külső megjelenés",
        "adolescent.mind.1": "Összpontosítás",
        "adolescent.mind.2": "Az érzéseid kezelése",
        "adolescent.mind.3": "Pozitívan viszonyulni az élethez",
        "adolescent.mind.4": "Elfogadni önmagad",
        "adolescent.mind.5": "Önbizalom",
        "adolescent.mind.6": "Megbirkózni a változással",
        "adolescent.mind.7": "Irányban lenni",
        "adolescent.meaning.1": "Értelmes életet élni",
        "adolescent.meaning.2": "Bizalommal tekinteni a jövőbe",
        "adolescent.meaning.3": "Életkedvet érezni",
        "adolescent.meaning.4": "Célok és álmok",
        "adolescent.meaning.5": "Döntéseket hozni",
        "adolescent.meaning.6": "Elfogadni a helyzeteket",
        "adolescent.meaning.7": "Hála",
        "adolescent.quality.1": "Boldogság",
        "adolescent.quality.2": "Öröm",
        "adolescent.quality.3": "Megélni az egyensúlyt",
        "adolescent.quality.4": "Biztonságban érezni magad",
        "adolescent.quality.5": "Kellemes környezet",
        "adolescent.quality.6": "Lakhatás és lakókörnyezet",
        "adolescent.quality.7": "Kijönni a pénzből",
        "adolescent.participation.1": "Társas kapcsolatok",
        "adolescent.participation.2": "Komolyan vétel",
        "adolescent.participation.3": "Jó dolgok csinálása másokkal",
        "adolescent.participation.4": "Valahová tartozás",
        "adolescent.participation.5": "Önkifejezés",
        "adolescent.participation.6": "Értelmes kapcsolatok",
        "adolescent.participation.7": "Támogatás és megértés kapása másoktól",
        "adolescent.daily.1": "Gondoskodni önmagadról",
        "adolescent.daily.2": "Tudni dolgozni vagy tanulni",
        "adolescent.daily.3": "Ismerni a határaidat",
        "adolescent.daily.4": "Egészséggel kapcsolatos ismeretek",
        "adolescent.daily.5": "Tervezési képesség",
        "adolescent.daily.6": "Tudni segítséget kérni",
        "adolescent.daily.7": "Nincs dohányzás, alkohol vagy drog",
        "child.body.1": "Jól érezni magad",
        "child.body.2": "Energikusnak lenni",
        "child.body.3": "Egészségesen táplálkozni",
        "child.body.4": "Jól aludni",
        "child.body.5": "Sport és testmozgás",
        "child.body.6": "Nincs testi panasz",
        "child.body.7": "Nincs fájdalom",
        "child.body.8": "Külső megjelenés",
        "child.mind.1": "Az érzéseid kezelése",
        "child.mind.2": "Elfogadni önmagad",
        "child.mind.3": "Beilleszkedni",
        "child.mind.4": "Pozitívan viszonyulni az élethez",
        "child.mind.5": "Ismerni a határaidat",
        "child.mind.6": "Megbirkózni a nehézségekkel",
        "child.meaning.1": "A jövőbe tekinteni",
        "child.meaning.2": "Kultúra és vallás",
        "child.meaning.3": "Célok és álmok",
        "child.meaning.4": "Döntéseket hozni",
        "child.meaning.5": "Önismeret",
        "child.meaning.6": "Példaképek",
        "child.quality.1": "Öröm",
        "child.quality.2": "Boldogság",
        "child.quality.3": "Derű",
        "child.quality.4": "Kellemes környezet",
        "child.quality.5": "Örömet lelni a tevékenységekben",
        "child.quality.6": "Támogatás és megértés kapása másoktól",
        "child.participation.1": "Barátok",
        "child.participation.2": "Valahová tartozás",
        "child.participation.3": "Zaklatás",
        "child.participation.4": "Önrendelkezés",
        "child.participation.5": "Lépést tartani a többiekkel",
        "child.participation.6": "Személyes hozzájárulás",
        "child.daily.1": "Iskolába járni",
        "child.daily.2": "Önmagad lenni",
        "child.daily.3": "Szabadidő",
        "child.daily.4": "Gondoskodni önmagadról",
        "child.daily.5": "Normálisnak érezni magad",
        "child.daily.6": "Korlátok",
        "child.daily.7": "Nincs dohányzás, alkohol- vagy drogfogyasztás",
    ]
}
