import Foundation

// Unofficial translation generated for this app — NOT the official Positive Health wording.
enum Icelandic {
    static let table: [String: String] = [
        "done": "Lokið",
        "cancel": "Hætta við",
        "back": "Til baka",
        "next": "Áfram",
        "app_title": "Mín jákvæða heilsa",
        "fill_menu": "Fylltu út köngulóarvefinn",
        "empty_title": "Fylltu út köngulóarvefinn þinn",
        "empty_desc": "Positive Health horfir á það sem skiptir þig máli, í sex víddum heilsu. Fylltu út köngulóarvefinn til að fá persónulegt yfirlit — upphafspunkt fyrir öðruvísi samtal.",
        "version.adult.title": "Fullorðnir",
        "version.adolescent.title": "Unglingar / ungt fullorðið fólk",
        "version.child.title": "Börn",
        "version.adult.age": "18+ ára",
        "version.adolescent.age": "16–25 ára",
        "version.child.age": "8–16 ára",
        "reflect.adult": "Eitthvað sem skiptir mig máli vantar:",
        "reflect.adolescent": "Eftirfarandi skiptir mig sérstaklega miklu máli",
        "reflect.child": "Eftirfarandi skiptir mig sérstaklega miklu máli",
        "q.how_feel": "Hvernig líður þér með þetta? Það eru engin rétt eða röng svör.",
        "q.include12": "Hafa með spurningar fyrir 12 ára og eldri",
        "q.almost_done": "Næstum búið",
        "q.write_here": "Skrifaðu það hér…",
        "q.save_footer": "Þegar þú vistar birtist persónulegt yfirlit þitt í köngulóarvefnum. Mundu: þetta er ekki próf og það er engin viðmiðun — þetta er þín eigin mynd af þessari stundu og upphafspunktur fyrir samtal.",
        "q.show_web": "Sýna köngulóarvefinn minn",
        "r.compare": "Bera saman við fyrra",
        "r.no_norm_footer": "Það er engin viðmiðun og engin einkunn til að ná. Þetta er þín eigin mynd af þessari stundu.",
        "r.my_dimensions": "Víddirnar mínar",
        "r.other_conversation": "Hitt samtalið",
        "r.other_footer": "Það skiptir ekki máli hvar þú byrjar — það sem skiptir máli er að þú byrjir og að þú takir lítil skref. Þegar einn punktur hreyfist hreyfast aðrir punktar líka.",
        "r.your_answer": "Svarið þitt…",
        "conv.attention": "Er eitthvað sem þú vildir gefa meiri athygli, eða vildir breyta?",
        "conv.step": "Hvaða lítið skref gætir þú sjálf/ur tekið?",
        "conv.support": "Hver eða hvað gæti stutt þig í þessu?",
        "settings.title": "Stillingar",
        "settings.language": "Tungumál",
        "settings.language_footer": "Enska notar opinbert orðalag Positive Health verkfæranna. Önnur tungumál eru óopinberar þýðingar gerðar fyrir þetta app.",
        "about.title": "Um Positive Health",
        "about.s.whatisit": "Hvað er Positive Health?",
        "about.s.origin": "Hvaðan kemur það?",
        "about.s.dimensions": "Víddirnar sex",
        "about.s.spiderweb": "Köngulóarvefurinn",
        "about.s.conversation": "Hitt samtalið",
        "about.s.steps": "Hvernig það virkar — þrjú skref",
        "about.s.who": "Fyrir hverja er það?",
        "about.s.movement": "Hreyfing, ekki bara verkfæri",
        "about.s.value": "Gildið sem stefnt er að",
        "about.s.resources": "Meira efni",
        "about.s.versions": "Útgáfur í þessu appi",
        "about.s.learnmore": "Fræðast meira",
        "about.whatisit": "Positive Health er víðtæk sýn á heilsu sem var þróuð í Hollandi. Í stað þess að skilgreina heilsu sem fjarveru sjúkdóms, horfir hún á fólk sem heilar manneskjur: á seiglu þeirra — hæfnina til að takast á við líkamlegar, tilfinningalegar og félagslegar áskoranir lífsins — og á það sem gerir líf þeirra merkingarbært. Miðlæga spurningin færist frá „Hvað er að hjá þér?“ yfir í „Hvað skiptir þig máli?“\n\nÞað er ekki meðferð eða próf. Það er leið til að horfa, íhugunarverkfæri og samtalskveikja sem hjálpar þér að vera áfram við stjórnvölinn í þínu eigin lífi þar sem því verður við komið.",
        "about.quote": "Ég er sannfærð um að af öllum þeim öflum sem efla heilsu sé merkingarbærni það sterkasta.",
        "about.quote_author": "Machteld Huber, stofnandi Positive Health",
        "about.origin": "Positive Health var sett á laggirnar af Machteld Huber, fyrrverandi hollenskum heimilislækni og rannsakanda. Eftir að hafa sjálf veikst alvarlega tók hún eftir því hversu mikil áhrif hennar eigin viðhorf og tilfinning fyrir stefnu hafði á bata hennar — eitthvað sem ríkjandi sýn á heilsu hafði ekkert rými fyrir.\n\nSkilgreining Alþjóðaheilbrigðismálastofnunarinnar frá 1948 lýsir heilsu sem ástandi fullkominnar líkamlegrar, andlegrar og félagslegrar vellíðunar. Huber og samstarfsfólk hennar færðu rök fyrir því í British Medical Journal (2011) að þessi hugsjón um „fullkomna vellíðan“ sé kyrrstæð og óaðgengileg — samkvæmt þeim mælikvarða er nánast enginn heilbrigður, síst af öllu fólk sem lifir með langvinnt ástand. Þau lögðu til kvikan valkost: heilsu sem hæfnina til að aðlagast og stýra sjálfum sér frammi fyrir áskorunum lífsins.\n\nTil að komast að því hvað heilsa þýðir fyrir fólk sjálft tók teymi Huber svo viðtöl við sjúklinga, umönnunarfólk og rannsakendur. Hundruð heilsuvísa sem komu út úr þessari rannsókn voru flokkuð í sex meginvíddir — ásana sex í köngulóarvefnum. Rannsóknin byggir einnig á eldri innsýn: salútógenesu Aaron Antonovsky (rannsókn á því sem skapar heilsu frekar en því sem veldur sjúkdómi) og Blue Zones, svæðum þar sem fólk verður gamalt við ótrúlega góða heilsu.",
        "about.spiderweb": "Þú fyllir sjálf/ur út spurningalistann og gefur hverjum þætti einkunn frá 0 til 10. Svörin þín eru teiknuð sem þitt persónulega heilsuyfirborð í köngulóarvefnum. Það er engin viðmiðun og ekkert til að standast eða falla á: vefurinn sýnir hvernig þú upplifir heilsu þína á þessari stundu, í öllum sex víddunum — mynd sem er mun ríkari en ein einasta tala.\n\nAð fylla hann út er oft augnopnun í sjálfu sér: heilsa reynist ekki bara vera líkami þinn og skap, heldur líka merking, þátttaka, lífsgæði og hvernig þú ræður við dagana þína.",
        "about.conversation": "Köngulóarvefurinn er upphafspunktur þess sem Positive Health kallar „hitt samtalið“ — við lækni, hjúkrunarfræðing, þjálfara, félagsráðgjafa eða einhvern sem þú treystir. Samtalið víkkar fyrst út (horfir á allan vefinn, ekki bara eina kvörtun) og þrengist svo að því sem raunverulega skiptir þig máli. Það snýst ekki um lægstu einkunnirnar; þú velur hverju þú vilt gefa athygli.\n\nSlík samtöl taka reglulega óvæntar stefnur: það sem einhver kom fyrst með reynist ekki vera það sem hann vill helst vinna með. Fólk veit yfirleitt nú þegar hvað þarf — vefurinn hjálpar til við að segja það upphátt.\n\nÞaðan er nálgunin vísvitandi smá: veldu eitt lítið skref sem þú getur sjálf/ur tekið og hugsaðu um hver eða hvað gæti stutt þig. Þegar einn punktur vefsins hreyfist eiga aðrir punktar til að hreyfast líka.",
        "about.step1.title": "Fylltu út köngulóarvefinn",
        "about.step1.text": "Gefðu einkunn fyrir hvernig þér líður með hvern þátt, frá 0 til 10. Það tekur aðeins nokkrar mínútur. Það er engin viðmiðun — þetta er persónulegt mat á þessari stundu.",
        "about.step2.title": "Taktu hitt samtalið",
        "about.step2.text": "Notaðu köngulóarvefinn þinn sem samtalskveikju — við lækni, hjúkrunarfræðing, félagsráðgjafa, þjálfara eða vin. Ekki um hvar einkunnir eru lágar, heldur um hvert þú vilt stefna og hvað skiptir þig máli.",
        "about.step3.title": "Taktu lítið skref",
        "about.step3.text": "Veldu eitt lítið skref sem þú getur sjálf/ur tekið og hugsaðu um hver eða hvað gæti stutt þig. Þegar einn punktur vefsins hreyfist hreyfast aðrir punktar líka.",
        "about.who": "Samtalsverkfærin eru til í þremur útgáfum — fyrir fullorðna, fyrir unglinga og ungt fullorðið fólk, og fyrir börn — svo að allir frá um það bil 8 ára aldri geti fyllt út sinn eigin vef. Opinberu verkfærin eru gefin út á fleiri en tíu tungumálum og netútgáfa er í boði á mypositivehealth.com.\n\nPositive Health hófst í Hollandi og er nú notað á alþjóðavettvangi, allt frá heilsugæslustöðvum og sjúkrahúsum til skóla, vinnustaða og heilla svæða. Það er beitt á fjórum stigum: af einstaklingum fyrir þá sjálfa, af fagfólki í daglegu starfi, af samfélögum og í heilbrigðiskerfinu í heild — sem drifkraftur breytinga frá sjúkdómsmiðaðri yfir í heilsumiðaða umönnun.",
        "about.movement": "Positive Health er ekki aðeins verkfæri heldur hreyfing — önnur leið til að hugsa, gera, skipuleggja og fjármagna umönnun. Það byrjar yfirleitt með fáeinum staðföstum einstaklingum og staðbundnum samstarfsaðilum sem deila sýn og vex í víðtækari bandalög. Leiðin sem það er innleitt er ólík eftir löndum og menningu, en kjarnasýnin er sú sama. Það hefur skotið rótum á mörgum sviðum í Hollandi á síðasta áratug og breiðist nú út á alþjóðavettvangi.\n\nÍ hjarta þess er færsla frá „viðgerðarviðbragðinu“ — sjálfvirku hvötinni til að laga kvörtun — yfir í að efla fólk til að þekkja hvað það sjálft getur gert til að lifa tilgangsríku, merkingarbæru lífi.",
        "about.value": "Í umönnun stefnir Positive Health að því sem er þekkt sem „Quadruple Aim“:\n\n• Að bæta heilsu íbúa\n• Að bæta upplifun fólks af umönnun\n• Að draga úr kostnaði\n• Að bæta líðan umönnunarteyma og fagfólks\n\nSaman lýsa þessi atriði færslu frá sjúkdómsmiðaðri umönnun yfir í heilsumiðaða umönnun — umönnun sem gengur út frá því sem skiptir manneskju máli, ekki aðeins frá því sem er að hjá henni.",
        "about.resources": "Fyrir utan köngulóarvefinn bjóða Positive Health International og institute for Positive Health (iPH) upp á fleiri leiðir til að fara dýpra:\n\n• Köngulóarvefinn á netinu á mypositivehealth.com, til að fylla hann út stafrænt.\n• Rafræna námseiningu, „The Essence of Positive Health“, sem kynningu.\n• Handbók með ítarlegum leiðbeiningum.\n• Ókeypis niðurhal og efni fyrir fólk og fagfólk.\n\nÞetta app er sjálfstæður persónulegur fylgifélagi sem gerir þér kleift að fylla út köngulóarvefinn í tækinu þínu; efnið hér að ofan er uppruninn og staðurinn til að fræðast meira.",
        "about.link.phi": "Positive Health International — samtalsverkfæri",
        "about.link.iph": "Institute for Positive Health (iPH)",
        "about.link.online": "My Positive Health — opinberi köngulóarvefurinn á netinu",
        "about.source": "Efni samtalsverkfærisins í þessu appi (víddir, þættir og samtalsspurningar) er © iPH/PHi. Enska orðalagið er endurgefið úr opinberu ensku verkfærunum frá Positive Health International í samstarfi við institute for Positive Health (iPH). Þýðingar á önnur tungumál eru óopinberar og voru gerðar fyrir þetta app. Skýringartextarnir taka saman opinberar upplýsingar beggja stofnananna.\n\nÞetta app er fylgifélagi til persónulegra nota. Það er ekki lækningatæki og veitir hvorki sjúkdómsgreiningar né læknisráð. Svörin þín eru aðeins geymd í þessu tæki.",
        "dimexpl.body": "Hvernig líkaminn þinn líður og starfar — að finnast þú heilbrigð/ur og hress, sofa, borða, hreyfa þig og vera laus við kvartanir eða verki.",
        "dimexpl.mind": "Innra líf þitt — að muna og einbeita þér, ráða við tilfinningar þínar, sætta þig við sjálfa/n þig og finnast þú hafa stjórn.",
        "dimexpl.meaning": "Tilgangur og stefna — merkingarbært líf, lífsgleði, hugsjónir og draumar, sjálfstraust, sátt og þakklæti.",
        "dimexpl.quality": "Hvernig þú upplifir líf þitt — ánægja, hamingja, jafnvægi, öryggi og aðstæður eins og húsnæði og peningar.",
        "dimexpl.participation": "Tengsl þín við aðra — félagsleg samskipti, að vera tekin/n alvarlega, að tilheyra, stuðningur og að gera merkingarbæra hluti saman.",
        "dimexpl.daily": "Að ráða við daglegt líf — að hugsa um sjálfa/n þig, vinnu eða nám, að þekkja mörk þín og að geta beðið um hjálp.",
        "adult.body": "Líkamsstarfsemi",
        "adult.mind": "Andleg vellíðan",
        "adult.meaning": "Merkingarbærni",
        "adult.quality": "Lífsgæði",
        "adult.participation": "Þátttaka",
        "adult.daily": "Dagleg færni",
        "adolescent.body": "Líkaminn minn",
        "adolescent.mind": "Tilfinningar mínar og hugsanir",
        "adolescent.meaning": "Merkingarbærni",
        "adolescent.quality": "Lífsgæði",
        "adolescent.participation": "Þátttaka",
        "adolescent.daily": "Daglegt líf",
        "child.body": "Líkaminn minn",
        "child.mind": "Tilfinningar mínar og hugsanir",
        "child.meaning": "Núna og í framtíðinni",
        "child.quality": "Að líða vel með sjálfa/n þig",
        "child.participation": "Þátttaka",
        "child.daily": "Daglegt líf",
        "adult.body.1": "Að finnast þú heilbrigð/ur",
        "adult.body.2": "Að finnast þú hress",
        "adult.body.3": "Engar líkamlegar kvartanir eða verkir",
        "adult.body.4": "Svefn",
        "adult.body.5": "Að borða",
        "adult.body.6": "Kynlíf",
        "adult.body.7": "Líkamlegt ástand",
        "adult.body.8": "Hreyfing",
        "adult.mind.1": "Að geta munað hluti",
        "adult.mind.2": "Að geta einbeitt þér",
        "adult.mind.3": "Að geta tjáð þig",
        "adult.mind.4": "Að vera kát/ur",
        "adult.mind.5": "Að sætta þig við sjálfa/n þig",
        "adult.mind.6": "Að geta ráðið við breytingar",
        "adult.mind.7": "Að finnast þú hafa stjórn",
        "adult.meaning.1": "Að lifa merkingarbæru lífi",
        "adult.meaning.2": "Að hafa lífsgleði",
        "adult.meaning.3": "Að fylgja hugsjónum eftir",
        "adult.meaning.4": "Að hafa sjálfstraust",
        "adult.meaning.5": "Að sætta þig við lífið",
        "adult.meaning.6": "Að vera þakklát/ur",
        "adult.meaning.7": "Símenntun",
        "adult.quality.1": "Ánægja",
        "adult.quality.2": "Að vera hamingjusöm/samur",
        "adult.quality.3": "Að líða vel",
        "adult.quality.4": "Að vera í góðu jafnvægi",
        "adult.quality.5": "Að finnast þú örugg/ur",
        "adult.quality.6": "Nánd",
        "adult.quality.7": "Húsnæðisaðstæður",
        "adult.quality.8": "Að hafa nóg af peningum",
        "adult.participation.1": "Félagsleg samskipti",
        "adult.participation.2": "Að vera tekin/n alvarlega",
        "adult.participation.3": "Að gera skemmtilega hluti saman",
        "adult.participation.4": "Að hafa stuðning frá öðrum",
        "adult.participation.5": "Tilfinning um að tilheyra",
        "adult.participation.6": "Að gera merkingarbæra hluti",
        "adult.participation.7": "Að hafa áhuga á samfélaginu",
        "adult.daily.1": "Að hugsa um sjálfa/n þig",
        "adult.daily.2": "Að þekkja takmörk þín",
        "adult.daily.3": "Þekking á heilsu",
        "adult.daily.4": "Að stýra tíma",
        "adult.daily.5": "Að stýra peningum",
        "adult.daily.6": "Að geta unnið",
        "adult.daily.7": "Að geta beðið um hjálp",
        "adolescent.body.1": "Að finnast þú heilbrigð/ur",
        "adolescent.body.2": "Að hafa orku",
        "adolescent.body.3": "Engar líkamlegar kvartanir eða verkir",
        "adolescent.body.4": "Að borða hollt",
        "adolescent.body.5": "Svefn",
        "adolescent.body.6": "Líkamshreysti",
        "adolescent.body.7": "Íþróttir og hreyfing",
        "adolescent.body.8": "Útlit",
        "adolescent.mind.1": "Einbeiting",
        "adolescent.mind.2": "Að ráða við tilfinningar þínar",
        "adolescent.mind.3": "Að vera jákvæð/ur gagnvart lífinu",
        "adolescent.mind.4": "Að sætta þig við sjálfa/n þig",
        "adolescent.mind.5": "Trú á sjálfa/n þig",
        "adolescent.mind.6": "Að takast á við breytingar",
        "adolescent.mind.7": "Að hafa stjórn",
        "adolescent.meaning.1": "Að lifa merkingarbæru lífi",
        "adolescent.meaning.2": "Að hafa trú á framtíðinni",
        "adolescent.meaning.3": "Að hafa lífsgleði",
        "adolescent.meaning.4": "Að hafa markmið og drauma",
        "adolescent.meaning.5": "Að taka ákvarðanir",
        "adolescent.meaning.6": "Að sætta þig við aðstæður",
        "adolescent.meaning.7": "Þakklæti",
        "adolescent.quality.1": "Hamingja",
        "adolescent.quality.2": "Ánægja",
        "adolescent.quality.3": "Að upplifa jafnvægi",
        "adolescent.quality.4": "Að finnast þú örugg/ur",
        "adolescent.quality.5": "Notalegt umhverfi",
        "adolescent.quality.6": "Húsnæði og búsetuumhverfi",
        "adolescent.quality.7": "Að láta enda ná saman",
        "adolescent.participation.1": "Félagsleg samskipti",
        "adolescent.participation.2": "Að vera tekin/n alvarlega",
        "adolescent.participation.3": "Að gera skemmtilega hluti með öðru fólki",
        "adolescent.participation.4": "Að tilheyra",
        "adolescent.participation.5": "Sjálfstjáning",
        "adolescent.participation.6": "Merkingarbær sambönd",
        "adolescent.participation.7": "Að fá stuðning og skilning frá öðrum",
        "adolescent.daily.1": "Að hugsa um sjálfa/n þig",
        "adolescent.daily.2": "Að geta unnið eða lært",
        "adolescent.daily.3": "Að þekkja takmörk þín",
        "adolescent.daily.4": "Þekking á heilsu",
        "adolescent.daily.5": "Hæfni til að skipuleggja",
        "adolescent.daily.6": "Að geta beðið um hjálp",
        "adolescent.daily.7": "Engar reykingar, áfengi eða fíkniefni",
        "child.body.1": "Að líða vel",
        "child.body.2": "Að hafa orku",
        "child.body.3": "Að borða hollt",
        "child.body.4": "Að sofa vel",
        "child.body.5": "Íþróttir og hreyfing",
        "child.body.6": "Engar líkamlegar kvartanir",
        "child.body.7": "Enginn verkur",
        "child.body.8": "Útlit",
        "child.mind.1": "Að ráða við tilfinningar þínar",
        "child.mind.2": "Að sætta þig við sjálfa/n þig",
        "child.mind.3": "Að falla inn í hópinn",
        "child.mind.4": "Að vera jákvæð/ur gagnvart lífinu",
        "child.mind.5": "Að þekkja takmörk þín",
        "child.mind.6": "Að takast á við mótlæti",
        "child.meaning.1": "Að horfa til framtíðar",
        "child.meaning.2": "Menning og trú",
        "child.meaning.3": "Að hafa markmið og drauma",
        "child.meaning.4": "Að taka ákvarðanir",
        "child.meaning.5": "Sjálfsþekking",
        "child.meaning.6": "Fyrirmyndir",
        "child.quality.1": "Ánægja",
        "child.quality.2": "Hamingja",
        "child.quality.3": "Kátína",
        "child.quality.4": "Notalegt umhverfi",
        "child.quality.5": "Að hafa gaman af því að gera hluti",
        "child.quality.6": "Að fá stuðning og skilning frá öðrum",
        "child.participation.1": "Vinir",
        "child.participation.2": "Að tilheyra",
        "child.participation.3": "Einelti",
        "child.participation.4": "Sjálfsákvörðun",
        "child.participation.5": "Að fylgja öðrum eftir",
        "child.participation.6": "Persónulegt framlag",
        "child.daily.1": "Að fara í skóla",
        "child.daily.2": "Að vera þú sjálf/ur",
        "child.daily.3": "Frítími",
        "child.daily.4": "Að hugsa um sjálfa/n þig",
        "child.daily.5": "Að finnast þú venjuleg/ur",
        "child.daily.6": "Takmarkanir",
        "child.daily.7": "Engar reykingar, áfengi eða fíkniefnanotkun",
    ]
}
