import Foundation

// Unofficial translation generated for this app — NOT the official Positive Health wording.
enum Italian {
    static let table: [String: String] = [
        "done": "Fatto",
        "cancel": "Annulla",
        "back": "Indietro",
        "next": "Avanti",
        "app_title": "La mia Salute Positiva",
        "fill_menu": "Compila la ragnatela",
        "empty_title": "Compila la tua ragnatela",
        "empty_desc": "La Salute Positiva guarda a ciò che conta per te, attraverso sei dimensioni della salute. Compila la ragnatela per ottenere il tuo quadro personale — un punto di partenza per un dialogo diverso.",
        "version.adult.title": "Adulti",
        "version.adolescent.title": "Adolescenti / giovani adulti",
        "version.child.title": "Bambini",
        "version.adult.age": "18+ anni",
        "version.adolescent.age": "16–25 anni",
        "version.child.age": "8–16 anni",
        "reflect.adult": "Manca qualcosa che è importante per me:",
        "reflect.adolescent": "Quanto segue è particolarmente importante per me",
        "reflect.child": "Quanto segue è particolarmente importante per me",
        "q.how_feel": "Come ti senti riguardo a questo? Non ci sono risposte giuste o sbagliate.",
        "q.include12": "Includi le domande per i 12 anni e oltre",
        "q.almost_done": "Ci siamo quasi",
        "q.write_here": "Scrivilo qui…",
        "q.save_footer": "Quando salvi, il tuo quadro personale appare nella ragnatela. Ricorda: non è un test e non c'è una norma — è la tua immagine di questo momento, e un punto di partenza per un dialogo.",
        "q.show_web": "Mostra la mia ragnatela",
        "r.compare": "Confronta con il precedente",
        "r.no_norm_footer": "Non c'è una norma né un punteggio da raggiungere. Questa è la tua immagine di questo momento.",
        "r.my_dimensions": "Le mie dimensioni",
        "r.other_conversation": "L'altro dialogo",
        "r.other_footer": "Non importa da dove parti — ciò che conta è che tu parta, e che tu faccia piccoli passi. Quando un punto si muove, si muovono anche gli altri.",
        "r.your_answer": "La tua risposta…",
        "conv.attention": "C'è qualcosa a cui vorresti dare più attenzione, o che vorresti cambiare?",
        "conv.step": "Quale piccolo passo potresti fare tu stesso?",
        "conv.support": "Chi o cosa potrebbe sostenerti in questo?",
        "settings.title": "Impostazioni",
        "settings.language": "Lingua",
        "settings.language_footer": "L'inglese utilizza la formulazione ufficiale degli strumenti Positive Health. Le altre lingue sono traduzioni non ufficiali realizzate per questa app.",
        "about.title": "Informazioni su Positive Health",
        "about.s.whatisit": "Che cos'è la Salute Positiva?",
        "about.s.origin": "Da dove viene?",
        "about.s.dimensions": "Le sei dimensioni",
        "about.s.spiderweb": "La ragnatela",
        "about.s.conversation": "L'altro dialogo",
        "about.s.steps": "Come funziona — tre passi",
        "about.s.who": "A chi è rivolta?",
        "about.s.movement": "Un movimento, non solo uno strumento",
        "about.s.value": "Il valore a cui mira",
        "about.s.resources": "Altre risorse",
        "about.s.versions": "Versioni in questa app",
        "about.s.learnmore": "Scopri di più",
        "about.whatisit": "La Salute Positiva è una visione ampia della salute sviluppata nei Paesi Bassi. Invece di definire la salute come assenza di malattia, guarda alle persone come esseri interi: alla loro capacità di recupero — la capacità di affrontare le sfide fisiche, emotive e sociali della vita — e a ciò che rende la loro vita significativa. La domanda centrale passa da “Qual è il tuo problema?” a “Che cosa conta per te?”\n\nNon è una cura né un test. È un modo di guardare, uno strumento di riflessione e un avvio al dialogo che ti aiuta a restare padrone della tua vita ovunque sia possibile.",
        "about.quote": "Sono convinta che, di tutte le forze che rafforzano la salute, il senso di significato sia la più potente.",
        "about.quote_author": "Machteld Huber, fondatrice della Salute Positiva",
        "about.origin": "La Salute Positiva è stata avviata da Machteld Huber, ex medico di famiglia e ricercatrice olandese. Dopo essersi ammalata gravemente lei stessa, ha notato quanto il proprio atteggiamento e senso di direzione influenzassero la sua guarigione — qualcosa a cui la visione prevalente della salute non lasciava spazio.\n\nLa definizione dell'Organizzazione Mondiale della Sanità del 1948 descrive la salute come uno stato di completo benessere fisico, mentale e sociale. Huber e i suoi colleghi hanno sostenuto sul British Medical Journal (2011) che questo ideale di “completo benessere” è statico e irraggiungibile — secondo quel criterio quasi nessuno è sano, tanto meno le persone che convivono con una condizione cronica. Hanno proposto un'alternativa dinamica: la salute come capacità di adattarsi e di gestirsi di fronte alle sfide della vita.\n\nPer scoprire che cosa significhi la salute per le persone stesse, il team di Huber ha poi intervistato pazienti, professionisti della cura e ricercatori. Le centinaia di indicatori di salute emersi da questo studio sono stati raggruppati in sei dimensioni principali — i sei assi della ragnatela. La ricerca si fonda anche su intuizioni più antiche: la salutogenesi di Aaron Antonovsky (lo studio di ciò che crea salute anziché di ciò che causa malattia) e le Blue Zones, regioni in cui le persone invecchiano in salute straordinariamente buona.",
        "about.spiderweb": "Compili il questionario tu stesso, dando a ogni aspetto un punteggio da 0 a 10. Le tue risposte vengono tracciate come la tua superficie personale della salute nella ragnatela. Non c'è una norma e non c'è nulla da superare o fallire: la ragnatela mostra come vivi la tua salute in questo momento, in tutte e sei le dimensioni — un quadro molto più ricco di un semplice numero.\n\nCompilarla è spesso una rivelazione di per sé: la salute si scopre essere non solo il corpo e l'umore, ma anche il senso, la partecipazione, la qualità della vita e come gestisci le tue giornate.",
        "about.conversation": "La ragnatela è il punto di partenza per ciò che la Salute Positiva chiama “l'altro dialogo” — con un medico, un infermiere, un coach, un assistente sociale o una persona di cui ti fidi. Il dialogo prima si allarga (guardando all'intera ragnatela, non a un solo disturbo) e poi si restringe verso ciò che conta davvero per te. Non riguarda i punteggi più bassi; sei tu a scegliere a cosa vuoi dare attenzione.\n\nQuesti dialoghi prendono spesso pieghe sorprendenti: ciò con cui una persona si è presentata all'inizio si rivela non essere la cosa su cui più desidera lavorare. Le persone di solito sanno già ciò che serve — la ragnatela aiuta a dirlo ad alta voce.\n\nDa lì, l'approccio è volutamente piccolo: scegli un piccolo passo che puoi fare tu stesso, e pensa a chi o cosa potrebbe sostenerti. Quando un punto della ragnatela si muove, tendono a muoversi anche gli altri.",
        "about.step1.title": "Compila la ragnatela",
        "about.step1.text": "Dai un punteggio a come ti senti riguardo a ciascun aspetto, da 0 a 10. Bastano pochi minuti. Non c'è una norma — è una valutazione personale di questo momento.",
        "about.step2.title": "Vivi l'altro dialogo",
        "about.step2.text": "Usa la tua ragnatela come avvio al dialogo — con un medico, un infermiere, un assistente sociale, un coach o un amico. Non su dove i punteggi sono bassi, ma su dove vuoi andare e su ciò che è importante per te.",
        "about.step3.title": "Fai un piccolo passo",
        "about.step3.text": "Scegli un piccolo passo che puoi fare tu stesso, e pensa a chi o cosa potrebbe sostenerti. Quando un punto della ragnatela si muove, si muovono anche gli altri.",
        "about.who": "Gli strumenti di dialogo esistono in tre versioni — per adulti, per adolescenti e giovani adulti, e per bambini — così che chiunque, a partire da circa 8 anni, possa compilare la propria ragnatela. Gli strumenti ufficiali sono pubblicati in più di dieci lingue, ed è disponibile una versione online su mypositivehealth.com.\n\nLa Salute Positiva è nata nei Paesi Bassi ed è oggi usata a livello internazionale, dagli ambulatori di medicina generale e gli ospedali fino alle scuole, ai luoghi di lavoro e a intere regioni. Viene applicata su quattro livelli: dalle persone per sé stesse, dai professionisti nel loro lavoro quotidiano, dalle comunità, e nel sistema sanitario nel suo complesso — come motore di cambiamento da una cura orientata alla malattia a una cura orientata alla salute.",
        "about.movement": "La Salute Positiva non è solo uno strumento, ma un movimento — un modo diverso di pensare, agire, organizzare e finanziare la cura. Di solito parte da poche persone impegnate e da partner locali che condividono una visione, e cresce fino a diventare coalizioni più ampie. Il modo in cui viene realizzata varia da paese a paese e da cultura a cultura, ma la visione di fondo rimane la stessa. Nell'ultimo decennio ha messo radici in molti ambiti nei Paesi Bassi e si sta ora diffondendo a livello internazionale.\n\nAl suo cuore c'è un allontanamento dal “riflesso di riparazione” — l'impulso automatico a risolvere un disturbo — verso il dare alle persone la capacità di riconoscere ciò che loro stesse possono fare per vivere una vita ricca di scopo e di significato.",
        "about.value": "Nella cura, la Salute Positiva mira a ciò che è noto come “Quadruple Aim”:\n\n• Migliorare la salute della popolazione\n• Migliorare l'esperienza di cura delle persone\n• Ridurre i costi\n• Migliorare il benessere delle équipe e dei professionisti della cura\n\nInsieme, questi obiettivi descrivono un passaggio da una cura orientata alla malattia a una cura orientata alla salute — una cura che parte da ciò che conta per una persona, non solo da ciò che non va in lei.",
        "about.resources": "Oltre alla ragnatela, Positive Health International e l'institute for Positive Health (iPH) offrono altri modi per approfondire:\n\n• La ragnatela online su mypositivehealth.com, per compilarla in formato digitale.\n• Un modulo e-learning, “The Essence of Positive Health”, come introduzione.\n• Un manuale con una guida completa.\n• Download e materiali gratuiti per persone e professionisti.\n\nQuesta app è un compagno personale indipendente che ti permette di compilare la ragnatela sul tuo dispositivo; le risorse qui sopra sono la fonte e il luogo per saperne di più.",
        "about.link.phi": "Positive Health International — strumenti di dialogo",
        "about.link.iph": "Institute for Positive Health (iPH)",
        "about.link.online": "My Positive Health — ragnatela online ufficiale",
        "about.source": "Il contenuto dello strumento di dialogo in questa app (dimensioni, aspetti e domande per il dialogo) è © iPH/PHi. La formulazione in inglese è riprodotta dagli strumenti ufficiali in inglese di Positive Health International in collaborazione con l'institute for Positive Health (iPH). Le traduzioni in altre lingue sono non ufficiali e sono state realizzate per questa app. I testi esplicativi riassumono le informazioni pubbliche di entrambe le organizzazioni.\n\nQuesta app è un compagno per uso personale. Non è un dispositivo medico e non fornisce diagnosi né consigli medici. Le tue risposte sono conservate solo su questo dispositivo.",
        "dimexpl.body": "Come il tuo corpo si sente e funziona — sentirti sano e in forma, dormire, mangiare, muoverti ed essere libero da disturbi o dolore.",
        "dimexpl.mind": "La tua vita interiore — ricordare e concentrarti, gestire le tue emozioni, accettarti e sentirti padrone di te.",
        "dimexpl.meaning": "Scopo e direzione — una vita significativa, voglia di vivere, ideali e sogni, fiducia, accettazione e gratitudine.",
        "dimexpl.quality": "Come vivi la tua vita — piacere, felicità, equilibrio, sicurezza, e circostanze come la casa e il denaro.",
        "dimexpl.participation": "Il tuo legame con gli altri — contatti sociali, essere preso sul serio, sentirti parte, sostegno, e fare insieme cose significative.",
        "dimexpl.daily": "Gestire la vita di ogni giorno — prenderti cura di te, lavoro o studio, conoscere i tuoi limiti ed essere in grado di chiedere aiuto.",
        "adult.body": "Funzioni corporee",
        "adult.mind": "Benessere mentale",
        "adult.meaning": "Senso di significato",
        "adult.quality": "Qualità della vita",
        "adult.participation": "Partecipazione",
        "adult.daily": "Funzionamento quotidiano",
        "adolescent.body": "Il mio corpo",
        "adolescent.mind": "Le mie emozioni e i miei pensieri",
        "adolescent.meaning": "Senso di significato",
        "adolescent.quality": "Qualità della vita",
        "adolescent.participation": "Partecipazione",
        "adolescent.daily": "Vita quotidiana",
        "child.body": "Il mio corpo",
        "child.mind": "Le mie emozioni e i miei pensieri",
        "child.meaning": "Ora e in futuro",
        "child.quality": "Stare bene con te stesso",
        "child.participation": "Partecipazione",
        "child.daily": "Vita quotidiana",
        "adult.body.1": "Sentirsi sani",
        "adult.body.2": "Sentirsi in forma",
        "adult.body.3": "Nessun disturbo fisico o dolore",
        "adult.body.4": "Dormire",
        "adult.body.5": "Mangiare",
        "adult.body.6": "Sessualità",
        "adult.body.7": "Condizione fisica",
        "adult.body.8": "Attività fisica",
        "adult.mind.1": "Riuscire a ricordare le cose",
        "adult.mind.2": "Riuscire a concentrarsi",
        "adult.mind.3": "Riuscire a comunicare",
        "adult.mind.4": "Essere di buon umore",
        "adult.mind.5": "Accettarsi",
        "adult.mind.6": "Riuscire a gestire il cambiamento",
        "adult.mind.7": "Sentirsi padroni di sé",
        "adult.meaning.1": "Avere una vita significativa",
        "adult.meaning.2": "Avere voglia di vivere",
        "adult.meaning.3": "Coltivare degli ideali",
        "adult.meaning.4": "Sentirsi sicuri di sé",
        "adult.meaning.5": "Accettare la vita",
        "adult.meaning.6": "Essere grati",
        "adult.meaning.7": "Imparare lungo tutta la vita",
        "adult.quality.1": "Piacere",
        "adult.quality.2": "Essere felici",
        "adult.quality.3": "Stare bene",
        "adult.quality.4": "Sentirsi in equilibrio",
        "adult.quality.5": "Sentirsi sicuri",
        "adult.quality.6": "Intimità",
        "adult.quality.7": "Condizioni abitative",
        "adult.quality.8": "Avere abbastanza denaro",
        "adult.participation.1": "Contatti sociali",
        "adult.participation.2": "Essere presi sul serio",
        "adult.participation.3": "Fare cose piacevoli insieme",
        "adult.participation.4": "Avere il sostegno degli altri",
        "adult.participation.5": "Senso di appartenenza",
        "adult.participation.6": "Fare cose significative",
        "adult.participation.7": "Interessarsi alla società",
        "adult.daily.1": "Prendersi cura di sé",
        "adult.daily.2": "Conoscere i propri limiti",
        "adult.daily.3": "Conoscenza della salute",
        "adult.daily.4": "Gestire il tempo",
        "adult.daily.5": "Gestire il denaro",
        "adult.daily.6": "Riuscire a lavorare",
        "adult.daily.7": "Riuscire a chiedere aiuto",
        "adolescent.body.1": "Sentirsi sani",
        "adolescent.body.2": "Avere energia",
        "adolescent.body.3": "Nessun disturbo fisico o dolore",
        "adolescent.body.4": "Mangiare in modo sano",
        "adolescent.body.5": "Dormire",
        "adolescent.body.6": "Forma fisica",
        "adolescent.body.7": "Sport e movimento",
        "adolescent.body.8": "Aspetto fisico",
        "adolescent.mind.1": "Concentrazione",
        "adolescent.mind.2": "Gestire le proprie emozioni",
        "adolescent.mind.3": "Sentirsi positivi verso la vita",
        "adolescent.mind.4": "Accettarsi",
        "adolescent.mind.5": "Fiducia in sé stessi",
        "adolescent.mind.6": "Affrontare il cambiamento",
        "adolescent.mind.7": "Sentirsi padroni di sé",
        "adolescent.meaning.1": "Condurre una vita significativa",
        "adolescent.meaning.2": "Avere fiducia nel futuro",
        "adolescent.meaning.3": "Avere voglia di vivere",
        "adolescent.meaning.4": "Avere obiettivi e sogni",
        "adolescent.meaning.5": "Fare delle scelte",
        "adolescent.meaning.6": "Accettare le situazioni",
        "adolescent.meaning.7": "Gratitudine",
        "adolescent.quality.1": "Felicità",
        "adolescent.quality.2": "Piacere",
        "adolescent.quality.3": "Vivere in equilibrio",
        "adolescent.quality.4": "Sentirsi sicuri",
        "adolescent.quality.5": "Un ambiente piacevole",
        "adolescent.quality.6": "Casa e ambiente di vita",
        "adolescent.quality.7": "Arrivare a fine mese",
        "adolescent.participation.1": "Contatti sociali",
        "adolescent.participation.2": "Essere presi sul serio",
        "adolescent.participation.3": "Fare cose piacevoli con altre persone",
        "adolescent.participation.4": "Appartenenza",
        "adolescent.participation.5": "Esprimersi",
        "adolescent.participation.6": "Relazioni significative",
        "adolescent.participation.7": "Ricevere sostegno e comprensione dagli altri",
        "adolescent.daily.1": "Prendersi cura di sé",
        "adolescent.daily.2": "Riuscire a lavorare o studiare",
        "adolescent.daily.3": "Conoscere i propri limiti",
        "adolescent.daily.4": "Conoscenza della salute",
        "adolescent.daily.5": "Capacità di pianificare",
        "adolescent.daily.6": "Riuscire a chiedere aiuto",
        "adolescent.daily.7": "Niente fumo, alcol o droghe",
        "child.body.1": "Stare bene",
        "child.body.2": "Avere energia",
        "child.body.3": "Mangiare in modo sano",
        "child.body.4": "Dormire bene",
        "child.body.5": "Sport e movimento",
        "child.body.6": "Nessun disturbo fisico",
        "child.body.7": "Niente dolore",
        "child.body.8": "Aspetto fisico",
        "child.mind.1": "Gestire le proprie emozioni",
        "child.mind.2": "Accettarsi",
        "child.mind.3": "Sentirsi integrati",
        "child.mind.4": "Sentirsi positivi verso la vita",
        "child.mind.5": "Conoscere i propri limiti",
        "child.mind.6": "Affrontare le difficoltà",
        "child.meaning.1": "Guardare al futuro",
        "child.meaning.2": "Cultura e religione",
        "child.meaning.3": "Avere obiettivi e sogni",
        "child.meaning.4": "Fare delle scelte",
        "child.meaning.5": "Conoscenza di sé",
        "child.meaning.6": "Modelli di riferimento",
        "child.quality.1": "Piacere",
        "child.quality.2": "Felicità",
        "child.quality.3": "Allegria",
        "child.quality.4": "Un ambiente piacevole",
        "child.quality.5": "Provare piacere nel fare le cose",
        "child.quality.6": "Ricevere sostegno e comprensione dagli altri",
        "child.participation.1": "Amici",
        "child.participation.2": "Appartenenza",
        "child.participation.3": "Bullismo",
        "child.participation.4": "Autodeterminazione",
        "child.participation.5": "Stare al passo con gli altri",
        "child.participation.6": "Contributo personale",
        "child.daily.1": "Andare a scuola",
        "child.daily.2": "Essere te stesso",
        "child.daily.3": "Tempo libero",
        "child.daily.4": "Prendersi cura di sé",
        "child.daily.5": "Sentirsi normali",
        "child.daily.6": "Limiti",
        "child.daily.7": "Niente fumo, alcol o uso di droghe",
    ]
}
