import Foundation

// Unofficial translation generated for this app — NOT the official Positive Health wording.
enum Norwegian {
    static let table: [String: String] = [
        "done": "Ferdig",
        "cancel": "Avbryt",
        "back": "Tilbake",
        "next": "Neste",
        "app_title": "Min Positive Health",
        "fill_menu": "Fyll ut spindelvevet",
        "empty_title": "Fyll ut ditt spindelvev",
        "empty_desc": "Positive Health ser på det som betyr noe for deg, på tvers av seks dimensjoner av helse. Fyll ut spindelvevet for å få din personlige oversikt – et utgangspunkt for en annerledes samtale.",
        "version.adult.title": "Voksne",
        "version.adolescent.title": "Ungdom / unge voksne",
        "version.child.title": "Barn",
        "version.adult.age": "18+ år",
        "version.adolescent.age": "16–25 år",
        "version.child.age": "8–16 år",
        "reflect.adult": "Noe som er viktig for meg mangler:",
        "reflect.adolescent": "Følgende er spesielt viktig for meg",
        "reflect.child": "Følgende er spesielt viktig for meg",
        "q.how_feel": "Hvordan har du det med dette? Det finnes ingen riktige eller gale svar.",
        "q.include12": "Ta med spørsmål for 12 år og eldre",
        "q.almost_done": "Nesten ferdig",
        "q.write_here": "Skriv det ned her…",
        "q.save_footer": "Når du lagrer, vises din personlige oversikt i spindelvevet. Husk: dette er ikke en test, og det finnes ingen norm – det er ditt eget bilde av dette øyeblikket, og et utgangspunkt for en samtale.",
        "q.show_web": "Vis spindelvevet mitt",
        "r.compare": "Sammenlign med tidligere",
        "r.no_norm_footer": "Det finnes ingen norm og ingen poengsum å nå. Dette er ditt eget bilde av dette øyeblikket.",
        "r.my_dimensions": "Mine dimensjoner",
        "r.other_conversation": "Den andre samtalen",
        "r.other_footer": "Det spiller ingen rolle hvor du begynner – det som betyr noe er at du begynner, og at du tar små skritt. Når ett punkt beveger seg, beveger andre punkter seg også.",
        "r.your_answer": "Ditt svar…",
        "conv.attention": "Er det noe du gjerne vil gi mer oppmerksomhet, eller ønsker å endre?",
        "conv.step": "Hvilket lite skritt kunne du ta selv?",
        "conv.support": "Hvem eller hva kunne støtte deg med dette?",
        "settings.title": "Innstillinger",
        "settings.language": "Språk",
        "settings.language_footer": "Engelsk bruker den offisielle ordlyden i verktøyene til Positive Health. De øvrige språkene er uoffisielle oversettelser laget for denne appen.",
        "about.title": "Om Positive Health",
        "about.s.whatisit": "Hva er Positive Health?",
        "about.s.origin": "Hvor kommer det fra?",
        "about.s.dimensions": "De seks dimensjonene",
        "about.s.spiderweb": "Spindelvevet",
        "about.s.conversation": "Den andre samtalen",
        "about.s.steps": "Slik fungerer det – tre steg",
        "about.s.who": "Hvem er det for?",
        "about.s.movement": "En bevegelse, ikke bare et verktøy",
        "about.s.value": "Verdien det sikter mot",
        "about.s.resources": "Flere ressurser",
        "about.s.versions": "Versjoner i denne appen",
        "about.s.learnmore": "Lær mer",
        "about.whatisit": "Positive Health er et bredt syn på helse som ble utviklet i Nederland. I stedet for å definere helse som fravær av sykdom, ser det på mennesker som hele personer: på deres motstandskraft – evnen til å håndtere livets fysiske, følelsesmessige og sosiale utfordringer – og på det som gjør livet deres meningsfullt. Det sentrale spørsmålet flyttes fra «Hva feiler det deg?» til «Hva betyr noe for deg?»\n\nDet er ikke en behandling eller en test. Det er en måte å se på, et refleksjonsverktøy og en samtalestarter som hjelper deg å beholde styringen over ditt eget liv der det er mulig.",
        "about.quote": "Jeg er overbevist om at av alle krefter som styrker helsen, er meningsfullhet den sterkeste.",
        "about.quote_author": "Machteld Huber, grunnlegger av Positive Health",
        "about.origin": "Positive Health ble startet av Machteld Huber, en tidligere nederlandsk allmennlege og forsker. Etter selv å ha blitt alvorlig syk, la hun merke til hvor mye hennes egen holdning og retningsfølelse påvirket tilfriskningen – noe det rådende synet på helse ikke hadde plass til.\n\nVerdens helseorganisasjons definisjon fra 1948 beskriver helse som en tilstand av fullstendig fysisk, mentalt og sosialt velvære. Huber og hennes kolleger hevdet i British Medical Journal (2011) at dette idealet om «fullstendig velvære» er statisk og uoppnåelig – etter den målestokken er nesten ingen friske, aller minst mennesker som lever med en kronisk tilstand. De foreslo et dynamisk alternativ: helse som evnen til å tilpasse seg og til å håndtere seg selv i møte med livets utfordringer.\n\nFor å finne ut hva helse betyr for menneskene selv, intervjuet Hubers team deretter pasienter, helsepersonell og forskere. De hundrevis av helseindikatorene som kom ut av denne studien ble gruppert i seks hoveddimensjoner – de seks aksene i spindelvevet. Forskningen bygger også på eldre innsikter: Aaron Antonovskys salutogenese (å studere hva som skaper helse i stedet for hva som forårsaker sykdom) og Blue Zones, regioner der mennesker blir gamle ved bemerkelsesverdig god helse.",
        "about.spiderweb": "Du fyller ut spørreskjemaet selv, og gir hvert aspekt en poengsum fra 0 til 10. Svarene dine tegnes som din personlige helseflate i spindelvevet. Det finnes ingen norm og ingenting å bestå eller stryke på: vevet viser hvordan du opplever helsen din i dette øyeblikket, i alle seks dimensjoner – et bilde som er mye rikere enn et enkelt tall.\n\nÅ fylle det ut er ofte en øyeåpner i seg selv: helse viser seg å ikke bare være kroppen og humøret ditt, men også mening, deltakelse, livskvalitet og hvordan du håndterer dagene dine.",
        "about.conversation": "Spindelvevet er utgangspunktet for det Positive Health kaller «den andre samtalen» – med en lege, sykepleier, coach, sosialarbeider eller noen du stoler på. Samtalen utvider seg først (ser på hele vevet, ikke bare én plage) og snevrer seg deretter inn mot det som virkelig betyr noe for deg. Det handler ikke om de laveste poengsummene; du velger hva du vil gi oppmerksomhet.\n\nSlike samtaler tar jevnlig overraskende vendinger: det en person først kom inn med, viser seg å ikke være det de mest ønsker å jobbe med. Folk vet som regel allerede hva som trengs – vevet hjelper til med å si det høyt.\n\nDerfra er tilnærmingen bevisst liten: velg ett lite skritt du kan ta selv, og tenk på hvem eller hva som kunne støtte deg. Når ett punkt i vevet beveger seg, har andre punkter en tendens til å bevege seg også.",
        "about.step1.title": "Fyll ut spindelvevet",
        "about.step1.text": "Gi poeng for hvordan du har det med hvert aspekt, fra 0 til 10. Det tar bare noen få minutter. Det finnes ingen norm – det er en personlig vurdering av dette øyeblikket.",
        "about.step2.title": "Ha den andre samtalen",
        "about.step2.text": "Bruk spindelvevet ditt som en samtalestarter – med en lege, sykepleier, sosialarbeider, coach eller en venn. Ikke om hvor poengsummene er lave, men om hvor du vil hen og hva som er viktig for deg.",
        "about.step3.title": "Ta et lite skritt",
        "about.step3.text": "Velg ett lite skritt du kan ta selv, og tenk på hvem eller hva som kunne støtte deg. Når ett punkt i vevet beveger seg, beveger andre punkter seg også.",
        "about.who": "Dialogverktøyene finnes i tre versjoner – for voksne, for ungdom og unge voksne, og for barn – slik at alle fra rundt 8 år kan fylle ut sitt eget vev. De offisielle verktøyene er publisert på mer enn ti språk, og en nettversjon er tilgjengelig på mypositivehealth.com.\n\nPositive Health startet i Nederland og brukes nå internasjonalt, fra fastlegekontorer og sykehus til skoler, arbeidsplasser og hele regioner. Det brukes på fire nivåer: av enkeltpersoner for seg selv, av fagfolk i deres daglige arbeid, av lokalsamfunn, og i helsesystemet som helhet – som en drivkraft for endring fra sykdomsorientert til helseorientert omsorg.",
        "about.movement": "Positive Health er ikke bare et verktøy, men en bevegelse – en annerledes måte å tenke, gjøre, organisere og finansiere omsorg på. Den starter som regel med noen få engasjerte mennesker og lokale partnere som deler en visjon, og vokser til bredere koalisjoner. Måten den gjennomføres på varierer fra land til land og kultur til kultur, men kjernevisjonen forblir den samme. Den har slått rot på tvers av mange områder i Nederland det siste tiåret og sprer seg nå internasjonalt.\n\nI kjernen ligger et skifte bort fra «reparasjonsrefleksen» – den automatiske trangen til å fikse en plage – mot å styrke mennesker til å gjenkjenne hva de selv kan gjøre for å leve et meningsfullt og betydningsfullt liv.",
        "about.value": "I omsorg sikter Positive Health mot det som kalles «Quadruple Aim»:\n\n• Bedre helse for befolkningen\n• Bedre opplevelse av omsorgen for menneskene\n• Lavere kostnader\n• Bedre trivsel for omsorgsteam og fagfolk\n\nTil sammen beskriver disse en bevegelse fra sykdomsorientert omsorg til helseorientert omsorg – omsorg som tar utgangspunkt i hva som betyr noe for en person, ikke bare i hva som er galt med dem.",
        "about.resources": "Utover spindelvevet tilbyr Positive Health International og instituttet for Positive Health (iPH) flere måter å gå dypere på:\n\n• Nettbasert spindelvev på mypositivehealth.com, for å fylle det ut digitalt.\n• En e-læringsmodul, «The Essence of Positive Health», som en introduksjon.\n• En håndbok med omfattende veiledning.\n• Gratis nedlastinger og materiell for folk og fagfolk.\n\nDenne appen er en uavhengig personlig følgesvenn som lar deg fylle ut spindelvevet på enheten din; ressursene ovenfor er kilden og stedet å lære mer.",
        "about.link.phi": "Positive Health International – dialogverktøy",
        "about.link.iph": "Institute for Positive Health (iPH)",
        "about.link.online": "My Positive Health – offisielt nettbasert spindelvev",
        "about.source": "Innholdet i dialogverktøyet i denne appen (dimensjoner, aspekter og samtalespørsmål) er © iPH/PHi. Den engelske ordlyden er gjengitt fra de offisielle engelske verktøyene til Positive Health International i samarbeid med instituttet for Positive Health (iPH). Oversettelser til andre språk er uoffisielle og ble laget for denne appen. De forklarende tekstene oppsummerer den offentlige informasjonen fra begge organisasjonene.\n\nDenne appen er en følgesvenn for personlig bruk. Den er ikke et medisinsk utstyr og gir verken diagnoser eller medisinske råd. Svarene dine lagres kun på denne enheten.",
        "dimexpl.body": "Hvordan kroppen din føles og fungerer – å føle deg frisk og i form, sove, spise, bevege deg, og være fri for plager eller smerte.",
        "dimexpl.mind": "Ditt indre liv – å huske og konsentrere deg, håndtere følelsene dine, akseptere deg selv og føle at du har kontroll.",
        "dimexpl.meaning": "Mening og retning – et meningsfullt liv, livsglede, idealer og drømmer, tillit, aksept og takknemlighet.",
        "dimexpl.quality": "Hvordan du opplever livet ditt – glede, lykke, balanse, trygghet, og forhold som bolig og økonomi.",
        "dimexpl.participation": "Din forbindelse med andre – sosiale kontakter, å bli tatt på alvor, tilhørighet, støtte, og å gjøre meningsfulle ting sammen.",
        "dimexpl.daily": "Å mestre hverdagen – å ta vare på deg selv, arbeid eller studier, kjenne dine grenser, og kunne be om hjelp.",
        "adult.body": "Kroppslige funksjoner",
        "adult.mind": "Mentalt velvære",
        "adult.meaning": "Meningsfullhet",
        "adult.quality": "Livskvalitet",
        "adult.participation": "Deltakelse",
        "adult.daily": "Daglig fungering",
        "adolescent.body": "Kroppen min",
        "adolescent.mind": "Følelsene og tankene mine",
        "adolescent.meaning": "Meningsfullhet",
        "adolescent.quality": "Livskvalitet",
        "adolescent.participation": "Deltakelse",
        "adolescent.daily": "Hverdagsliv",
        "child.body": "Kroppen min",
        "child.mind": "Følelsene og tankene mine",
        "child.meaning": "Nå og i framtiden",
        "child.quality": "Å ha det bra med deg selv",
        "child.participation": "Deltakelse",
        "child.daily": "Hverdagsliv",
        "adult.body.1": "Å føle seg frisk",
        "adult.body.2": "Å føle seg i form",
        "adult.body.3": "Ingen fysiske plager eller smerte",
        "adult.body.4": "Å sove",
        "adult.body.5": "Å spise",
        "adult.body.6": "Seksualitet",
        "adult.body.7": "Fysisk form",
        "adult.body.8": "Fysisk aktivitet",
        "adult.mind.1": "Å kunne huske ting",
        "adult.mind.2": "Å kunne konsentrere seg",
        "adult.mind.3": "Å kunne kommunisere",
        "adult.mind.4": "Å være glad",
        "adult.mind.5": "Å akseptere deg selv",
        "adult.mind.6": "Å kunne håndtere endring",
        "adult.mind.7": "Å føle at du har kontroll",
        "adult.meaning.1": "Å ha et meningsfullt liv",
        "adult.meaning.2": "Å ha livsglede",
        "adult.meaning.3": "Å strebe etter idealer",
        "adult.meaning.4": "Å føle tillit",
        "adult.meaning.5": "Å akseptere livet",
        "adult.meaning.6": "Å være takknemlig",
        "adult.meaning.7": "Livslang læring",
        "adult.quality.1": "Glede",
        "adult.quality.2": "Å være lykkelig",
        "adult.quality.3": "Å ha det godt",
        "adult.quality.4": "Å føle deg i balanse",
        "adult.quality.5": "Å føle deg trygg",
        "adult.quality.6": "Nærhet",
        "adult.quality.7": "Boforhold",
        "adult.quality.8": "Å ha nok penger",
        "adult.participation.1": "Sosiale kontakter",
        "adult.participation.2": "Å bli tatt på alvor",
        "adult.participation.3": "Å gjøre morsomme ting sammen",
        "adult.participation.4": "Å ha støtte fra andre",
        "adult.participation.5": "Følelse av tilhørighet",
        "adult.participation.6": "Å gjøre meningsfulle ting",
        "adult.participation.7": "Å være interessert i samfunnet",
        "adult.daily.1": "Å ta vare på deg selv",
        "adult.daily.2": "Å kjenne dine begrensninger",
        "adult.daily.3": "Kunnskap om helse",
        "adult.daily.4": "Å styre tiden",
        "adult.daily.5": "Å styre økonomien",
        "adult.daily.6": "Å kunne arbeide",
        "adult.daily.7": "Å kunne be om hjelp",
        "adolescent.body.1": "Å føle seg frisk",
        "adolescent.body.2": "Å ha energi",
        "adolescent.body.3": "Ingen fysiske plager eller smerte",
        "adolescent.body.4": "Å spise sunt",
        "adolescent.body.5": "Å sove",
        "adolescent.body.6": "Form",
        "adolescent.body.7": "Sport og trening",
        "adolescent.body.8": "Fysisk utseende",
        "adolescent.mind.1": "Konsentrasjon",
        "adolescent.mind.2": "Å håndtere følelsene dine",
        "adolescent.mind.3": "Å føle deg positiv til livet",
        "adolescent.mind.4": "Å akseptere deg selv",
        "adolescent.mind.5": "Tro på deg selv",
        "adolescent.mind.6": "Å håndtere endring",
        "adolescent.mind.7": "Å ha kontroll",
        "adolescent.meaning.1": "Å leve et meningsfullt liv",
        "adolescent.meaning.2": "Å ha tro på framtiden",
        "adolescent.meaning.3": "Å ha livsglede",
        "adolescent.meaning.4": "Å ha mål og drømmer",
        "adolescent.meaning.5": "Å ta valg",
        "adolescent.meaning.6": "Å akseptere situasjoner",
        "adolescent.meaning.7": "Takknemlighet",
        "adolescent.quality.1": "Lykke",
        "adolescent.quality.2": "Glede",
        "adolescent.quality.3": "Å oppleve balanse",
        "adolescent.quality.4": "Å føle deg trygg",
        "adolescent.quality.5": "Et hyggelig miljø",
        "adolescent.quality.6": "Bolig og bomiljø",
        "adolescent.quality.7": "Å få det til å gå rundt",
        "adolescent.participation.1": "Sosiale kontakter",
        "adolescent.participation.2": "Å bli tatt på alvor",
        "adolescent.participation.3": "Å gjøre morsomme ting med andre",
        "adolescent.participation.4": "Tilhørighet",
        "adolescent.participation.5": "Selvuttrykk",
        "adolescent.participation.6": "Meningsfulle relasjoner",
        "adolescent.participation.7": "Å få støtte og forståelse fra andre",
        "adolescent.daily.1": "Å ta vare på deg selv",
        "adolescent.daily.2": "Å kunne arbeide eller studere",
        "adolescent.daily.3": "Å kjenne dine begrensninger",
        "adolescent.daily.4": "Kunnskap om helse",
        "adolescent.daily.5": "Evne til å planlegge",
        "adolescent.daily.6": "Å kunne be om hjelp",
        "adolescent.daily.7": "Ingen røyk, alkohol eller narkotika",
        "child.body.1": "Å ha det bra",
        "child.body.2": "Å ha energi",
        "child.body.3": "Å spise sunt",
        "child.body.4": "Å sove godt",
        "child.body.5": "Sport og trening",
        "child.body.6": "Ingen fysiske plager",
        "child.body.7": "Ingen smerte",
        "child.body.8": "Fysisk utseende",
        "child.mind.1": "Å håndtere følelsene dine",
        "child.mind.2": "Å akseptere deg selv",
        "child.mind.3": "Å passe inn",
        "child.mind.4": "Å føle deg positiv til livet",
        "child.mind.5": "Å kjenne dine begrensninger",
        "child.mind.6": "Å takle motgang",
        "child.meaning.1": "Å se mot framtiden",
        "child.meaning.2": "Kultur og religion",
        "child.meaning.3": "Å ha mål og drømmer",
        "child.meaning.4": "Å ta valg",
        "child.meaning.5": "Selvinnsikt",
        "child.meaning.6": "Forbilder",
        "child.quality.1": "Glede",
        "child.quality.2": "Lykke",
        "child.quality.3": "Å være i godt humør",
        "child.quality.4": "Et hyggelig miljø",
        "child.quality.5": "Å ha glede av å gjøre ting",
        "child.quality.6": "Å få støtte og forståelse fra andre",
        "child.participation.1": "Venner",
        "child.participation.2": "Tilhørighet",
        "child.participation.3": "Mobbing",
        "child.participation.4": "Selvbestemmelse",
        "child.participation.5": "Å henge med de andre",
        "child.participation.6": "Personlig bidrag",
        "child.daily.1": "Å gå på skolen",
        "child.daily.2": "Å være deg selv",
        "child.daily.3": "Fritid",
        "child.daily.4": "Å ta vare på deg selv",
        "child.daily.5": "Å føle deg normal",
        "child.daily.6": "Begrensninger",
        "child.daily.7": "Ingen bruk av røyk, alkohol eller narkotika",
    ]
}
