import Foundation

// Unofficial translation generated for this app — NOT the official Positive Health wording.
enum Papiamento {
    static let table: [String: String] = [
        "done": "Kla",
        "cancel": "Kanselá",
        "back": "Bèk",
        "next": "Siguiente",
        "app_title": "Mi Salú Positivo",
        "fill_menu": "Yena e webu di aranja",
        "empty_title": "Yena bo webu di aranja",
        "empty_desc": "Positive Health ta wak loke ta importante pa bo, den seis dimenshon di salú. Yena e webu di aranja pa haña bo bista personal — un punto di partida pa un otro tipo di kòmbersashon.",
        "version.adult.title": "Adultonan",
        "version.adolescent.title": "Adolesente / hóbennan",
        "version.child.title": "Muchanan",
        "version.adult.age": "18+ aña",
        "version.adolescent.age": "16–25 aña",
        "version.child.age": "8–16 aña",
        "reflect.adult": "Tin un kos ku ta importante pa mi ku ta falta:",
        "reflect.adolescent": "Lo siguiente ta spesialmente importante pa mi",
        "reflect.child": "Lo siguiente ta spesialmente importante pa mi",
        "q.how_feel": "Kon bo ta sinti tokante esaki? No tin kontesta bon ni robes.",
        "q.include12": "Inkluí preguntanan pa 12 aña i mas ariba",
        "q.almost_done": "Kasi kla",
        "q.write_here": "Skirbié akinan…",
        "q.save_footer": "Ora bo warda, bo bista personal ta aparesé den e webu di aranja. Kòrda: esaki no ta un tèst i no tin un norma — esaki ta bo mes imágen di e momento akí, i un punto di partida pa un kòmbersashon.",
        "q.show_web": "Mustra mi webu di aranja",
        "r.compare": "Kompará ku esun anterior",
        "r.no_norm_footer": "No tin norma ni punto pa alkansá. Esaki ta bo mes imágen di e momento akí.",
        "r.my_dimensions": "Mi dimenshonnan",
        "r.other_conversation": "E otro kòmbersashon",
        "r.other_footer": "No ta importa unda bo kuminsá — loke ta importante ta ku bo kuminsá, i ku bo dal pasonan chikitu. Ora un punto move, otro puntonan tambe ta move.",
        "r.your_answer": "Bo kontesta…",
        "conv.attention": "Tin un kos ku lo bo kier duna mas atenshon, òf ku lo bo kier kambia?",
        "conv.step": "Ki paso chikitu bo mes por dal?",
        "conv.support": "Ken òf kiko por yuda bo ku esaki?",
        "settings.title": "Konfigurashon",
        "settings.language": "Idioma",
        "settings.language_footer": "Ingles ta usa e teksto ofisial di e hèrmèntnan di Positive Health. E otro idiomanan ta tradukshonnan no ofisial trahá pa e app akí.",
        "about.title": "Tokante Positive Health",
        "about.s.whatisit": "Kiko ta Positive Health?",
        "about.s.origin": "Di unda e ta bini?",
        "about.s.dimensions": "E seis dimenshonnan",
        "about.s.spiderweb": "E webu di aranja",
        "about.s.conversation": "E otro kòmbersashon",
        "about.s.steps": "Kon e ta funshoná — tres paso",
        "about.s.who": "Pa ken e ta?",
        "about.s.movement": "Un movementu, no djis un hèrmènt",
        "about.s.value": "E balor ku e ta buska",
        "about.s.resources": "Mas rekurso",
        "about.s.versions": "Vershonnan den e app akí",
        "about.s.learnmore": "Siña mas",
        "about.whatisit": "Positive Health ta un bista amplio di salú ku a wòrdu desaroyá na Hulanda. En bes di definí salú komo ousensia di malesa, e ta wak hende komo persona kompleto: na nan resiliensia — e kapasidat di lidia ku e retonan físiko, emoshonal i sosial di bida — i na loke ta duna nan bida sentido. E pregunta sentral ta kambia di “Kiko tin fout ku bo?” pa “Kiko ta importante pa bo?”\n\nE no ta un tratamentu ni un tèst. E ta un manera di wak, un hèrmènt di reflekshon i un kuminsamentu di kòmbersashon ku ta yuda bo keda na mando di bo mes bida unda ku ta posibel.",
        "about.quote": "Mi ta konvensí ku di tur e fuersanan ku ta mehorá salú, sentido ta esun mas fuerte.",
        "about.quote_author": "Machteld Huber, fundadó di Positive Health",
        "about.origin": "Positive Health a wòrdu inisiá pa Machteld Huber, un anterior dòkter di kas hulandes i investigadó. Despues di kai gravemente malu e mes, el a ripará kuantu su mes aktitut i sentido di direkshon a influensiá su rekuperashon — un kos ku e bista dominante di salú no tabatin lugá pa dje.\n\nE definishon di 1948 di Organisashon Mundial di Salú ta deskribí salú komo un estado di bienestar físiko, mental i sosial kompleto. Huber i su koleganan a argumentá den British Medical Journal (2011) ku e ideal akí di “bienestar kompleto” ta státiko i inalkansabel — segun e norma ei kasi ningun hende no ta salú, muchu ménos hende ku ta biba ku un kondishon krónika. Nan a proponé un alternativa dinámiko: salú komo e kapasidat di adaptá i di maneha bo mes dilanti di e retonan di bida.\n\nPa deskubrí kiko salú ta nifiká pa hende mes, e ekipo di Huber a entrevistá pashèntnan, profeshonalnan di kuido i investigadónan. E shen di indikadónan di salú ku a sali for di e estudio akí a wòrdu agrupá den seis dimenshon prinsipal — e seis ehe di e webu di aranja. E investigashon tambe ta traha riba insightnan mas bieu: e salutogénesis di Aaron Antonovsky (studia loke ta krea salú en bes di loke ta kousa malesa) i e Blue Zones, region unda hende ta bira bieu den un salú remarkabelmente bon.",
        "about.spiderweb": "Bo mes ta yena e kuestionario, dunando kada aspekto un punto for di 0 te 10. Bo kontestanan ta wòrdu dibuhá komo bo superfisie personal di salú den e webu di aranja. No tin norma i nada pa pasa òf keda: e webu ta mustra kon bo ta eksperensiá bo salú na e momento akí, den tur seis dimenshon — un imágen ku ta muchu mas riku ku un solo number.\n\nYen'é hopi biaha ta un abridó di wowo di su mes: salú ta resultá di no ta solamente bo kurpa i bo estado di ánimo, sino tambe sentido, partisipashon, kalidat di bida i kon bo ta maneha bo dianan.",
        "about.conversation": "E webu di aranja ta e punto di partida pa loke Positive Health ta yama “e otro kòmbersashon” — ku un dòkter, fèrpleger, koach, trahadó sosial, òf un hende ku bo ta konfia. E kòmbersashon promé ta bira mas amplio (wak henter e webu, no djis un keho) i despues ta bai mas serka riba loke di berdat ta importante pa bo. E no ta tokante e puntonan mas abou; bo ta skohe kiko bo kier duna atenshon.\n\nTal kòmbersashonnan regularmente ta tuma direkshon sorprendente: e kos ku un hende a bini kuné promé ta resultá di no ta e kos ku e mas kier traha riba dje. Hende generalmente ya kaba sa kiko ta nesesario — e webu ta yuda pa bis'é na bos haltu.\n\nfor di ei, e enfoke ta deliberadamente chikitu: skohe un paso chikitu ku bo mes por dal, i pensa riba ken òf kiko por yuda bo. Ora un punto di e webu move, otro puntonan tambe ta tendé pa move.",
        "about.step1.title": "Yena e webu di aranja",
        "about.step1.text": "Duna un punto na kon bo ta sinti tokante kada aspekto, for di 0 te 10. E ta tuma djis un par di minüt. No tin norma — e ta un evaluashon personal di e momento akí.",
        "about.step2.title": "Tene e otro kòmbersashon",
        "about.step2.text": "Usa bo webu di aranja komo kuminsamentu di kòmbersashon — ku un dòkter, fèrpleger, trahadó sosial, koach, òf un amigu. No tokante unda e puntonan ta abou, sino tokante unda bo kier bai i kiko ta importante pa bo.",
        "about.step3.title": "Dal un paso chikitu",
        "about.step3.text": "Skohe un paso chikitu ku bo mes por dal, i pensa riba ken òf kiko por yuda bo. Ora un punto di e webu move, otro puntonan tambe ta move.",
        "about.who": "E hèrmèntnan di diálogo ta eksistí den tres vershon — pa adultonan, pa adolesente i hóbennan, i pa muchanan — asina ku tur hende for di mas o ménos 8 aña por yena nan mes webu. E hèrmèntnan ofisial ta publiká den mas ku dies idioma, i un vershon online ta disponibel na mypositivehealth.com.\n\nPositive Health a kuminsá na Hulanda i awor ta wòrdu usá internashonalmente, for di praktikanan di dòkter di kas i hòspital te na skol, lugá di trabou i henter region. E ta wòrdu apliká na kuater nivel: pa individuonan pa nan mes, pa profeshonalnan den nan trabou di tur dia, pa komunidat, i den e sistema di salú kompleto — komo un motor di kambio for di kuido enfoká riba malesa pa kuido enfoká riba salú.",
        "about.movement": "Positive Health no ta solamente un hèrmènt sino un movementu — un otro manera di pensa, hasi, organisá i finansiá kuido. E generalmente ta kuminsá ku un par di hende komprometé i partnernan lokal ku ta kompartí un vishon, i ta krese den koalishonnan mas amplio. E manera ku e ta wòrdu implementá ta diferensiá pa kada pais i kultura, ma e vishon sentral ta keda meskos. Riba e último dékada el a hinka rais den hopi domino na Hulanda i awor e ta plama internashonalmente.\n\nNa su korason tin un kambio for di “e refleho di drecha” — e impulso outomátiko pa drecha un keho — pa fortifiká hende pa rekonosé kiko nan mes por hasi pa biba un bida ku propósito i sentido.",
        "about.value": "Den kuido, Positive Health ta buska loke ta konosí komo e “Quadruple Aim”:\n\n• Mehorá e salú di e poblashon\n• Mehorá e eksperensia di kuido di hende\n• Redusí gastu\n• Mehorá e bienestar di ekiponan i profeshonalnan di kuido\n\nHuntu esakinan ta deskribí un kambio for di kuido enfoká riba malesa pa kuido enfoká riba salú — kuido ku ta kuminsá for di loke ta importante pa un hende, no solamente for di loke tin fout kuné.",
        "about.resources": "Fuera di e webu di aranja, Positive Health International i e institüt pa Positive Health (iPH) ta ofresé mas manera pa bai mas profundo:\n\n• E webu di aranja online na mypositivehealth.com, pa yen'é digitalmente.\n• Un módulo di e-learning, “The Essence of Positive Health”, komo introdukshon.\n• Un buki di man ku guia kompleto.\n• Downloadnan i materialnan grátis pa hende i profeshonalnan.\n\nE app akí ta un kompañero personal independiente ku ta laga bo yena e webu di aranja riba bo aparato; e rekursonan ariba ta e fuente i e lugá pa siña mas.",
        "about.link.phi": "Positive Health International — hèrmèntnan di diálogo",
        "about.link.iph": "Institüt pa Positive Health (iPH)",
        "about.link.online": "My Positive Health — webu di aranja online ofisial",
        "about.source": "E kontenido di e hèrmènt di diálogo den e app akí (dimenshonnan, aspektonan i preguntanan di kòmbersashon) ta © iPH/PHi. E teksto na ingles ta reprodusí for di e hèrmèntnan ofisial na ingles di Positive Health International den kolaborashon ku e institüt pa Positive Health (iPH). Tradukshonnan pa otro idioma ta no ofisial i a wòrdu trahá pa e app akí. E tekstonan splikatibo ta resumí e informashon públiko di ámbos organisashon.\n\nE app akí ta un kompañero pa uso personal. E no ta un aparato médiko i no ta duna diagnóstiko ni konseho médiko. Bo kontestanan ta wòrdu wardá solamente riba e aparato akí.",
        "dimexpl.body": "Kon bo kurpa ta sinti i funshoná — sinti bo salú i fit, drumi, kome, move, i ta liber di keho òf doló.",
        "dimexpl.mind": "Bo bida interior — kòrda i konsentrá, maneha bo sentimentunan, aseptá bo mes i sinti bo na kontrol.",
        "dimexpl.meaning": "Propósito i direkshon — un bida ku sentido, gana di biba, idealnan i soñonan, konfiansa, aseptashon i gratitut.",
        "dimexpl.quality": "Kon bo ta eksperensiá bo bida — gosa, felisidat, balansa, siguridat, i sirkunstansianan manera kas i plaka.",
        "dimexpl.participation": "Bo konekshon ku otro hende — kontaktonan sosial, ta wòrdu tumá na serio, pertenesé, sosten, i hasi kosnan ku sentido huntu.",
        "dimexpl.daily": "Maneha bida di tur dia — kuida bo mes, trabou òf estudio, konosé bo límitenan, i por pidi yudansa.",
        "adult.body": "Funshonnan di kurpa",
        "adult.mind": "Bienestar mental",
        "adult.meaning": "Sentido",
        "adult.quality": "Kalidat di bida",
        "adult.participation": "Partisipashon",
        "adult.daily": "Funshonamentu di tur dia",
        "adolescent.body": "Mi kurpa",
        "adolescent.mind": "Mi sentimentunan i pensamentunan",
        "adolescent.meaning": "Sentido",
        "adolescent.quality": "Kalidat di bida",
        "adolescent.participation": "Partisipashon",
        "adolescent.daily": "Bida di tur dia",
        "child.body": "Mi kurpa",
        "child.mind": "Mi sentimentunan i pensamentunan",
        "child.meaning": "Awor i den futuro",
        "child.quality": "Sinti bo bon ku bo mes",
        "child.participation": "Partisipashon",
        "child.daily": "Bida di tur dia",
        "adult.body.1": "Sinti bo salú",
        "adult.body.2": "Sinti bo fit",
        "adult.body.3": "Sin keho físiko ni doló",
        "adult.body.4": "Drumi",
        "adult.body.5": "Kome",
        "adult.body.6": "Seksualidat",
        "adult.body.7": "Kondishon físiko",
        "adult.body.8": "Aktividat físiko",
        "adult.mind.1": "Por kòrda kosnan",
        "adult.mind.2": "Por konsentrá",
        "adult.mind.3": "Por komuniká",
        "adult.mind.4": "Ta kontentu",
        "adult.mind.5": "Aseptá bo mes",
        "adult.mind.6": "Por maneha kambio",
        "adult.mind.7": "Sinti bo na kontrol",
        "adult.meaning.1": "Tin un bida ku sentido",
        "adult.meaning.2": "Tin gana di biba",
        "adult.meaning.3": "Persiguí idealnan",
        "adult.meaning.4": "Sinti bo konfiá",
        "adult.meaning.5": "Aseptá bida",
        "adult.meaning.6": "Ta gradisidu",
        "adult.meaning.7": "Siña henter bida",
        "adult.quality.1": "Gosa",
        "adult.quality.2": "Ta felis",
        "adult.quality.3": "Sinti bo bon",
        "adult.quality.4": "Sinti bo balansá",
        "adult.quality.5": "Sinti bo sigur",
        "adult.quality.6": "Intimidat",
        "adult.quality.7": "Sirkunstansianan di biba",
        "adult.quality.8": "Tin sufisiente plaka",
        "adult.participation.1": "Kontaktonan sosial",
        "adult.participation.2": "Ta wòrdu tumá na serio",
        "adult.participation.3": "Hasi kosnan dushi huntu",
        "adult.participation.4": "Tin sosten di otronan",
        "adult.participation.5": "Sentido di pertenesé",
        "adult.participation.6": "Hasi kosnan ku sentido",
        "adult.participation.7": "Ta interesá den sosiedat",
        "adult.daily.1": "Kuida bo mes",
        "adult.daily.2": "Konosé bo límitenan",
        "adult.daily.3": "Konosementu di salú",
        "adult.daily.4": "Maneha tempu",
        "adult.daily.5": "Maneha plaka",
        "adult.daily.6": "Por traha",
        "adult.daily.7": "Por pidi yudansa",
        "adolescent.body.1": "Sinti bo salú",
        "adolescent.body.2": "Tin energia",
        "adolescent.body.3": "Sin keho físiko ni doló",
        "adolescent.body.4": "Kome salú",
        "adolescent.body.5": "Drumi",
        "adolescent.body.6": "Kondishon físiko",
        "adolescent.body.7": "Deporte i ehersisio",
        "adolescent.body.8": "Aparensia físiko",
        "adolescent.mind.1": "Konsentrashon",
        "adolescent.mind.2": "Maneha bo sentimentunan",
        "adolescent.mind.3": "Sinti bo positivo tokante bida",
        "adolescent.mind.4": "Aseptá bo mes",
        "adolescent.mind.5": "Konfiansa den bo mes",
        "adolescent.mind.6": "Lidia ku kambio",
        "adolescent.mind.7": "Ta na kontrol",
        "adolescent.meaning.1": "Hiba un bida ku sentido",
        "adolescent.meaning.2": "Tin konfiansa den futuro",
        "adolescent.meaning.3": "Tin gana di biba",
        "adolescent.meaning.4": "Tin metanan i soñonan",
        "adolescent.meaning.5": "Hasi eskohonan",
        "adolescent.meaning.6": "Aseptá situashonnan",
        "adolescent.meaning.7": "Gratitut",
        "adolescent.quality.1": "Felisidat",
        "adolescent.quality.2": "Gosa",
        "adolescent.quality.3": "Eksperensiá balansa",
        "adolescent.quality.4": "Sinti bo sigur",
        "adolescent.quality.5": "Un ambiente agradabel",
        "adolescent.quality.6": "Kas i ambiente di biba",
        "adolescent.quality.7": "Yega na fin di luna",
        "adolescent.participation.1": "Kontaktonan sosial",
        "adolescent.participation.2": "Ta wòrdu tumá na serio",
        "adolescent.participation.3": "Hasi kosnan dushi ku otro hende",
        "adolescent.participation.4": "Pertenesé",
        "adolescent.participation.5": "Ekspreshon di bo mes",
        "adolescent.participation.6": "Relashonnan ku sentido",
        "adolescent.participation.7": "Risibí sosten i komprenshon di otronan",
        "adolescent.daily.1": "Kuida bo mes",
        "adolescent.daily.2": "Por traha òf studia",
        "adolescent.daily.3": "Konosé bo límitenan",
        "adolescent.daily.4": "Konosementu tokante salú",
        "adolescent.daily.5": "Kapasidat di planiá",
        "adolescent.daily.6": "Por pidi yudansa",
        "adolescent.daily.7": "Sin siga, alkohòl ni droga",
        "child.body.1": "Sinti bo bon",
        "child.body.2": "Tin energia",
        "child.body.3": "Kome salú",
        "child.body.4": "Drumi bon",
        "child.body.5": "Deporte i ehersisio",
        "child.body.6": "Sin keho físiko",
        "child.body.7": "Sin doló",
        "child.body.8": "Aparensia físiko",
        "child.mind.1": "Maneha bo sentimentunan",
        "child.mind.2": "Aseptá bo mes",
        "child.mind.3": "Enkahá",
        "child.mind.4": "Sinti bo positivo tokante bida",
        "child.mind.5": "Konosé bo límitenan",
        "child.mind.6": "Lidia ku kontratempu",
        "child.meaning.1": "Wak pa futuro",
        "child.meaning.2": "Kultura i religion",
        "child.meaning.3": "Tin metanan i soñonan",
        "child.meaning.4": "Hasi eskohonan",
        "child.meaning.5": "Konosementu di bo mes",
        "child.meaning.6": "Ehèmpelnan pa sigui",
        "child.quality.1": "Gosa",
        "child.quality.2": "Felisidat",
        "child.quality.3": "Alegria",
        "child.quality.4": "Un ambiente agradabel",
        "child.quality.5": "Gosa di hasi kosnan",
        "child.quality.6": "Risibí sosten i komprenshon di otronan",
        "child.participation.1": "Amigunan",
        "child.participation.2": "Pertenesé",
        "child.participation.3": "Pesta (bullying)",
        "child.participation.4": "Determiná bo mes",
        "child.participation.5": "Keda na paso ku otronan",
        "child.participation.6": "Kontribushon personal",
        "child.daily.1": "Bai skol",
        "child.daily.2": "Ta bo mes",
        "child.daily.3": "Tempu liber",
        "child.daily.4": "Kuida bo mes",
        "child.daily.5": "Sinti bo normal",
        "child.daily.6": "Limitashonnan",
        "child.daily.7": "Sin uso di siga, alkohòl ni droga",
    ]
}
