import Foundation

// Unofficial translation generated for this app — NOT the official Positive Health wording.
enum Spanish {
    static let table: [String: String] = [
        "done": "Listo",
        "cancel": "Cancelar",
        "back": "Atrás",
        "next": "Siguiente",
        "app_title": "Mi Salud Positiva",
        "fill_menu": "Completa la telaraña",
        "empty_title": "Completa tu telaraña",
        "empty_desc": "Positive Health observa lo que te importa, a través de seis dimensiones de la salud. Completa la telaraña para obtener tu panorama personal: un punto de partida para una conversación distinta.",
        "version.adult.title": "Adultos",
        "version.adolescent.title": "Adolescentes / jóvenes",
        "version.child.title": "Niños",
        "version.adult.age": "18+ años",
        "version.adolescent.age": "16–25 años",
        "version.child.age": "8–16 años",
        "reflect.adult": "Falta algo que es importante para mí:",
        "reflect.adolescent": "Lo siguiente es especialmente importante para mí",
        "reflect.child": "Lo siguiente es especialmente importante para mí",
        "q.how_feel": "¿Cómo te sientes con esto? No hay respuestas correctas ni incorrectas.",
        "q.include12": "Incluir preguntas para 12 años en adelante",
        "q.almost_done": "Ya casi terminas",
        "q.write_here": "Escríbelo aquí…",
        "q.save_footer": "Cuando guardes, tu panorama personal aparecerá en la telaraña. Recuerda: esto no es un test y no hay una norma; es tu propia imagen de este momento y un punto de partida para una conversación.",
        "q.show_web": "Mostrar mi telaraña",
        "r.compare": "Comparar con la anterior",
        "r.no_norm_footer": "No hay una norma ni una puntuación que alcanzar. Esta es tu propia imagen de este momento.",
        "r.my_dimensions": "Mis dimensiones",
        "r.other_conversation": "La otra conversación",
        "r.other_footer": "No importa por dónde empieces; lo que importa es que empieces y que des pequeños pasos. Cuando un punto se mueve, otros puntos también se mueven.",
        "r.your_answer": "Tu respuesta…",
        "conv.attention": "¿Hay algo a lo que te gustaría prestar más atención o que te gustaría cambiar?",
        "conv.step": "¿Qué pequeño paso podrías dar por ti mismo?",
        "conv.support": "¿Quién o qué podría apoyarte con esto?",
        "settings.title": "Ajustes",
        "settings.language": "Idioma",
        "settings.language_footer": "El inglés utiliza la redacción oficial de las herramientas de Positive Health. Los demás idiomas son traducciones no oficiales hechas para esta app.",
        "about.title": "Acerca de Positive Health",
        "about.s.whatisit": "¿Qué es Positive Health?",
        "about.s.origin": "¿De dónde viene?",
        "about.s.dimensions": "Las seis dimensiones",
        "about.s.spiderweb": "La telaraña",
        "about.s.conversation": "La otra conversación",
        "about.s.steps": "Cómo funciona: tres pasos",
        "about.s.who": "¿Para quién es?",
        "about.s.movement": "Un movimiento, no solo una herramienta",
        "about.s.value": "El valor que busca",
        "about.s.resources": "Más recursos",
        "about.s.versions": "Versiones en esta app",
        "about.s.learnmore": "Saber más",
        "about.whatisit": "Positive Health es una visión amplia de la salud que se desarrolló en los Países Bajos. En lugar de definir la salud como la ausencia de enfermedad, mira a las personas como seres completos: su resiliencia —la capacidad de afrontar los desafíos físicos, emocionales y sociales de la vida— y aquello que da sentido a su vida. La pregunta central pasa de “¿Qué te pasa?” a “¿Qué te importa?”\n\nNo es un tratamiento ni un test. Es una forma de mirar, una herramienta de reflexión y un punto de partida para conversar que te ayuda a seguir al mando de tu propia vida siempre que sea posible.",
        "about.quote": "Estoy convencida de que, de todas las fuerzas que favorecen la salud, el sentido de la vida es la más fuerte.",
        "about.quote_author": "Machteld Huber, fundadora de Positive Health",
        "about.origin": "Positive Health fue impulsada por Machteld Huber, exmédica de familia e investigadora neerlandesa. Tras enfermar gravemente ella misma, notó cuánto influían su propia actitud y su sentido de dirección en su recuperación, algo para lo que la visión predominante de la salud no tenía espacio.\n\nLa definición de la Organización Mundial de la Salud de 1948 describe la salud como un estado de completo bienestar físico, mental y social. Huber y sus colegas argumentaron en el British Medical Journal (2011) que este ideal de “completo bienestar” es estático e inalcanzable: según ese criterio, casi nadie está sano, y menos aún quienes viven con una enfermedad crónica. Propusieron una alternativa dinámica: la salud como la capacidad de adaptarse y de gestionarse a uno mismo frente a los desafíos de la vida.\n\nPara descubrir qué significa la salud para las personas mismas, el equipo de Huber entrevistó luego a pacientes, profesionales del cuidado e investigadores. Los cientos de indicadores de salud que surgieron de este estudio se agruparon en seis dimensiones principales: los seis ejes de la telaraña. La investigación también se apoya en ideas más antiguas: la salutogénesis de Aaron Antonovsky (estudiar qué crea salud en lugar de qué causa enfermedad) y las Blue Zones, regiones donde las personas envejecen con una salud notablemente buena.",
        "about.spiderweb": "Tú mismo completas el cuestionario, puntuando cada aspecto de 0 a 10. Tus respuestas se dibujan como tu superficie de salud personal en la telaraña. No hay una norma ni nada que aprobar o suspender: la telaraña muestra cómo experimentas tu salud en este momento, en las seis dimensiones; una imagen mucho más rica que un solo número.\n\nCompletarla suele ser en sí mismo un descubrimiento: resulta que la salud no es solo tu cuerpo y tu estado de ánimo, sino también el sentido, la participación, la calidad de vida y cómo llevas tus días.",
        "about.conversation": "La telaraña es el punto de partida de lo que Positive Health llama “la otra conversación”: con un médico, enfermero, coach, trabajador social o alguien en quien confíes. La conversación primero se amplía (mirando toda la telaraña, no solo una queja) y luego se centra en lo que de verdad te importa. No se trata de las puntuaciones más bajas; tú eliges a qué quieres prestar atención.\n\nEstas conversaciones toman con frecuencia rumbos sorprendentes: aquello con lo que alguien llegó al principio resulta no ser lo que más quiere trabajar. Las personas suelen saber ya lo que necesitan; la telaraña ayuda a decirlo en voz alta.\n\nA partir de ahí, el enfoque es deliberadamente pequeño: elige un pequeño paso que puedas dar por ti mismo y piensa en quién o qué podría apoyarte. Cuando un punto de la telaraña se mueve, otros puntos suelen moverse también.",
        "about.step1.title": "Completa la telaraña",
        "about.step1.text": "Puntúa cómo te sientes con cada aspecto, de 0 a 10. Solo lleva unos minutos. No hay una norma: es una valoración personal de este momento.",
        "about.step2.title": "Ten la otra conversación",
        "about.step2.text": "Usa tu telaraña como punto de partida para conversar: con un médico, enfermero, trabajador social, coach o una amistad. No sobre dónde las puntuaciones son bajas, sino sobre adónde quieres ir y qué es importante para ti.",
        "about.step3.title": "Da un pequeño paso",
        "about.step3.text": "Elige un pequeño paso que puedas dar por ti mismo y piensa en quién o qué podría apoyarte. Cuando un punto de la telaraña se mueve, otros puntos también se mueven.",
        "about.who": "Las herramientas de diálogo existen en tres versiones —para adultos, para adolescentes y jóvenes, y para niños—, de modo que cualquier persona a partir de unos 8 años pueda completar su propia telaraña. Las herramientas oficiales están publicadas en más de diez idiomas, y hay una versión en línea disponible en mypositivehealth.com.\n\nPositive Health comenzó en los Países Bajos y hoy se usa internacionalmente, desde consultorios de medicina de familia y hospitales hasta escuelas, lugares de trabajo y regiones enteras. Se aplica en cuatro niveles: por las personas para sí mismas, por los profesionales en su trabajo diario, por las comunidades y en el sistema de salud en su conjunto, como motor de un cambio de una atención orientada a la enfermedad a una atención orientada a la salud.",
        "about.movement": "Positive Health no es solo una herramienta, sino un movimiento: una forma distinta de pensar, hacer, organizar y financiar la atención. Suele empezar con unas pocas personas comprometidas y socios locales que comparten una visión, y crece hasta convertirse en coaliciones más amplias. La manera de implementarlo varía según el país y la cultura, pero la visión central sigue siendo la misma. En la última década ha echado raíces en muchos ámbitos de los Países Bajos y ahora se está extendiendo internacionalmente.\n\nEn su esencia está un alejamiento del “reflejo de reparar” —el impulso automático de arreglar una queja— hacia el empoderamiento de las personas para que reconozcan lo que ellas mismas pueden hacer para vivir una vida con propósito y sentido.",
        "about.value": "En la atención, Positive Health busca lo que se conoce como el “Quadruple Aim”:\n\n• Mejorar la salud de la población\n• Mejorar la experiencia de atención de las personas\n• Reducir los costes\n• Mejorar el bienestar de los equipos y profesionales de la atención\n\nEn conjunto describen un paso de una atención orientada a la enfermedad a una atención orientada a la salud: una atención que parte de lo que le importa a la persona, y no solo de lo que le pasa.",
        "about.resources": "Más allá de la telaraña, Positive Health International y el institute for Positive Health (iPH) ofrecen más formas de profundizar:\n\n• La telaraña en línea en mypositivehealth.com, para completarla de forma digital.\n• Un módulo de aprendizaje en línea, “The Essence of Positive Health”, como introducción.\n• Un manual con orientación completa.\n• Descargas y materiales gratuitos para personas y profesionales.\n\nEsta app es un acompañante personal independiente que te permite completar la telaraña en tu dispositivo; los recursos anteriores son la fuente y el lugar para aprender más.",
        "about.link.phi": "Positive Health International — herramientas de diálogo",
        "about.link.iph": "Institute for Positive Health (iPH)",
        "about.link.online": "My Positive Health — telaraña oficial en línea",
        "about.source": "El contenido de la herramienta de diálogo de esta app (dimensiones, aspectos y preguntas de conversación) es © iPH/PHi. La redacción en inglés se reproduce a partir de las herramientas oficiales en inglés de Positive Health International en colaboración con el institute for Positive Health (iPH). Las traducciones a otros idiomas son no oficiales y se hicieron para esta app. Los textos explicativos resumen la información pública de ambas organizaciones.\n\nEsta app es un acompañante de uso personal. No es un dispositivo médico y no ofrece diagnósticos ni consejos médicos. Tus respuestas se guardan únicamente en este dispositivo.",
        "dimexpl.body": "Cómo se siente y funciona tu cuerpo: sentirte sano y en forma, dormir, comer, moverte y estar libre de molestias o dolor.",
        "dimexpl.mind": "Tu vida interior: recordar y concentrarte, manejar tus sentimientos, aceptarte a ti mismo y sentir que tienes el control.",
        "dimexpl.meaning": "Propósito y dirección: una vida con sentido, ganas de vivir, ideales y sueños, confianza, aceptación y gratitud.",
        "dimexpl.quality": "Cómo experimentas tu vida: disfrute, felicidad, equilibrio, seguridad y circunstancias como la vivienda y el dinero.",
        "dimexpl.participation": "Tu conexión con los demás: contactos sociales, sentirte tomado en serio, pertenencia, apoyo y hacer cosas con sentido juntos.",
        "dimexpl.daily": "Manejar la vida cotidiana: cuidar de ti mismo, trabajar o estudiar, conocer tus límites y ser capaz de pedir ayuda.",
        "adult.body": "Funciones corporales",
        "adult.mind": "Bienestar mental",
        "adult.meaning": "Sentido de la vida",
        "adult.quality": "Calidad de vida",
        "adult.participation": "Participación",
        "adult.daily": "Funcionamiento diario",
        "adolescent.body": "Mi cuerpo",
        "adolescent.mind": "Mis sentimientos y pensamientos",
        "adolescent.meaning": "Sentido de la vida",
        "adolescent.quality": "Calidad de vida",
        "adolescent.participation": "Participación",
        "adolescent.daily": "Vida diaria",
        "child.body": "Mi cuerpo",
        "child.mind": "Mis sentimientos y pensamientos",
        "child.meaning": "Ahora y en el futuro",
        "child.quality": "Sentirte bien contigo mismo",
        "child.participation": "Participación",
        "child.daily": "Vida diaria",
        "adult.body.1": "Sentirte sano",
        "adult.body.2": "Sentirte en forma",
        "adult.body.3": "Sin molestias físicas ni dolor",
        "adult.body.4": "Dormir",
        "adult.body.5": "Comer",
        "adult.body.6": "Sexualidad",
        "adult.body.7": "Condición física",
        "adult.body.8": "Actividad física",
        "adult.mind.1": "Poder recordar cosas",
        "adult.mind.2": "Poder concentrarte",
        "adult.mind.3": "Poder comunicarte",
        "adult.mind.4": "Estar animado",
        "adult.mind.5": "Aceptarte a ti mismo",
        "adult.mind.6": "Poder afrontar los cambios",
        "adult.mind.7": "Sentir que tienes el control",
        "adult.meaning.1": "Tener una vida con sentido",
        "adult.meaning.2": "Tener ganas de vivir",
        "adult.meaning.3": "Perseguir ideales",
        "adult.meaning.4": "Sentir confianza",
        "adult.meaning.5": "Aceptar la vida",
        "adult.meaning.6": "Sentir gratitud",
        "adult.meaning.7": "Aprender a lo largo de la vida",
        "adult.quality.1": "Disfrute",
        "adult.quality.2": "Ser feliz",
        "adult.quality.3": "Sentirte bien",
        "adult.quality.4": "Sentirte equilibrado",
        "adult.quality.5": "Sentirte seguro",
        "adult.quality.6": "Intimidad",
        "adult.quality.7": "Condiciones de vivienda",
        "adult.quality.8": "Tener suficiente dinero",
        "adult.participation.1": "Contactos sociales",
        "adult.participation.2": "Sentirte tomado en serio",
        "adult.participation.3": "Hacer cosas divertidas juntos",
        "adult.participation.4": "Contar con el apoyo de los demás",
        "adult.participation.5": "Sentido de pertenencia",
        "adult.participation.6": "Hacer cosas con sentido",
        "adult.participation.7": "Interesarte por la sociedad",
        "adult.daily.1": "Cuidar de ti mismo",
        "adult.daily.2": "Conocer tus límites",
        "adult.daily.3": "Conocimientos sobre la salud",
        "adult.daily.4": "Gestionar el tiempo",
        "adult.daily.5": "Gestionar el dinero",
        "adult.daily.6": "Poder trabajar",
        "adult.daily.7": "Poder pedir ayuda",
        "adolescent.body.1": "Sentirte sano",
        "adolescent.body.2": "Tener energía",
        "adolescent.body.3": "Sin molestias físicas ni dolor",
        "adolescent.body.4": "Comer de forma saludable",
        "adolescent.body.5": "Dormir",
        "adolescent.body.6": "Estar en forma",
        "adolescent.body.7": "Deporte y ejercicio",
        "adolescent.body.8": "Apariencia física",
        "adolescent.mind.1": "Concentración",
        "adolescent.mind.2": "Manejar tus sentimientos",
        "adolescent.mind.3": "Sentirte positivo sobre la vida",
        "adolescent.mind.4": "Aceptarte a ti mismo",
        "adolescent.mind.5": "Confianza en ti mismo",
        "adolescent.mind.6": "Afrontar los cambios",
        "adolescent.mind.7": "Tener el control",
        "adolescent.meaning.1": "Llevar una vida con sentido",
        "adolescent.meaning.2": "Tener confianza en el futuro",
        "adolescent.meaning.3": "Tener ganas de vivir",
        "adolescent.meaning.4": "Tener metas y sueños",
        "adolescent.meaning.5": "Tomar decisiones",
        "adolescent.meaning.6": "Aceptar las situaciones",
        "adolescent.meaning.7": "Gratitud",
        "adolescent.quality.1": "Felicidad",
        "adolescent.quality.2": "Disfrute",
        "adolescent.quality.3": "Sentir equilibrio",
        "adolescent.quality.4": "Sentirte seguro",
        "adolescent.quality.5": "Un entorno agradable",
        "adolescent.quality.6": "Vivienda y entorno de vida",
        "adolescent.quality.7": "Llegar a fin de mes",
        "adolescent.participation.1": "Contactos sociales",
        "adolescent.participation.2": "Sentirte tomado en serio",
        "adolescent.participation.3": "Hacer cosas divertidas con otras personas",
        "adolescent.participation.4": "Pertenencia",
        "adolescent.participation.5": "Expresarte",
        "adolescent.participation.6": "Relaciones con sentido",
        "adolescent.participation.7": "Recibir apoyo y comprensión de los demás",
        "adolescent.daily.1": "Cuidar de ti mismo",
        "adolescent.daily.2": "Poder trabajar o estudiar",
        "adolescent.daily.3": "Conocer tus límites",
        "adolescent.daily.4": "Conocimientos sobre la salud",
        "adolescent.daily.5": "Capacidad de planificar",
        "adolescent.daily.6": "Poder pedir ayuda",
        "adolescent.daily.7": "Sin tabaco, alcohol ni drogas",
        "child.body.1": "Sentirte bien",
        "child.body.2": "Tener energía",
        "child.body.3": "Comer de forma saludable",
        "child.body.4": "Dormir bien",
        "child.body.5": "Deporte y ejercicio",
        "child.body.6": "Sin molestias físicas",
        "child.body.7": "Sin dolor",
        "child.body.8": "Apariencia física",
        "child.mind.1": "Manejar tus sentimientos",
        "child.mind.2": "Aceptarte a ti mismo",
        "child.mind.3": "Encajar",
        "child.mind.4": "Sentirte positivo sobre la vida",
        "child.mind.5": "Conocer tus límites",
        "child.mind.6": "Afrontar las dificultades",
        "child.meaning.1": "Mirar hacia el futuro",
        "child.meaning.2": "Cultura y religión",
        "child.meaning.3": "Tener metas y sueños",
        "child.meaning.4": "Tomar decisiones",
        "child.meaning.5": "Conocerte a ti mismo",
        "child.meaning.6": "Modelos a seguir",
        "child.quality.1": "Disfrute",
        "child.quality.2": "Felicidad",
        "child.quality.3": "Alegría",
        "child.quality.4": "Un entorno agradable",
        "child.quality.5": "Disfrutar haciendo cosas",
        "child.quality.6": "Recibir apoyo y comprensión de los demás",
        "child.participation.1": "Amigos",
        "child.participation.2": "Pertenencia",
        "child.participation.3": "Acoso",
        "child.participation.4": "Decidir por ti mismo",
        "child.participation.5": "Seguir el ritmo de los demás",
        "child.participation.6": "Aportación personal",
        "child.daily.1": "Ir a la escuela",
        "child.daily.2": "Ser tú mismo",
        "child.daily.3": "Tiempo libre",
        "child.daily.4": "Cuidar de ti mismo",
        "child.daily.5": "Sentirte normal",
        "child.daily.6": "Límites",
        "child.daily.7": "Sin tabaco, alcohol ni consumo de drogas",
    ]
}
